### ISSUE TITLE
Cidade e UF direto da base do IBGE

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#1004]
## Feature Description

No sistema existem alguns locais onde é necessário solicitar informações de UF e Cidade. Hoje esse campo está em texto livre. Queremos deixar os nossos dados mais estruturados, então, será necessário utilizar as mesmas informações já conhecidas em bases de dados amplamente utilizadas, como o IBGE.

Segue a API do IBGE com a lista de Estado e Cidades.

https://servicodados.ibge.gov.br/api/docs/localidades#api-Municipios-estadosUFMunicipiosGet

- Alterar UF, Cidade do cadastro de usuários
- Alterar UF, Cidade do cadastro de organizações
 
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by mateus4k** [comment]
Dependeremos do desenvolvimento da issue #760 para usarmos esses dados no frontend 🙂

**Comment by mateus4k** [comment]
Requisitos de frontend movidos para #1025
