### ISSUE TITLE
Vitrine Tecnologica: organizações com siglas com mais de uma palavra não abre a vitrine

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#1037]
## Feature Description

Hoje a vitrine tecnologia das organizações são acessadas pelo endereço: https://plataformasabia.com/vitrine/SIGLA

No entanto, tem algumas siglas com mais de uma palavra, que acaba não funcionando a URL com esse espaço entre uma palavra e outra.

Exemplo: https://plataformasabia.com/vitrine/PW TECH

Uma sugestão é colocar um hifen nos espaços entre palavras .

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by luizeboli** [comment]
@nichollasrennah essa issue precisa de um esforço de API primeiro, para poder gerar o slug das iniciais da instituição.

É mais complexo do que eu conheço de Adonis, será necessário o apoio de alguém mais experiente nesse assunto

**Comment by luizeboli** [comment]
Depende da https://github.com/ufersa/plataforma-sabia/issues/1040
