### ISSUE TITLE
Implementar slug para iniciais de instituições 

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#1040]
## Feature Description

Existem instituições onde as inicias contém mais de uma palavra, logo precisaremos criar um slug para as iniciais da instituição, e assim tornar acessível a página de vitrines

---------------

## Acceptance criteria

* Slug com as iniciais da instituição indexados no algolia 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
Já iniciou essa issue @alexandreadames ?
