### ISSUE TITLE
Problema com mapas

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#1045]
## Feature Description

Estamos tendo problemas na visualização de mapas e também quando tem campos que precisam pesquisar no google maps.

![image](https://user-images.githubusercontent.com/48101231/119041679-49865600-b98d-11eb-86f3-49acc78d791a.png)

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by mateus4k** [comment]
Consertado 👍
