### ISSUE TITLE
Checar pela thumbnail ao exibir galeria de imagens

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#1058]
## Feature Description

Existem casos onde a API devolve o array de imagens da tecnologia sem o item da thumbnail. Isso quebra a galeria de imagens dos detalhes.

**Comment by nichollasrennah** [comment]
Creio que o problema seja no cadastro e edição de tecnologias. Não está vindo a thumbnail que o usuário marca como imagem de capa.
