### ISSUE TITLE
Cadastrar Nova Tecnologia - Detalhes

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#106]
## Feature Description

Criar página de detalhes (passo 2) e componentes relacionados que se façam necessários para a referida página. Deve-se seguir o layout conforme imagem a seguir e [modelo criado no figma](https://www.figma.com/file/9ffoyCmF8jcFmiJDrdbcpB/Plataforma-Sabi%C3%A1?node-id=0%3A1) por @nichollasrennah.

![image](https://user-images.githubusercontent.com/6104632/82268883-77822600-9946-11ea-9711-4bc1518704b4.png)

---------------

## Acceptance criteria
- Deve conter todos os campos disponíveis no modelo.
- A página deve ser o mais similar possível (não necessariamente 100% idêntica) ao modelo.

## Implementation Brief
- Deve-se utilizar os componentes do [Form](https://github.com/ufersa/plataforma-sabia/blob/master/packages/web/components/Form/index.js) para criar a página;
- Caso se identifique que é possível criar componentes que podem ser reutilizados, deve-se criá-los e seguir o padrão dos componentes do Form, de modo que possam ser reutilizados.

## Additional Information
- Deve-se analisar a viabilidade (considerando tempo e tamanho da PR) de já deixar os componentes responsivos. Caso não seja viável, gerar uma nova issue para tratar especificamente da responsividade.

**Comment by lcnogueira** [comment]
Descrição inserida. Revisar quando possível, @nicholasio.

**Comment by nicholasio** [comment]
IB ✅

**Comment by nicholasio** [comment]
Fechando essa pois o que tiver faltando aqui será feito em #111
