### ISSUE TITLE
Cadastro de Tecnologia - Custos e Financiamentos

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#107]
## Feature Description

![image](https://user-images.githubusercontent.com/6104632/82268944-91bc0400-9946-11ea-9a3a-576f4325e364.png)

Os custos poderão ser detalhados da forma que está na tela:

- Descrição, tipo (Serviço, Insumo, Equipamento, Outro), quantidade, preço unitário e valor total
- Ao final, apresentar a soma do valor de todos os itens cadastrados
- Apresentar um campo texto para cadastrar observações dos custos
- Poderão cadastrar quantos itens for necessário
- Poderá não cadastrar item nenhum

Os custos se dividirão em:

**a) CUSTO DE  DESENVOLVIMENTO**
Para tecnologias em desenvolvimento (TRL 1 a 6) que poderão cadastrar quais são os custos para construir a tecnologia. Será útel para apresentar aos financiadores para conseguir investimentos para o desenvolvimento.

**b) CUSTOS DE IMPLANTAÇÃO**
Para tecnologias já maduras e disponivel (TRL 7 a 9) que mostrará o detalhamento dos custos de implantação da tecnologia.

**c) CUSTOS DE MANUTENÇÃO**
Para tecnologias já maduras e disponivel (TRL 7 a 9) que mostrará o detalhamento dos custos de assistência técnica da tecnologia. 

Na parte final, apresentar os itens de financiamento. Esses itens aparecerão somente em tecnologias em desenvolvimento (TRL 1 a 6) para que os investidores possam saber quanto aquele pesquisador precisa pra desenvolver a tecnologia.
- Tipo de financiamento (Público, privado, coletivo)
- Situação do financiamento (Não adquirido, Em aquisição, Já adquirido)
 

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nicholasio** [comment]
@nichollasrennah @alexandreadames @lcnogueira ainda precisamos discutir algo dessa tela? A forma com que os custos estão elencados aí é da forma que deve ser? Será que precisamos ver com o contador qual seria a forma ideal dessa tela e pra armazenamento dos dados?

**Comment by alexandreadames** [comment]
@nicholasio Essa tela reflete a ideia original. No início se pensou dessa forma. Lembro que @nichollasrennah ficou de ver com o professor Kleber se seria ideal ficar assim ou deveria ter outro formato.

**Comment by lcnogueira** [comment]
Pois, se possível, vamos aguardar o retorno de @nichollasrennah após falar com Kleber, e só depois iniciamos essa.

**Comment by nichollasrennah** [comment]
Conversei com Kleber e Jean Berg e vamos manter como foi programado iniciamente e colocado na interface.
