### ISSUE TITLE
Cadastro de Tecnologia - Resumo

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#110]
## Feature Description

Criar página de resumo (último passo) e componentes relacionados que se façam necessários para a referida página. Deve-se seguir o layout conforme imagem a seguir e [modelo criado no figma](https://www.figma.com/file/9ffoyCmF8jcFmiJDrdbcpB/Plataforma-Sabi%C3%A1?node-id=0%3A1) por @nichollasrennah.

![image](https://user-images.githubusercontent.com/6104632/82269118-07c06b00-9947-11ea-9f90-54378fa58c5b.png)

---------------

## Acceptance criteria
- Deve conter todos os campos disponíveis no modelo.
- A página deve ser o mais similar possível (não necessariamente 100% idêntica) ao modelo.

## Implementation Brief
- Deve-se criar novos componentes que possam ser reutilizados nesta página de resumo.

## Additional Information
- Deve-se analisar a viabilidade (considerando tempo e tamanho da PR) de já deixar os componentes responsivos. Caso não seja viável, gerar uma nova issue para tratar especificamente da responsividade.

**Comment by lcnogueira** [comment]
Descrição inserida. Revisar quando possível, @nicholasio.

**Comment by nicholasio** [comment]
Aqui não utilizariamos os components do form em si já que seria somente exibindo o resumo de todas as informações cadastradas.

**Comment by lcnogueira** [comment]
Atualizei a descrição.

**Comment by nicholasio** [comment]
IB ✅
