### ISSUE TITLE
Associar Tecnologia a Usuário

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#113]
## Feature Description

Toda tecnologia deve está associado a pelo menos um usuário (O usuário que está criando a tecnologia).

Além disso deve ser possível associar outros "Autores" que nesse caso poderão ser ou não usuários no sistema. @alexandreadames precisamos pensar se todos os autores da tecnologia (https://github.com/ufersa/plataforma-sabia/issues/109) precisam ser usuário no sistema, estou inclicado a sim,  e caso eles não tenham um usuário a gente cria na etapa de cadastro, uma vez que jah estamos pendindo nome e email (gerariamos uma senha randomica e caso eles queiram se logar eles fariam o processo de recuperar a senha) cc @nichollasrennah @lcnogueira 

---------------

## Acceptance criteria

Passar em todos os testes funcionais.

### Modelagem:

![Responsibility Model](https://user-images.githubusercontent.com/13112022/82737070-83823500-9d04-11ea-83d2-21c918fb8248.png)

Criação do esquema `technology_user`, que possui um outro campo `role`. A relação irá guardar o usuário e a tecnologia, bem como sua responsabilidade. Responsabilidades:

**Owner**: Criador da tecnologia
**Developer**: Desenvolvedor da tecnologia
**Institution**: Representante da instituição desenvolvedora
**Technical Assistance**: Assistência Técnica

Além disso o esquema `user` teria um `organization`, caso o user esteja ligado a uma empresa ou instituição, esse compo seria opcional ou seja nullable.

### Modelos e Relacionamentos

Criação do Modelo `TechnologyUser` para  a tabela pivô. Esse modelo é necessário, pois o campo a mais `role` deve ser tratato.

```javascript
User belongsToMany Technology
Technology belongsToMany User
```

### Rotas

No TechnologyController:

`POST technologies/:idTechnology/users/:idUser`

Passar o `role` no body 

`DELETE technologies/:idTechnology/users/:idUser`

Dessassocia o usuário da tecnologia

`GET /technologies/:id/users?role=`

Retorna todos os usuários relacionados aquela tecnologia com suas responsabilidades. Se `owner` for passado, realizar a filtragem.

**Comment by nicholasio** [comment]
@alexandreadames fiz uma pequenas mudanças:

- Owner no lugar de "Creator"
- `role` no lugar de `responsibility`. `responsiblity` fica meio estranho. Nesse caso esse `role` teria um escopo limitado ao papel do usuário naquela tecnologia.

**Comment by alexandreadames** [comment]
Vlw @nicholasio desculpe meu inglês ruim.

**Comment by nicholasio** [comment]
@alexandreadames o inglês não estava errado, foi só a escolha das palavras mesmo, `owner` e `role` são mais comuns :D
