### ISSUE TITLE
Alterar imagem de banner de edital

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#1138]
## Feature Description

**Precisa alterar o banner de edital pois as inscrições foram prorrogadas.** 

Versão Mobile:
![Banner edital mobile](https://user-images.githubusercontent.com/48101231/127924366-cb2dcea1-98f1-44af-9fda-c8d1d16f0ef8.png)

Versão Desktop:
![Banner edital edital](https://user-images.githubusercontent.com/48101231/127924375-84f70d89-c9de-44e2-820d-fadeb144b12f.png)

**Apontar para o seguinte link:** https://blog.plataformasabia.com/prorrogadas-as-inscricoes-para-o-edital-de-projetos-de-inovacao-e-empreendedorismo-tecnologico

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by andreluizlq** [comment]
Eu subo para qual branch?

**Comment by luizeboli** [comment]
A branch você cria. E no Pull Request sempre para a master
