### ISSUE TITLE
Alterar banner edital

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#1167]
## Feature Description

![Edital_tecnologias_banner_3](https://user-images.githubusercontent.com/48101231/131720705-744ccee2-a11e-4644-a8ca-434a328f0187.png)

Apontar para o seguinte link:

https://blog.plataformasabia.com/divulgado-resultado-preliminar-do-edital-de-selecao-de-projetos-de-inovacao-e-empreendedorismo

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by luizeboli** [comment]
Faltou adicionar o banner do mobile

**Comment by nichollasrennah** [comment]
![Edital_tecnologias_banner_mobile_3](https://user-images.githubusercontent.com/48101231/131730416-3bcc03fe-abca-423f-9261-204d59065706.png)
