### ISSUE TITLE
Criar Rotas Protegidas 

### ISSUE THREAD

**Issue by NaylsonFerreira** [ufersa/plataforma-sabia#119]
## Feature Description

Criar um componente "Protected" para que possamos proteger rotas e/ou componentes. 
Exemplo de uso:

**Proteger por estado de autenticação (só renderiza os filhos caso esteja logado).**

```javascript
<Protected>
	<FormWizard
		onSubmit={handleSubmit}
		onPrev={({ prevStep }) => setCurrentStep(prevStep)}
		currentStep={currentStep}
		steps={newTechonologySteps}
	/>
</Protected>
```

**Proteger por `role`.**
Renderize `children` caso o usuário esteja logado e possua a `role` passada.

```javascript
<Protected role="admin">
	<Components />
</Protected>
```

Por padrão caso o usuário não esteja logado, será mostrado o modal de login, no lugar de `children`. Após fazer o login caso o usuário tenha permissão ele poderá então visualizar `children`.

Caso o usuário não tenha permissão (e esteja logado) deverá ser renderizado um componente `<NotAuthorized />` com uma mensagem padrão (design a ser definido).

O componente `Protected`  também poderá receber (de forma opcional) um `redirectTo` para que caso o usuário não tenha permissão (após logado) ele ser redirecionado para a rota específicada em `redtirectTo`.

---------------

## Acceptance criteria

* `<Protected>` não renderiza `children` caso o usuário não esteja logado ou não tenha permissão.
* `<Protected>` não renderiza `children` e mostra o formulário de login caso o usuário não esteja logado.
* `<Protected>` não renderiza `children` e mostra o formulário de login caso o usuário não esteja logado. E após se logar e o usuário tiver permissão renderiza `children`
* `<Protected role="admin" redirectTo="/">` não renderiza `children` e redireciona o usuário para `redirectTo` caso ele **esteja logado** e não possua permissão.
* `<Protected role="admin" ` não renderiza `children` e exibte o componente `NotAuthorized` ocaso ele **esteja logado** e não possua permissão.

## Implementation Brief

* Criar o componente `NotAuthorized.js` em `packages/web/components/Authorization/`
* Criar o componente `Protected.js` em  `packages/web/components/Authorization/`
* Exportar ambos os componentes em  `packages/web/components/Authorization/index.js`
* `Protected.js` deverá usar o hook `useUser` para verificar se o usuário está logado e suas devidas permissões.

Exemplo:
```javascript
const Protected = ({ children, redirectTo, role }) => {
   const user = useUser();
   
   if (!user) {
     // show login modal.
   }

   if (role && user.role !== role) {
      if (redirectTo) {
        // redireciona
      } else {
         return <NotAuthorized />
      }
   }

   return (<>{children}</>)
}
```

**Comment by nicholasio** [comment]
IB finalizado.

Deem uma olhada ai @lcnogueira @marcusmota
