### ISSUE TITLE
Slug deve ser único.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#131]
## Feature Description

O Slug é gerado a partir do title, porém ele deve ser sempre `unique`, caso existem duas tecnologias com nomes iguais (ou nomes um pouco diferente que geram o mesmo slug) precisamos adicionar '-1', '-2' e assim por diante.

---------------

## Acceptance criteria

* Se eu criar uma tecnologia com o nome "Tecnologia do Semiárido" essa tecnologia deve ser criada com o slug 'tecnologia-do-semiarido'
* Se eu criar outra tecnologia com o mesmo nome essa tecnologia deve ser criada com o slug 'tecnologia-do-semiarido-1'
* Se eu criar outra tecnologia com o mesmo nome essa tecnologia deve ser criada com o slug 'tecnologia-do-semiarido-2'
* Se eu criar N tecnologias com o mesmo nome essa tecnologia deve ser criada com o slug 'tecnologia-do-semiarido-(N-1)'

## Implementation Brief
* Atualmente os slugs estão sendo criado com '.' (pontos finais), esse ponto final não deve existir no slug.
* Criar uma função chamada `createUniqueSlug(model, columnNameToSlugify, slugColumn)`. Ex: `createUniqueSlug(model, 'title', 'slug');`
* Na hora de criar o slug, realizar uma consulta `regexp` pelo campo `slug` usando o slug criado a partir do título. 
```
SELECT slug FROM technologies WHERE slug REGEXP '{slug}.*(-(\d*))?$'
```
A consulta acima retorna tanto slugs com o '-N' e sem ele.
* Por motivos de perfomance, adicione um index ao campo slug na migration technology.
* Escrever testes **unitários** para a nova função criada e testes **funcionais** para a API.

**Comment by marcusmota** [comment]
Só um detalhe, pelo o que percebi, na consulta antes de gerar o slug estamos considerando o “count” das slugs para determinar a próxima slug, entretanto se uma slug for deletada (a terceira no meio de 5 por exemplo) a última continua “slug-5” e ao realizar o count, iremos receber o count como 5 na mesma, que irá gerar a slug duplicada 👍

**Comment by nicholasio** [comment]
> Só um detalhe, pelo o que percebi, na consulta antes de gerar o slug estamos considerando o “count” das slugs para determinar a próxima slug, entretanto se uma slug for deletada (a terceira no meio de 5 por exemplo) a última continua “slug-5” e ao realizar o count, iremos receber o count como 5 na mesma, que irá gerar a slug duplicada 👍

Verdade, nesse caso podemos verificar o "count" do ultimo slug. A consulta mysql em tese está capturando mas não sei se tem como retornar as capturas, mas de qualquer forma é só fazer a verificação quando receber os resultados.
