### ISSUE TITLE
Adequar frontend às mudanças nos dados

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#133]
## Feature Description

Ajustar componentes do frontend para adequá-los aos novos campos do backend após as mudanças introduzidas pela PR #114. 

## Acceptance criteria
- O layout dos cards deve exibir adequadamente as novas informações não deve quebrar;
- A busca da página de busca deve continuar funcional, incluindo os filtros, ordenação e paginação;
- A sincronização da URL deve continuar ocorrendo de maneira adequada e amivágel (sem espaços, acentos nem leitra maiúsculas) caso o usuário busque por um termo ou filtre por uma categoria;
- Os dados do BD devem ser corretamente indexados no algolia caso o usuário execute o script  `algolia:index`;

## Implementation Brief
Com as mudanças realizadas, será necessário:
- Identificar e ajustar os cards com as novas informações da nossa API: 
  - Remover/substituir `region`, `place`, `url` e price;
  - Remover badges de `category` e `price`;
  - Atualizar `logo` por `thumbnail`;
- Identificar e ajustar novas informações da página de busca:
  - Remover/substituir replicas de `price_asc` e `price_desc` (o campo `price` não mais existe no BD);
  - Remover/ajustar facet de `region` (campo não mais existe no BD);
  - Atualizar facet de `category` e `algoliaHelper` para adequar os novos campos de category e manter URL adequadamente sincronizada com a busca.
- Atualizar comando de indexação de dados do backend para o Algolia ( `AlgoliaIndex`):
  - Ajustar `searchableAttributes`;
  - Ajustar `attributesForFaceting`;
  - Ajustar `replicas`;
- Criar função que calcula a quantidade de semanas/meses/anos através do campo de quantidade de dias para implantação da tecnologia (`installation_time`). Será útil para exibir a informação nos cards a partir da quantidade de dias.
- Ajustar tempo do `debouncedSearch` + tempo de debounce para sincronização da URL. Atualmente, os tempos estão sendo somados e está levando cerca de 1 seg (muito tempo).

**Comment by nicholasio** [comment]
IB ✅
