### ISSUE TITLE
Ajustar rota de cadastro de tecnologia

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#148]
## Feature Description

Ajustar o fluxo de cadastro de tecnologia na API para:
- Associar termos à tecnologia;
- Indexar os termos da taxonomia de categoria, juntamente com os dados da tecnologia, no algolia.

---------------

## Acceptance criteria
- Se um `term`, pertencente a qualquer taxonomia, for enviado na rota de cadastro de tecnologia, ele deve ser associado àquela tecnologia na nossa base de dados;
- Se um `term` pertencente à taxonomia `Category` for enviado na rota de cadastro de tecnologia, ele deve ser indexado no algolia;
- Se um `term` **não** pertencente à taxonomia `Category`, for enviado na rota de cadastro de tecnologia, **não** deve ser indexado no algolia;

## Implementation Brief

- A rota de cadastro (`store`)  da tecnologia, deve aceitar, **de maneira opcional**, o envio de um array de `termId` ou `slug`. Ex.:
```
terms: ['Saneamento', 10]
```
Caso essa propriedade seja enviada, para cada um desses slugs ou termIds deve ser criada uma relação entre tecnologia e term na tabela `technology_term`
- Caso o array seja enviado e um dos `terms` pertença à `taxonomy` cujo slug é `CATEGORY`, ele deve ser associado no algolia como uma propriedade chamada `category`, juntamente com as demais propriedades da tecnologia:
```
...technologyData,
category: term.term
```

**Comment by lcnogueira** [comment]
@nicholasio @alexandreadames, quando possível, vejam a descrição dessa issue. Vejam se tem algo que deveria ser contemplado e não está aí. Vou iniciar nessa demanda hoje à noite.

**Comment by nicholasio** [comment]
✅

**Comment by alexandreadames** [comment]
👍
