### ISSUE TITLE
Detalhamento de Tecnologia - Estágios de Desenvolvimento

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#213]
## Feature Description

Encontrar a melhor forma de mostrar qual o nível de maturidade da tecnolgia e que fique visualmente agradável ao usuário e adaptável ao design das telas.

![image](https://user-images.githubusercontent.com/48101231/93473509-79480000-f8cc-11ea-96f3-346b4a3de0cb.png)

- Será apresentando apenas os níveis de 7 a 9, mas é necessário mostrar todos os níveis para visualmente o usuário saber que a tecnologia já passou por vários estários.
 
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nicholasio** [comment]
@nichollasrennah Isso é uma coisa que nem implementamos ainda, pode descrever aqui como isso funciona? Quem é que define o estágio? É o curador ou o pesquisador que cadastra?

**Comment by nichollasrennah** [comment]
É para implementar. Existe um campo no cadastro que é o nível de maturidade. São 9 níveis. Apresente a imagem estática dos níveis e apenas uma seta vai se mover entre os níveis de 1 a 9. Como descrito na imagem. Outra opção é gerar 9 imagens que serão trocadas de acordo com o nível escolhido.

**Comment by nicholasio** [comment]
@nichollasrennah Eu acho que seria interessante aguardar o @JoaoPauloSMoura fazer a auditoria do design e dar uma sugestão sobre como implementar essa parte aqui. Essa imagem como um termômetro será bem complicada de implementar e me parece um pouco estranha.

**Comment by nicholasio** [comment]
@nichollasrennah Lembrando que precisamos de um design pra essa issue aqui tbm.

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura Precisamos encontrar a melhor forma de colocar esse termômetro. Alguma sugestão?

**Comment by JoaoPauloSMoura** [comment]
sim, na vdd ele não está de acordo com o layout, sugiro deixar ele mais minimalista e usando o padrão de cores que a gente criou, desde o vermelho até o verde.

**Comment by nichollasrennah** [comment]
Te enviei o layout que fiz disso aí no

**Comment by JoaoPauloSMoura** [comment]
show @nichollasrennah recebi aqui

**Comment by nichollasrennah** [comment]
@nicholasio O @JoaoPauloSMoura já reformulou o gráfico da TRL lá no Figma. Como iremos apresentar somente tecnologias com estágios de 7 a 9, sugiro gerar 3 imagens (uma em cada estágio) para apresentar de acordo com o nível da tecnologia. Inclusive acho que seja a melhor opção para a responsividade.

**Comment by nichollasrennah** [comment]
@luizeboli Coloquei essa issue para você, visto que você fez esse componente na tela de parecer do curador. É algo simples. Apenas replicar nessa tela.

**Comment by luizeboli** [comment]
> @luizeboli Coloquei essa issue para você, visto que você fez esse componente na tela de parecer do curador. É algo simples. Apenas replicar nessa tela.

Perfeito @nichollasrennah , o componente que eu fiz atende sem problemas, o único detalhe é que essa issue vai depender da outra pra ser executada.
