### ISSUE TITLE
Detalhamento de Tecnologia - Georreferenciamento

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#217]
## Feature Description

https://www.figma.com/file/9ffoyCmF8jcFmiJDrdbcpB/Plataforma-Sabi%C3%A1?node-id=333%3A680

![image](https://user-images.githubusercontent.com/6104632/91647158-cc493880-ea2d-11ea-88a7-8c7d622689cb.png)

- Essa aba estará ativa para todos usuários, mas seu conteúdo está liberado somente para usuários logados. Usuários não logados aparecer a mensagem que esse conteúdo está disponível apenas para usuários cadastrados. E mostrar o link para logar ou se cadastrar.
---------------

## Acceptance criteria

* Os locais onde há tecnologia está sendo implantada e desenvolvido devem ser renderizados no mapa.

## Implementation Brief

* Utilizar a API do Google maps para renderizar os "places" com os "pins" do Google Maps.
* No getInitialProps, usar o `getTechnologyTerms` para retornar as taxonomias `REGION` and `GOOGLE_PLACES` e suas respectivas metas com latitude e longitude.
* Utilizar o componenent `Protected` para só mostrar essa aba para usuários logados.

**Comment by nicholasio** [comment]
@marcusmota Passando essa issue aqui pra vc, qualquer dúvida grita.

**Comment by nichollasrennah** [comment]
@marcusmota essa issue já não era pra está fechada?

**Comment by marcusmota** [comment]
Sim, pode fechar!
