### ISSUE TITLE
Alteração de Email

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#218]
## Feature Description

Essa issue é para implementar o fluxo de alteração de email. De maneira geral, deve funcionar da seguinte forma:

- Usuário altera seu email (antes de o usuário poder fazer isso, ele precisa inserir sua senha novamente)
- ~~Seu status é alterado para `pending_new_email_verification`~~
- Um email é enviado para confirmar que o usuário é dono do novo email.
- Quando o usuário confirma o novo email, seu email é de fato alterado para o novo.
- Enquanto o usuário não confirma o novo email, para todos os efeitos a conta dele ainda está associada ao seu email antigo.

---------------

## Acceptance criteria

* Usuário pode solicitar a alteração do seu Email
* Um Email é enviado para confirmar que o usuário é dono do novo Email.
* Quando o usuário confirma o novo Email, seu Email é de fato alterado para o novo.
* Enquanto o usuário não confirma o novo Email, para todos os efeitos a conta dele ainda está associada ao seu Email antigo.

## Implementation Brief
* Criar o campo `temp_email` em `Models/User.js`
* Criar a rota **POST** `/user/change-email`
   * Essa rota espera como parâmetro o novo Email
   * Salvar o novo Email em `temp_email`
* Criar a função `changeEmail` em `UserController.js`
   * ~~Alterar o status do usuário para `pending_new_email_verification`~~
   * Enviar um Email com o token de confirmação para o novo endereço de Email
* Criar a rota **PUT** `/user/change-email`
   * Essa rota espera como parâmetro o token enviado para o novo email
   * Atualizar o endereço de Email do usuário e enviar um Email de confirmação

**Comment by nicholasio** [comment]
@NaylsonFerreira acho que é isso mesmo. Agora que eu estou relendo essa issue eu estava pensando se o novo status é realmente necessário. Pois se o usuário tiver um email pendente dá pra saber isso caso ele tenha o temp_email.

Acho que podemos retirar a parte do novo status.

O que acham @marcusmota @mateus4k @lcnogueira

**Comment by lcnogueira** [comment]
Acho que é isso mesmo: como já tem o `temp_email` e ele continua com o e-mail antigo pra efeitos do sistema enquanto não validar, já resolve. Acho que não precisaria do status não.

**Comment by lcnogueira** [comment]
Acho que seria bom adicionar alguns testes aqui. Poderia se basear ali no critério de aceitação :bulb:
