### ISSUE TITLE
Área do Usuário - Meu Perfil

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#219]
## Feature Description

https://www.figma.com/file/9ffoyCmF8jcFmiJDrdbcpB/Plataforma-Sabi%C3%A1?node-id=0%3A1

![image](https://user-images.githubusercontent.com/6104632/84571070-830b1600-ad67-11ea-97d1-1309e8b7c945.png)

![image(1)](https://user-images.githubusercontent.com/12154623/86055332-f97b6980-ba31-11ea-9153-248778eca939.png)

Implementar a área "Meu perfil" onde o usuário pode alterar a sua senha e dados pessoais como nome e outros dados.

Por hora não deverá ser possível alterar email (https://github.com/ufersa/plataforma-sabia/issues/new?template=feature_request.md).

---------------

## Acceptance criteria

* O usuário logado pode acessar a área do perfil e alterar seus dados básicos.
* O usuário não logado não pode acessar essa área.

## Implementation Brief

* Na issue https://github.com/ufersa/plataforma-sabia/issues/70 onde "Minhas tecnologias" foi criado, ela ficou sendo a "index" da rota `user/my-account`, agora essa tela deve ser a tela principal e a rota de tecnologias deve ser `user/my-account/technologies`
* O fluxo de alteração de senha será separado do restante dos dados, o usuário deve clicar em um link "Alterar minha senha" onde será aberto um formulário específico para alterar a senha, o usuário deve entrar com a senha antiga e a senha nova (duas vezes para confirmar). Essa funcionalidade vai requerer alteração na API com a criação de uma rota específica para alteração de senha.
* Deverá ser cirado uma rota na API `POST `user/change-password` que receberá a senha atual e a nova senha. A API não precisa receber a senha nova duplicada, pois a verificação se a nova senha bate será feita somente no front. Note que essa rota requer que o usuário esteja autenticado, mas ainda assim irá verificar se a senha atual está correta para ter certeza de essa é uma operação iniciada pelo dono da conta.

**Comment by nicholasio** [comment]
@nichollasrennah precisamos de design ou pelo menos uma idea de como será essa tela, campos etc.

**Comment by nicholasio** [comment]
OBS: Essa issue não dá pra ser feita em paralelo com #70 , creio ser melhor fazer primeiro a #70 . Mas dá pra fazer essa primeira e depois a outra tbm.

**Comment by lcnogueira** [comment]
Não entendi o que disse no final, @nicholasio.

**Comment by nicholasio** [comment]
A rota de alterar a senha foi implementada nessa PR #269

**Comment by lcnogueira** [comment]
Alguns campos ainda não existem. Decidiu-se incluir, por hora, somente os campos existentes e, depois, incluir os campos em uma nova issue: #273
