### ISSUE TITLE
Transformar componentes visuais em responsivos

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#22]
Os componentes criados na issue #17 ainda não estão responsivos.

**Comment by nicholasio** [comment]
Dependendo da resolução o menu gera um scrol horizontal. Provavelmente precisamos transformar o menu em um hamburguer menu a partir de um certo breakpoint

![image](https://user-images.githubusercontent.com/6104632/78450574-00bef100-7656-11ea-8785-daa2a412face.png)
