### ISSUE TITLE
Favoritos

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#253]
## Feature Description

Usuários logados do site podem favoritar tecnologia. As tecnologias favoritadas serão listadas em seu perfil.

---------------

## Acceptance criteria

* Um usuário logado pode favoritar qualquer tecnologia.
* Um usuário logado pode listar todas as suas tecnologias favoritas.
* Um usuário logado pode desfavoritar uma ou mais tecnologia favorita.
* Usuários que tenham a permissão `LIST_BOOKMARKS` podem listar todas os usuários que favoritaram uma determinada tecnologia.

## Implementation Brief

* Criar controller `UserBookmarks.js`
* Criar Migrations
* `user.bookmarks()` deve retornar as tecnologias favoritas do usuário.
* Implementar as seguintes rotas no controller `UserBookmarks.js`
* Criar seed com fake reviews (só pra testes)
* Escrever testes

**Rotas**
|   método | rota  |  query/body params  |   auth |
|---|---|---|---|
|  POST | /user/:id/bookmarks    | technologyId[] |   **Yes** - qualquer usuário logado. Não precisa de permissão specífica.
|  GET    |   /user/:id/bookmarks  | N/A  |   **Yes** - qualquer usuário logado. Não precisa de permissão específica, mas deve retornar somente os favoritos do usuário.
|  GET    |   /bookmarks  | technologyId ** |   **Yes** - Somente admins (ou que tenham a pemrissão LIST_BOOKMARKS)
|  PUT    |   N/A | N/A  | N/A
|  DELETE | /user/:id/bookmarks | technologyId[]* |   **Yes** - qualquer usuário logado; Remove da lista de favoritos do usuário logado.

* A rota recebe um array de tecnologyIds mas a operação sempre deve ser de append e no caso de remover remover somente os que foram passados.
** `GET /bookmarks?technologyId=2` retorna todos os usuários que favoritaram a tecnologia com id `2`.

**Comment by alexandreadames** [comment]
Uma pequena sugestão de alteração seguindo a mesma lógica das revisões: Nas rotas POST, GET e DELETE /user/:id/bookmarks, mudar para /user/bookmarks já que o id sempre será do usuário logado.

**Comment by nicholasio** [comment]
@alexandreadames nesse caso acho que seja interessante deixar o id na URL porquê acho que será interessante ter a possibilidade no admin de ver todas as tecnologias favoritas de um usuário.

**Comment by alexandreadames** [comment]
Sem problemas, acredito que no caso do POST poderia ser como eu falei porque mesmo sendo admin ele não poderia favoritar por outro usuário. No caso de GET e DELETE faz sentido mesmo o admin fazer, mas nesse caso é necessário criar permissões tipo LIST_BOOKMARK para usuário comum só poder listar seus próprios favoritos, DELETE_BOOKMARK para só deletar seus próprios favoritos. Bem como DELETE_BOOKMARKS para o admin, e LIST_BOOKMARKS seria para listar todos os favoritos ou apenas os favoritos de um usuário no caso do admin.
