### ISSUE TITLE
Alteração de Senha para Usuários Logado

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#254]
## Feature Description

Criar uma rota específica para permitir alteração de senha de um usuário logado.

---------------

## Acceptance criteria

* Um usuário logado pode alterar sua senha sem ir pelo fluxo de "esqueci minha senha"

## Implementation Brief
* Implementar rota no controller do usuário.
* Alterar a senha deve disparar um email confirmando a alteração da senha do usuário.
* Não deve ser possível alterar a senha de um usuário pela rota de editar usuário.
* Essa rota deve verificar se a senha passada é válida da seguinte forma:
   - Pegue o usuário logado.
   - Compare o hashed password com `hash(currentPassword)`

**Rotas**
|   método | rota  |  query/body params  |   auth |
|---|---|---|---|
|  PUT | /user/:id/change-password    | currentPassword, newPassword |   **Yes** - qualquer usuário logado. Não precisa de permissão specífica. Mas obviamente só pode alterar a própria senha.

**Comment by alexandreadames** [comment]
@nicholasio Pequena sugestão de alteração, como não existe permissão específica, sugiro que a rota seja: 
`PUT  /user/change-password`. Como essa rota só edita a própria senha não há necessidade de passar o id do usuário .

**Comment by nicholasio** [comment]
tem razão. 👍
