### ISSUE TITLE
Cadastro/Edição de Tecnologia - Integrar Responsáveis.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#256]
## Feature Description

Ver #109 

Na tela de edição de responsáveis no cadastro de tecnologia o usuário que está criando a tecnologia tem a opção de adicionar outros usuários que serão integrantes da tecnologia.

---------------

## Acceptance criteria

* O usuário que está cadastrando a tecnologia será sempre o primeiro responsável no repeater de responsáveis.
 **somente** o campos lattes será editável para o autor da tecnologia.
* É possível adicionar integrantes que já estejam cadastrados na plataforma.
* É possível adicionar integrantes que ainda não estejam cadastrados na plataforma.
* Ao adicionar um integrante que ainda não está cadastrado na plataforma, um novo usuário é criado com o status `invited` e com nome, email e lattes id informado pelo autor da tecnologia. Esse usuário "convidado" receberá um email informado a qual tecnologia ele foi adicionado. Um usuário `invited` não precisa confirmar seu email, **porém** sua senha será gerada aleatoriamente de modo que ele será obrigado a passar pelo fluxo de "esqueci minha senha".
   - Uma vez que o usuário `invited` altera sua senha, ele passa a ser `verified`.
* Ao adicionar integrantes que já estejam cadastrados na plataforma, esses usuários recebem um email informando que foram adicionados a uma tecnologia.
* Não haverá nenhum tipo de autocomplete na hora de adicionar integrantes, pois os dados do usuário são sensíveis.
* Caso o autor da tecnologia cadastre um usuário já existente, devemos **desconsiderar** o campo nome e lattes id. Esses dados virão diretamente do usuário cadastrado.
* Para os usuários que já foram adicionados a tecnologia, não será possível alterar nenhum dado do usuário, somente removê-lo da lista de integrantes, uma vez adicionado somente o usuário que foi adicionado a tecnologia pode alterar seu nome, email ou lattes id.

## Implementation Brief

*

**Comment by nicholasio** [comment]
@lcnogueira passando essa daqui pra você! Adicionei todas as regras de negócio, vou deixar o IB pra você definir 👍

**Comment by lcnogueira** [comment]
Blz, @nicholasio 👍

**Comment by lcnogueira** [comment]
O usuário que for adicionado como integrante a uma tecnologia deve receber qual `role`?

**Comment by nicholasio** [comment]
> O usuário que for adicionado como integrante a uma tecnologia deve receber qual `role`?

Acho que por enquanto podemos adicionar como usuário comum.
