### ISSUE TITLE
Alterar o login para retornar o papel do usuário

### ISSUE THREAD

**Issue by alexandreadames** [ufersa/plataforma-sabia#26]
O admin faz a chamada a API de login, esse endpoint retorna o usuário juntamente com seu papel. Se o papel for 'admin' o admin vai salvar o JWT token e logar o usuário no sistema. Caso o papel não seja 'admin' o client ADMIN descarta o JWT token e informa que o usuário não tem permissão para logar. Técnicamente o login será feito mas o JWT token será descartado!

**Comment by nicholasio** [comment]
@alexandreadames a rota de login já existe e será a mesma para admin e front, o que vai diferenciar é o papel/permissões que o usuário terá.

**Comment by alexandreadames** [comment]
Então eu passaria um parâmetro na rota de login apenas para checar a permissão? Tipo se ele for usuário comum e tentar logar no pelo painel admin eu iria mandar um parâmetro na requisição que vier do painel admin para checar se ele tem a permissão.

**Comment by nicholasio** [comment]
O client admin iria verificar o papel do usuário e caso seja um papel de usuário comum ele não vai aceitar o login.  Além disse todas as requests vindo do admin, serão verificadas quanto as suas permissões.

Exemplificando:

1. Usuário loga com user_1 mas esse user_1 tem papel de usuário comum. O admin não vai aceitar.
2. Uma vez logado todas as requests para o API para por exemplo, cadastrar uma nova categoria de tecnologia, irá verificar se o usuário que está fazendo a requisição tem permissão para tal. Toda as as requisições irão enviar o token JWT então conseguimos recuperar o usuário na API.

**Comment by alexandreadames** [comment]
Entendi, então no caso o próprio cliente ADIMIN iria fazer uma requisição antes para checar se o usuário possui o papel mesmo antes do login é isso?

**Comment by NaylsonFerreira** [comment]
A validação da permissão fica do lado da API, é isso? a requisição teria um status code 401?

**Comment by nicholasio** [comment]
> Entendi, então no caso o próprio cliente ADIMIN iria fazer uma requisição antes para checar se o usuário possui o papel mesmo antes do login é isso?

O admin faz a chamada a API de login, esse endpoint retorna o usuário juntamente com seu papel. Se o papel for 'admin' o admin vai salvar o JWT token e logar o usuário no sistema. Caso o papel não seja 'admin' o client ADMIN descarta o JWT token e informa que o usuário não tem permissão para logar. Técnicamente o login será feito mas o JWT token será descartado!



> A validação da permissão fica do lado da API, é isso? a requisição teria um status code 401?

Exato, a validação da permissão fica do lado da API, se eu me logar como admin, toda ação que eu tentar fazer a API vai verificar se o meu usuário tem permissão para fazer aquilo.

**Comment by alexandreadames** [comment]
Entendi, então vou alterar aqui a issue.
