### ISSUE TITLE
Criar seed para criação de usuário ADMIN

### ISSUE THREAD

**Issue by alexandreadames** [ufersa/plataforma-sabia#27]
Criar seed para criação do usuário ADMIM que possui todas as permissões do sistema. Esse é o primeiro usuário a ser criado para a área admin, inicialmente será cadastrado dessa forma:

ROLE: ADMIN

PERMISSIONS:

CREATE_USERS
CREATE_ROLES
CREATE_PERMISSIONS

**Comment by nicholasio** [comment]
@alexandreadames creio que essa issue não seja mais necessário né? isso aqui vai ser coberto pelas issues #51 #73
