### ISSUE TITLE
Ler traduções nos testes e2e

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#282]
## Feature Description

Atualmente, fazemos os asserts baseados nos textos em português ou inglês. Com isso, caso os textos mudem, os testes e2e quebrarão. O ideal é utilizar os arquivos das traduções em si, e utilizarmos as `keys` das traduções ao invés dos textos diretamente. Dessa forma, mesmo que os textos sejam modificados, os testes e2e ainda continuarão a funcionar.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by mateus4k** [comment]
Agora, com o [dynamic import](https://v8.dev/features/dynamic-import), talvez seja possível implementar essa feature com base no [helper que tentei fazer](https://github.com/ufersa/plataforma-sabia/pull/252/commits/8436985f8afc2f5c89ba2e1afd35f62dbedca74a#diff-9593faa52e480476d0f5eef99f197fbbR33-R55) recentemente :thinking:

**Comment by nicholasio** [comment]
@mateus4k Passando essa aqui pra você agora que as coisas estão um pouco mais calmas.

Eu acho que basta criar um helper que faça o import dos jsons de tradução.
