### ISSUE TITLE
Processo de Curadoria

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#283]
## Feature Description

Ver as seguintes issues: #377 #378 #379 #380 #381 #382 

O processo de curadoria é uma análise realizada por uma equipe de curadores nos cadastros de tecnologias realizados na plataforma. 

O processo de cadastro de Tecnologias envolve:

![Fluxo de cadastro Tecnologias](https://user-images.githubusercontent.com/48101231/86368608-c1537100-bc53-11ea-9fac-0b22ac8722d1.jpg)

**QUEM SÃO OS CURADORES?**
- Os curadores são pesquisadores definidos pelo Admin
- Precisa ter a opção de um usuário solicitar o papel de Curador ao Admin
- No pedido para se tornar curador será ncesspario informar em quais áreas ele é especializado na analise das tecnologias (categorias e subcategorias das tecnologias)

**COMO ESCOLHER OS CURADORES DE UM CADASTRO?**
- O sistema definirá automaticamente 1 curador para a tecnologia de acordo com a categoria e subcategoria cadastrada
- A designação ocorrerá após o pesquisador concluir o cadastro e envio.
- Será randômico a escolha curador (evitar de um mesmo curador fique com muitas análises e outros com poucas)
- Opcionalmente na área Admin será possível designar qualquer curador, mesmo de áreas diferentes

**COMO SERÁ FEITA A CURADORIA?**
- O curador terá acesso na ÁREA DO USUÁRIO a uma lista de tecnologias a serem analisadas por ele de acordo com a área de especialidade dele.
- Ao abrir o cadastro para analisar, será apresentado todos os campos do cadastro da tecnologia.
- Os campos disponíveis na análise so curador serão:
PARECER: Caixa suspensa com as opções: Aprovado, Rejeitado, Solicitar modificações
AVALIAÇÃO: Campo texto para observações da avaliação do curador.
ANEXO: Espaço para anexar arquivos pelo curador.
BOTÃO DE REGISTRO DA AVALIAÇÃO (submit)

**APROVAÇÃO DA TECNOLOGIA**
- Ao aprovar, alterar o status da tecnologia para PUBLICADA
- Enviar mensagem para o autor da tecnologia informando o aceite

**REJEIÇÃO DA TECNOLOGIA**
- Ao reprovar, alterar o status da tecnologia para REJEITADA
- Enviar mensagem para o autor da tecnologia informando o motivo da rejeição

**SOLICITAÇÃO DE MODIFICAÇÕES DA TECNOLOGIA**
- Ao solicitação alterações, mantém o status da tecnologia para PENDENTE DE ANÁLISE
- Enviar mensagem para o autor da tecnologia informando o parecer do curador e quais dados precisam ser alterados.

---------------

## Acceptance criteria

Todo o fluxo da curadoria deve ser feito.

### DER do Processo de Curadoria

![Curation Process Model](https://user-images.githubusercontent.com/13112022/92980178-8350a580-f46b-11ea-8956-4e328c6bf146.png)

### Fluxo da Curadoria:

1. O Usuário solicita o papel de curador, informando as categorias que deseja ser curador. É criado uma entrada na tabela `reviewers` com status `pending` e relacionamentos em `reviewer_categories`;
2. O usuário Admin lista os curadores e aprova ou rejeita, o sistema muda o status para `approved` ou `rejected` na tabela `reviewers`. Se `approved` o usuário ganha o papel `REVIEWER`;
3. O sistema precisa definir as tecnologias que os curadores aprovados podem optar por revisar:
Situações onde pode ocorrer a distribuição:
3.1 Após o admin mudar o status do reviewer para aprovado;
3.2 Após cadastrar a tecnologia,no ato da finalização do cadastro;
3.3 Após a atribuição automática, o curador precisa entrar na sua área e decidir se quer ou não revisar a tecnologia. Se o curador aceitar a revisão, o sistema muda o registro de `reviewer_technology`, com o `status=PENDING` para `status=ACCEPTED` e o status da technologia muda para `in_review`.
3.4 O curador possui X dias para aceitar ou rejeitar a revisão, caso os dias se passem, deve ser feito uma nova atribuição (Nesse caso um timer deve rodar uma função para verificar se a aceitação venceu baseado na data que foi feita a atribuição).
3.5 O timer de distribuição segue as seguintes regras:
3.5.1 Pega todas as tecnologias com status `pending` que não tenham um registro em `reviewer_technology`, ou que tenham um registro em `reviewer_technology` vencido.
3.5.2 Para cada registro, busca um curador com que se enquadre na categoria da tecnologia em questão e cria um registro em `reviewer_technology`, com o `status=PENDING` e a data e hora atual.
3.5.3 Após a atribuição enviar e-mail para o curador em questão.
4. O curador entra na sua área, pode ver a lista de tecnologias atribuídas as ele que estão em `in_review`. Revisa a tecnologia, é criada uma entrada em `revision`, 
_A princípio uma tecnologia só pode ser revisada por um curador_
4.1 Se o parecer do curador for `approved` ou `rejrected` o sistema envia para apreciação do admin que fará a avaliação final.
4.2 Se o parecer for `requested changes` o pesquisador pode realizar as alterações. O sistema envia um email para o pesquisador informando que um revisor requisitou mudanças. Após as mudanças serem feitas, o revisor recebe um email informando que as mudanças foram feitas. O revisor então pode criar outra entrada em `revision` que pode ser novamente `requested changes` ou `approved`. 
_A tabela `revision` irá guardar o histórico das revisões. O revisor só poderá criar uma nova entrada nessa tabela para uma dada tecnologia, caso a iteração anterior tenha sido `requested changes`;_
5. Se o pesquisador desejar alterar novamente uma tecnologia publicada deve sujeitar-se ao processo de revisão novamente, nesse caso, será necessário definir como será esse novo processo.

**Comment by nicholasio** [comment]
@alexandreadames 

vamos fazer as seguintes alterações:
 - renomear `opinion` para `assessment` 
 - `evaluation` para `description` e o campo deve ser `TEXT` e não varchar

Ficou muito bom o fluxo.

Sobre o ponto 5, acho que podemos desconsiderar isso por hora, acho que seria descenessário... o que acha @nichollasrennah

**Comment by alexandreadames** [comment]
@nicholasio @nichollasrennah @JoaoPauloSMoura @lcnogueira 
Conforme reunião feita hoje, algumas mudanças foram feitas no fluxo de curadoria, seguem as principais:

1. Uma tecnologia terá apenas um curador;
2. Após o processo de revisão apenas o admin pode publicar a tecnologia;
3. O curador possui a opção de aceitar ou não a tecnologia que lhe foi atribuída pelo sistema. O curador possui um prazo de x dias para aceitar ou rejeitar, deve ser criado um _timer_ para rodar o processo de distribuição diariamente.

Foi feita a atualização do DER e do processo no IB.

**Comment by nicholasio** [comment]
>    3.4 O curador possui X dias para aceitar ou rejeitar a revisão, caso os dias se passem, deve ser feito uma nova atribuição (Nesse caso um timer deve rodar uma função para verificar se a aceitação venceu baseado na data que foi feita a atribuição).
>    3.5 O timer de distribuição segue as seguintes regras:
>    3.5.1 Pega todas as tecnologias com status `pending` que não tenham um registro em `reviewer_technology`, ou que tenham um registro em `reviewer_technology` vencido.
>    3.5.2 Para cada registro, busca um curador com que se enquadre na categoria da tecnologia em questão e cria um registro em `reviewer_technology`, com o `status=PENDING` e a data e hora atual.
>    3.5.3 Após a atribuição enviar e-mail para o curador em questão.
Essa questão do timer e dos dias que o curador tem pra aceitar a revisão vai requerer um cron job sendo executado no serivodor da API. 

Minha única preocupação é que isso complica um pouco as coisas. Será que teremos tantos curadores assim. Vamos supor que só temos 1 curador para essa categoria e o curador não aceitou nos X dias, ele vai perder a revisão e vai ser distribuído novamente pra ele?
> 4. O curador entra na sua área, pode ver a lista de tecnologias atribuídas as ele que estão em `in_review`. Revisa a tecnologia, é criada uma entrada em `revision`,
Em que momento o curador vai aceitar a revisão?
>    _A princípio uma tecnologia só pode ser revisada por um curador_
>    4.1 Se o parecer do curador for `approved` ou `rejrected` o sistema envia para apreciação do admin que fará a avaliação final.
Quem serão esses admins que farão a avaliação final?

> 5. Se o pesquisador desejar alterar novamente uma tecnologia publicada deve sujeitar-se ao processo de revisão novamente, nesse caso, será necessário definir como será esse novo processo.
Isso aqui complica bastante as coisas, será que é realmente necessária? Eu acho que podemos deixar alguns campos abertos e limitar somente certos campos... Tipo, terá que passar por revisão para corrigir um erro de digitação? para adicionar uma nova imagem?

**Comment by nichollasrennah** [comment]
Minha única preocupação é que isso complica um pouco as coisas. Será que teremos tantos curadores assim. Vamos supor que só temos 1 curador para essa categoria e o curador não aceitou nos X dias, ele vai perder a revisão e vai ser distribuído novamente pra ele?
**Vimos a necessidade de colocar um aceite por parte dos curadores porque possa ser que ele não possa avaliar naquele momento e o cadastro da tecnologia iria parar por falta de uma avaliação dele. Por isso na necessidade de exigir que ele dê um aceite que irá realizar a avaliação.** 
Em que momento o curador vai aceitar a revisão?
**Quando ele receber o email ou na área do usuário e clicar no botão aceitar revisão na tecnologia listada**
Quem serão esses admins que farão a avaliação final?
**À princípio serão 3 admins cuidando disso (Eu, Jean e David)** Sabemos que teremos poucos registros no início devido a dificuldade que estamos tendo com os pesquisadores.
Isso aqui complica bastante as coisas, será que é realmente necessária? Eu acho que podemos deixar alguns campos abertos e limitar somente certos campos... Tipo, terá que passar por revisão para corrigir um erro de digitação? para adicionar uma nova imagem?
**Não temos como garantir que o pesquisador vai alterar somente os campos pedidos. Por isso, tudo que ele alterar precisa passar pelo crivo do mesmo avaliador que já realizou as primeiras revisões nesse pedido. A não ser que consigamos identificar alterações simples e mais abrangentes a nível de código para definir se envia para curadoria ou não.**

**Comment by alexandreadames** [comment]
@nichollasrennah analisando da perspectiva da implementação essa questão da aceitação complica realmente as coisas, eu estava pensando aqui, imagine a seguinte situação:

1. Tecnologia com categoria "Recursos hidrícos" foi cadastrada => A função de distribuição é disparada;
2. Existem 2 curadores com essa categoria. Na primeira iteração a função vai atribuir ao curador 1 essa tecnologia;
3. Se passaram 3 dias e o curador 1 não aceitou; 
4. Na segunda iteração sistema terá que excluir o curador 1 da distribuição levando em consideração que ele não aceitou por tempo de expiração, isso vale pra rejeição também e irá atribuir para o curador 2;
5. Se o curador 2 não aceitar em 3 dias, ou rejeitar. Na terceira iteração não haverá mais curadores;
6. Concluindo, na distribuição o sistema não poderá usar curadores que não aceitaram por expiração ou rejeição, isso levando em consideração um tecnologia específica.

A minha sugestão é:

Quando a tecnologia for finalizada ou o curador for aprovado, rodar a função de distribuição que fará o seguinte:

1. Irá atribuir a tecnologia ao curador e mudar o status da tecnologia para `in_review`;
2. Se o curador, na revisão, clicar em `approved` mudar o status da tecnologia para `published` sem passar pelo admin;
3. Se o curador, na revisão, pedir `requested changes`, o pesquisador muda;
4. Se o curador, na revisão, clicar em `rejected` a tecnologia é mudada para `rejected`, mas o admin pode alterar o status se assim desejar, caso o pesquisador se sinta prejudicado entra em contato com os admins;
5. Com relação a questão do curador não querer de jeito nenhum a tecnologia, podemos deixar apenas um botão para ele rejeitar. O status da tecnologia voltaria para `pending` e a distribuição seria refeita, e desconsideraria curadores que tenham rejeitado aquela tecnologia antes.

**Comment by nicholasio** [comment]
Eu acho que devemos remover esse step do curador aceitar. Creio que seria mais fácil o curador solicitar que outro revise no lugar dele. Logo seria um "opt-in" por padrão com a possibilidade de "opt-out" por parte do curador.

**Comment by alexandreadames** [comment]
O curador poderia setar o próprio status como no Slack:

![set status](https://user-images.githubusercontent.com/13112022/93003565-2f4ecb00-f516-11ea-852d-c9f13b6269e6.png)

Quando ele tivesse de férias não seria atribuído nada.

**Comment by alexandreadames** [comment]
> Eu acho que devemos remover esse step do curador aceitar. Creio que seria mais fácil o curador solicitar que outro revise no lugar dele. Logo seria um "opt-in" por padrão com a possibilidade de "opt-out" por parte do curador.

Acho interessante essa ideia, assim quando ele não quisesse revisar de jeito nenhum, ele rejeitaria e seria atribuído a outro.

**Comment by JoaoPauloSMoura** [comment]
@nicholasio e se o curador deixar de entrar no perfil dele, durante um mês, a tecnologia vai passar um mês sem mudança de status?

**Comment by nicholasio** [comment]
@JoaoPauloSMoura Ai entraria o admin/editor que iria fazer esse acompanhamento e cobrar dos curadores

**Comment by nicholasio** [comment]
Lembrando que eles receberiam um email informando a nova tecnologia

**Comment by JoaoPauloSMoura** [comment]
entendi, então acho que é tranquilo
