### ISSUE TITLE
Atualizar documentação da plataforma

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#286]
## Feature Description

Atualizar a documentação para que fique a mais clara para que outras pessoas possam contribuir com o projeto. Deve-se:
- Escrever a documentação em inglês
- Deixar claro como configurar o ambiente de desenvolvimento
- Deixar claro como contribuir (`CONTRIBUTING.md`)
  - Padrões a se seguir
- Atualizar `README` do diretório principal e cada um dos `READMEs` dos packages.
- Incluir seção ao final do `README` com os contribuidores do projeto;

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nicholasio** [comment]
Posso fazer isso aqui 👍

**Comment by lcnogueira** [comment]
@nicholasio , conforme combinado na última reunião, estou pegando essa aqui :+1:
