### ISSUE TITLE
Soluções em Destaque - Homepage

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#289]
## Feature Description

Em #276 foi implementado as soluções recentes na homepage. Agora precisamos implementar a primeira versão das "soluções em destaque'. As soluções em destaque serão simplesmente as soluções com mais likes na plataforma. Por isso precisamos fazer o "orderBy" por "likes" ao pegar as tecnologias em destaques.

Um outro detalhe é que é interessante fazer a "de-duplicação" ou seja se uma tecnologia já foi exibida como destaque mas ela também se enquadradia como recente, ela não deve ser exibida nas tecnologias recentes, para isso precisaremos implementar um parâmetro notIn na rota /tecnologies.

---------------

## Acceptance criteria

* Na homepage as tecnologias em destaque são exibidas de acordo com os likes, em order decrescente. Somente os últimos 4 são exibidos.
* Não há tecnologia duplicadas entre as listagens de tecnologias em destaque e tecnologias recentes.
* A query de tecnologias em destaque é feita usando o `orderBy` `likes` (https://github.com/ufersa/plataforma-sabia/blob/master/packages/api/app/Middleware/HandleParam.js#L58)
* A query de tecnologias recentes é feita passando um filtro `notIn" para a rota de tecnologias. Esse filtro deve ser implementado.

## Implementation Brief

* Em https://github.com/ufersa/plataforma-sabia/blob/master/packages/api/app/Controllers/Http/TechnologyController.js#L50 adicionar um novo filtro `notIn` que receberá um array de ids (ids separado por vírgula). Esse filtro deve remover os ids passados da listagem.
* Em https://github.com/ufersa/plataforma-sabia/blob/master/packages/web/pages/index.js#L34 fazer uma outra consulta usando o `getTechnologies` services, mas dessa vez fazer o `orderBy: likes`. Uma vez com as tecnologias em destaque, gerar os ids e passar para o `notIn` da consulta de tecnologias recentes.

**Comment by alexandreadames** [comment]
Pessoal uma dúvida, as soluções em destaque devem vir antes ou depois das soluções recentes? @nicholasio, @marcusmota, @mateus4k, @lcnogueira.

**Comment by mateus4k** [comment]
Antes :slightly_smiling_face: 
![home](https://user-images.githubusercontent.com/30202634/87860267-7489be80-c912-11ea-9a0b-4415a71793fd.png)
