### ISSUE TITLE
Implementar Query Suggestions - Algolia

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#293]
## Feature Description

https://www.algolia.com/doc/guides/getting-insights-and-analytics/leveraging-analytics-data/query-suggestions/

A ideia aqui é basicamente usar o recurso Query Suggestions do Algolia e no lugar de fazer um "Autocomplete" a busca no `SearchForm` vai retornar sugestões (exemplo https://preview.algolia.com/delayed-hits-demo/?q=computer%20tablet&idx=instant_search&p=0)

---------------

## Acceptance criteria

* Ao buscar, os resultados retornados devem ser sugestões e não tecnologias em si.
* No lugar de exibir a imagem e descrição, alterar renderizar simplesmente a sugestão como no link acima.

## Implementation Brief

* Criar um novo component `SearchSuggestions` para usar no lugar do `Autocomplete`

**Comment by nichollasrennah** [comment]
@nicholasio lembre de preencher os criterios dessa issue.

**Comment by nichollasrennah** [comment]
Um exemplo que poderá ser feito da mesma forma: 
https://preview.algolia.com/delayed-hits-demo/?q=computer%20tablet&idx=instant_search&p=0

**Comment by nicholasio** [comment]
@nichollasrennah Atualizei, a ideia é essa desse link mesmo.
