### ISSUE TITLE
Área Perfil - Minhas Tecnologias Favoritas

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#295]
## Feature Description

Ver #294 e #274 .

Essa issue é para o usuário poder ver as tecnologias que ele "favoritou"/deu like. Precisamos criar uma listagem simples com o link para a tecnologia no site. Essa listagem existirá na área de perfil do usuário.

---------------

## Acceptance criteria

* Ao favoritar uma tecnologia, o usuário logado consegue ver ela na sua área de perfil. Em "Favoritos".
* O usuário pode remover uma tecnologia de sua lista de favoritos a partir da área de perfil, clicando em um link/botão "Remover dos favoritos".

## Implementation Brief

* Implementar uma tabela similar a tabela de "Minhas tecnologias"
* Implementar paginação.
* Implementar link/botão para remover a tecnologia dos favoritos.
* Implementar filtros "sort/sortBy" ao clicar na coluna da tecnologia. O filtro deve ser parte da rota, por exemplo: `user/my-account/bookmarks?sortBy=id&sort=ASC` e ao executar essas ações devemos o usar o `router.push` para que o Next.js chame o getInitialProps para pegar os dados. A ideia é não precisar lidar com o "state" dentro do component e deixar toda a responsabilidade de pegar os dados no getInitialProps.

**Comment by nicholasio** [comment]
IB ✅

**Comment by nicholasio** [comment]
@luizeboli passando essa aqui pra vc

**Comment by luizeboli** [comment]
@nicholasio o componente está funcional, mas os estilos do menu de paginação não agradaram muito, precisava de orientação quanto a isso.

![GIF-Bookmarks](https://user-images.githubusercontent.com/13091635/92025360-cefda380-ed35-11ea-8e4b-a7a765b4158f.gif)
