### ISSUE TITLE
Implementar User Dropdown

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#296]
## Feature Description

![image](https://user-images.githubusercontent.com/6104632/86589369-f74e6900-bf63-11ea-88d1-b01cbd4ea68a.png)

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by lcnogueira** [comment]
@nicholasio , só para confirmar aqui: no mouseover, eu mostra o Dropdown e no click eu levo ele pra área administrativa?

**Comment by nicholasio** [comment]
@lcnogueira quando fazer hover/click deve abrir o dropdown. Em mobile deve abrir o dropdown no clikc. O usuário vai para a parte administrativo ao clicar nas opções do dropdown.
