### ISSUE TITLE
Erro ao executar npm run seed:default

### ISSUE THREAD

**Issue by miguelslima** [ufersa/plataforma-sabia#304]
## Feature Description

Ajustes no Defuault da seed.

Só consegui rodar a seed sem o default.

## Acceptance criteria

Apresentou o seguinte erro:

```
C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api>npm run seed:default

> adonis-api-app@4.1.0 seed:default C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api
> node ace seed --files='0_RoleSeeder.js, 2_TaxonomySeeder.js, 3_TermSeeder.js, 5_PermissionSeeder.js'


TypeError: Cannot read property 'name' of undefined


1 anonymous
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\@adonisjs\ace\src\Command\index.js:527

2 anonymous
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\lodash\lodash.js:13806

3 arrayEach
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\lodash\lodash.js:516

4 Function.transform
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\lodash\lodash.js:13805

5 Function.commanderAction
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\@adonisjs\ace\src\Command\index.js:526

6 Command.listener
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\commander\index.js:315

7 Command.parseArgs
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\commander\index.js:651

8 Command.parse
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\commander\index.js:474

9 Kernel.invoke
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\@adonisjs\ace\src\Kernel\index.js:329

10 Ignitor._invokeAce
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\@adonisjs\ignitor\src\Ignitor\index.js:532

11 Ignitor.fireAce
  C:\Users\migue\Desktop\UFERSA\plataforma-sabia\packages\api\node_modules\@adonisjs\ignitor\src\Ignitor\index.js:847

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adonis-api-app@4.1.0 seed:default: `node ace seed --files='0_RoleSeeder.js, 2_TaxonomySeeder.js, 3_TermSeeder.js, 5_PermissionSeeder.js'`

```

**Comment by lcnogueira** [comment]
Oi, @miguelslima , obrigado por abrir a issue. 

É possível que tenha esquecido de fazer algo antes de rodar o `seed:default`? Eu droppei meu banco e refiz os passos aqui e não apresentou erro. 

Se possível, faz um teste seguindo os passos seguintes para a gente testar:
1) Na **raiz do projeto**, instala as dependências e executa o lerna para criar os links das dependências entre os demais packages:
```
npm install
npm run bootstrap
```

2) Entra no diretório da api (`cd packages/api`) e segue os passos que estão lá no README, até o passo 4 (os seguintes não são necessários pra o teste).

Se possível, faz isso e nos dá um feedback. Como disse, testei aqui e foi sem problemas, mas, de repente, tem alguma config local (uma variável de ambiente, por exemplo...) que inserimos durante o processo e esquecemos de atualizar na documentação. Isso pode nos ajudar a melhorar a documentação. Obrigado :handshake: :100:

**Comment by miguelslima** [comment]
Olá, @lcnogueira 

Fiz todo o passo a passo citado. Sem sucesso.

Fiz um novo clone do projeto em uma nova pasta e fiz tudo do início novamente para ter certeza que não esqueci de nenhuma etapa.

Mas tirando essa questão do `npm run seed:default` o restante da aplicação eu consigo executar sem problemas. Consigo rodar a API, consigo logar tanto na página WEB como na ADMIN.

**Comment by lcnogueira** [comment]
Estranho. Agora fiquei curioso.

Acabei de fazer um novo teste, mas dessa vez do zero. Clonei novamente o projeto em outro diretório e segui exatamente os passos descritos acima e consegui executar o `seed` default sem problemas.

Vocẽ conseguiu executar o seed que roda todos os arquivos? `npm run seed`

**Comment by lcnogueira** [comment]
Te mandei um arquivo aí no teu e-mail do hotmail, @miguelslima . Dá uma olhada lá, por favor :+1:

**Comment by lcnogueira** [comment]
FYI, estou fazendo alguns testes com o Miguel para tentar identificar o problema.

**Comment by lcnogueira** [comment]
Após vários testes com @miguelslima , identificamos o problema: os caracteres do script `seed:default` precisam ser escapados, pois nem todos os terminais aceitam. 

Miguel, se puder enviar o PR, seria legal. Se não, já agradeço pela contribuição e eu mesmo faço mais tarde. Só me dá um retorno, blz?

Vlw
