### ISSUE TITLE
Server Error quando não há tecnologias no banco.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#305]
## Feature Description

![image](https://user-images.githubusercontent.com/6104632/87360737-2145f380-c541-11ea-9801-6e5ae6bc563b.png)

---------------

## Acceptance criteria

* O front não deve da erro 500 quando não há tecnologias cadastradas (mesmo que seja um edge case)

## Implementation Brief

*

**Comment by mateus4k** [comment]
Bem observado. Vou consertar!
