### ISSUE TITLE
Atualização das tooltips cadastro de tecnologias

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#306]
## Feature Description

Atualizar o conteúdo das tooltips de ajuda dos campos do formulário de cadastro de tecnologias.

Os campos e a ajuda são as seguintes:

**ABA: SOBRE A TECNOLOGIA**

TÍTULO
O título é o nome pelo qual a sua tecnologia é identificada. Pode conter a sigla e o nome completo.

DESCRIÇÃO
Descreva de forma sucinta o que é a sua tecnologia.

PÚBLICO-ALVO
Qual o público a que se destina a sua tecnologia? pode incluir mais de um público-alvo

BIOMA PRINCIPAL
Informe o bioma principal de indicação da tecnologia

PROGRAMA DE GOVERNO
Se a sua tecnologia faz parte de algum incentivo de programa de governo, especifique qual o programa.

ESTÁGIO DE MATURIDADE
A maturidade da tecnologia será medida utilizando a escala TRL (Technology Readiness Levels) em 9 níveis. Defina qual estágio está sua tecnologia:

Nível 1 - Princípios básicos observados e relatados
Neste nível estamos falando de atividades de pesquisa científica, do tipo acadêmica. Possíveis aplicações da tecnologia ainda estão no estágio inicial, sem definições conceituais.

Nível 2 – Conceito e/ou aplicação da tecnologia formulados
São definidos os princípios básicos estudados no nível 1 e as aplicações conceituais são mencionadas de forma consistente, porém não necessariamente comprovada.

Nível 3 – Prova de conceito analítica e experimental de características e/ou funções críticas
Envolve a prova de conceito, através de modelagem, simulação e experimentação. Os estudos analíticos e laboratoriais são essenciais para a validação do conceito. Após estas atividades a tecnologia avança para o próximo nível.

Nível 4 – Verificação funcional de componente e/ou subsistema em ambiente laboratorial
A tecnologia ainda se encontra na fase de prova de conceito, sendo necessário neste nível a construção de um protótipo em estágio inicial para análise da funcionalidade de todos os componentes envolvidos, porém, ainda não representa o desempenho do sistema final por estar no ambiente laboratorial.

Nível 5 – Verificação da função crítica do componente e/ou subsistema em ambiente relevante
Ao demonstrar as funções do elemento estudado em ambiente relevante, mas ainda em escala piloto, atingiu-se o nível 5. Neste nível há uma definição preliminar dos requisitos de desempenho do elemento e o projeto preliminar, pois testes mais detalhados são realizados. Uma incerteza está relacionada à funcionalidade do elemento após o aumento de escala.

Nível 6 – Demonstração do modelo de protótipo de sistema/subsistema em ambiente relevante
A tecnologia encontra-se no nível 6 quando o desempenho geral do modelo proposto está demonstrado. Neste estágio, a tecnologia está pronta para a realização dos testes finais, visando a aplicação final e comercialização.

Nível 7 – Demonstração do protótipo de sistema/subsistema em ambiente operacional
Neste nível são realizados ensaios com o protótipo, porém em ambiente operacional, utilizando os parâmetros reais, para análise da integração da tecnologia no sistema operacional. Neste estágio, há desenvolvimentos para a resolução de problemas de desempenho da tecnologia.

Nível 8 – Sistema real desenvolvido e aprovado
O elemento é integrado no sistema final e está pronto para operar.

Nível 9 – Sistema real desenvolvido e aprovado através de operações bem-sucedidas
É alcançado quando o elemento está integrado no sistema final e operando.

ATENÇÃO: Só serão publicadas na Plataforma Sabiá as tecnologias do nível 7 a 9, pois tratam-se de projetos que já estão nas etapas de disponibilidade mercadológica. Tecnologias em níveis inferiores de maturidade poderão ser cadastradas apenas para ter acesso ao banco de investidores e parceiros para o desenvolvimento do projeto. Quando atingir a maturidade 7 ou superior poderão ser publicadas.

TEM PATENTE?
A sua tecnologia tem depósito do registro de proteção intelectual junto ao INPI?

PROTEÇÃO INTELECTUAL DA TECNOLOGIA
A Propriedade Intelectual é o que garante direitos em níveis industriais sobre aquilo que foi criado por alguém.

CLASSIFICAÇÃO DA TECNOLOGIA
As tecnologias podem ser classificadas quanto à sua natureza, que podem ser:
Avanços Tecnológicos:  são tecnologias que envolvem um conjunto de instrumentos, métodos e técnicas que visam a resolução de problemas.
Tecnologia Social: são tecnologias que podem ser utilizadas como ferramenta para resolver desafios sociais. Não necessariamente precisa ser algo novo, mas que ajude a solucionar problemas da sociedade. 
Inovação Social: produzem resultados que são orientados por necessidades e de caráter inovador, solucionando problemas da sociedade a longo prazo. Preocupa-se em solucionar desafios de ordem social, não necessariamente buscando aumento de lucro ou de competitividade. Podem se utilizar de tecnologias sociais como meio para solução dos problemas.

DIMENSÃO DA TECNOLOGIA
Em quais áreas a tecnologia contribui para o desenvolvimento sustentável da região: Ambiental, social, econômica, cultural ou política.

CATEGORIA/SUBCATEGORIA
As categorias e subcategorias são áreas que associam a sua tecnologia com a região do semiárido.

**ABA: CARACTERIZAÇÃO**

OBJETIVO PRINCIPAL
Qual o principal objetivo que a tecnologia quer alcançar. Inserir um objetivo claro e direto.

OBJETIVOS SECUNDÁRIOS
São outros objetivos que serão atingidos com a tecnologia, mas que são opcionais. 
LOCAL DE APLICAÇÃO
Qual o ambiente de aplicação: solo, água, planta, equipamentos, pessoas ou meio digital.

FORMA DE APLICAÇÃO
Descreva de forma sucinta como ocorre a aplicação da sua tecnologia.

EXEMPLOS DE APLICAÇÃO
Uma tecnologia pode ser usada de várias formas. Indique exemplos que a sua tecnologia pode ser usada.

DURAÇÃO DO PROCESSO DE INSTALAÇÃO
Quanto tempo demora para a instalação da tecnologia? informe o tempo em dias

PROBLEMAS QUE A TECNOLOGIA SOLUCIONA
Se a sua tecnologia for utilizada, quais os problemas que ela soluciona a curto, médio e longo prazo?

PROBLEMAS QUE A TECNOLOGIA ACARRETA
Se a sua tecnologia for utilizada, quais os seus efeitos colaterais? Ou seja, que problemas ela acarreta? 

PRÉ-REQUISITOS PARA A IMPLANTAÇÃO
Antes de implantar a sua tecnologia, o que o usuário precisa fazer?

RISCOS ASSOCIADOS
Quais riscos estão associados ao uso da sua tecnologia? 

CONTRIBUIÇÃO DA TECNOLOGIA
O que a sua tecnologia contribui para solucionar os problemas do semiárido?

**ABA: CUSTOS E FINANCIAMENTO**

CUSTOS DE DESENVOLVIMENTO
São custos relativos ao desenvolvimento da plataforma. Destinado a tecnologias que ainda não estão finalizadas. Os custos de desenvolvimento envolvem toda a necessidade de material, serviços e equipamentos durante a fase de construção. Esse tipo de informação é útil para os investidores conhecer os custos relativos à tecnologia.

CUSTOS DE IMPLANTAÇÃO
Para tecnologias já em fase de comercialização, informe quais os custos da implantação. Se a tecnologia não estiver nenhum custo relacionado com a implantação, informar o valor aproximado da tecnologia em si.

CUSTOS DE MANUTENÇÃO
Qual o custo médio da manutenção anual da tecnologia? Informar detalhadamente o que precisa ser feito para manutenções preventivas da tecnologia no período de 1 ano.

OBSERVAÇÃO
Descreva detalhes dos custos da sua tecnologia que precisa de alguma explicação mais detalhada.

NECESSITA DE FINANCIAMENTO?
Informe se você deseja de recursos financeiros para desenvolver sua tecnologia ou colocá-la em produção em escala. Esses dados não estarão disponibilizados na área pública da plataforma. Apenas os parceiros financiadores terão acesso a esses dados para oferecer a melhor opção para os desenvolvedores. 

TIPO DE FINANCIAMENTO
Você deseja um financiamento de bancos e investidores (privados), editais de fomento à pesquisa (público) ou financiamento coletivo (crowdfunding)?

VALOR DO FINANCIAMENTO
Informe o quanto deseja arrecadar via financiamento para o desenvolvimento da sua tecnologia.

SITUAÇÃO DO FINANCIAMENTO
Caso já tenha algum tipo de financiamento em andamento, informe aqui o status.

**ABA: MAPAS E ANEXOS**

ONDE A TECNOLOGIA É DESENVOLVIDA
Informe a instituição onde a tecnologia é desenvolvida. Caso não encontre na lista, deixe em branco. 

ONDE A TECNOLOGIA PODE SER UTILIZADA
Qual a região de abrangência que sua tecnologia pode ser usada? A princípio, apenas a região do semiárido está disponível.

ONDE A TECNOLOGIA JÁ FOI IMPLANTADA
Quais as cidades que a sua tecnologia já está sendo usada.

ANEXO DE FOTOS E VÍDEOS:
Coloque fotos da sua tecnologia. Procure iluminar bem a imagem. Se possível, contrate um profissional de fotografia para registrar as imagens de sua tecnologia. Lembre que aqui é uma vitrine.

ANEXO DE DOCUMENTOS
Nesse espaço você poderá adicionar todo o material documental da sua tecnologia: manuais, folhetos, tutoriais, cartilhas etc.

**ABA: RESPONSÁVEIS**

Adicione o nome dos responsáveis pelas tecnologias. O ID Lattes é importante para que a equipe de avaliadores possa analisar os dados dos pesquisadores com mais detalhes.

**ABA: RESUMO**

COMENTÁRIOS:
Informe aqui tudo o que você não encontrou neste formulário e acha importante comunicar aos avaliadores. Campos com opções não encontradas, instituições não cadastradas ou dados que são importantes e não encontrou local para cadastrá-lo. Esse campo é apenas para informar, não será publicado.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nicholasio** [comment]
@nichollasrennah você ainda vai definir os tooltips?

**Comment by nichollasrennah** [comment]
Sim. Irei definir o conteúdo ainda.
