### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#308]
## Feature Description

Criar endpoints na API para lidar com uploads.

Todos os uploads serão realizados de forma independente, através de um endpoint especifico de upload. Para associar uploads a outras entidades, será utilizado o id do upload.

---------------

## Acceptance criteria

* É possivel fazer upload de um ou vários arquivos ao mesmo tempo com a rota `POST /uploads`
* Não é possível fazer upload de arquivos não suportados (ver tabela mime-type).

## Implementation Brief

* Criar uma nova tabela no banco para armazena os uploads

**Tabela uploads**

column| type| description 
-- | -- | -- 
id| integer, autoincrement, pk | 
filename | varchar(255) | nome do arquivo armazenado no servidor.
user_id | id | id do usuário que fez o upload, é preenchido automaticamente baseado no usuário que fez o upload.
object | varchar(255), optional | nome da entidade (tabela)  a qual esse upload está relacionado.
object_id | integer, optional | id do objeto a qual esse upload está relacionado. (não e chave estrangeira)

Não haverá um relacionado propriamente dito, por chaves estrangeiras (a não ser em casos especificos). `object` e `object_id` será utilizado para relacionar o upload de forma virtual.

* Atualizar o campo `thumbnail` em `technologies` para ser uma chave estrangeira (thumbnail_id - `hasOne`).
  - No caso da thumbnail de tecnologia, o upload ainda será feito de forma separada no front, mas a thumbnail será associada diretamente com a tecnologia por uma chave estrangeira.
* Criar os seguintes endpoints:

método | rota | query/body params | auth
-- | -- | -- | --
GET | /uploads | object, object_id (ambos opcionais, serve para filtrar) | yes - usuários não admins só podem listar os uploads feitos por eles próprios.
POST | /uploads | file, meta *Post body| Yes - qualquer usuário logado. No entanto as permissões devem ser checadas para `object` e `object_id`, por exemplo, um usuário só pode fazer upload para a tecnologia com id 3 se ele tem permissão de update para aquela tecnologia.
DELETE | /uploads/:id | NA| Yes - permissão depende de `object` e `object_id`,

*essa rota não receberá um json, o content-type dela será `multipart/form-data`
**para enviar  os metadados com json, será necessário serializar o json, por exemplo

```html
<form method="POST" action="/uploads" enctype="multipart/form-data">
  <input type="file" name="files[]" multiple />
  <input type="hidden" name="meta" value='"{\n \"object\": \"technologies\",\n \"object_id\": 3\n}"'
  <button type="submit"> Submit </button>
</form>
```
O form acima exemplifica como os dados serao submetidos, no nosso caso iremos submeter via `fetch` no front.

* A rota `POST /uploads` e a rota `GET /uploads`retorna JSON com os dados do uploads, a resposta deve serguir o seguinte formato
```json
[
 {
   "id": 1,
   "filename": "filename.png",
   "url": "public/url/to/filename.png",
    "object": "technologies",
    "object_id": 3,
    "user_id": 2
 },
 {
   "id": 2,
   "filename": "filename2.png",
   "url": "public/url/to/filename2.png",
    "object": "technologies",
    "object_id": 4,
    "user_id": 5
 }
]
```
* Somente os seguintes arquivos serão suportados
  - a validação deve ser feita por mime-type e extensão.

extensions| mime-type| description 
-- | -- | -- 
.jpg, .jpeg, .jfif, .pjpeg, .pjp | image/jpeg 
.png | image/png
.webp| image/web

* Os arquivos devem ser armazenados em `resources/uploads`
  - se o upload não tiver um `object` ele deve ser armazenado na raíz
  - se o upload tiver um `object` ele deve ser armazenado no seguinte padrao `resources/uploads/{object}/filename`

**Exemplo de como testar o envio de uploads pelo `insomnia`**
![image](https://user-images.githubusercontent.com/6104632/87881534-4074d300-c9d0-11ea-9329-b6054c32883c.png)

**Comment by alexandreadames** [comment]
@nicholasio uma dúvida eu vi aqui que tem um campo `"url": "public/url/to/filename.png",`, e vi que os arquivos serão armazenados em `resources/uploads/{object}/filename`, foi apenas um exemplo ou teria que fazer algum tipo de mapeamento? O campo url seria virtual né, tipo ele é montado baseado no padrão.
