### ISSUE TITLE
Adicionar suportes para metadados a termos de taxonomia.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#315]
## Feature Description

Essa issue é para adicionar suporte ao conceito de metadados aos termos de uma tecnologia. Deve ser possivel associar metatados arbitrários a qualquer termo de qualquer tecnologia.

Cada metadado será um registro em uma tabela nova, que estara associada diretamente com um termo.

Cada metadado terá os seguintes campos:
- id
- term_id
- meta_key
- meta_value

---------------

## Acceptance criteria

* É possivel criar metadados ao criar ou atualizar um termo.
* É possivel enviar uma payload contendo somente metadados sem alterar nada do termo em si.
* O array "meta" da payload deve ser sincronizado com os metadados existentes baseado nos meta ids.

## Implementation Brief

Atualizar as seguintes rotas:

método | rota | query/body params | auth
-- | -- | -- | --
POST | /terms | *Post Body | Yes - mesma para criação de termos.
PUT | /terms/:id | *Post Body | Yes - mesma para atualização de termos. 
PUT | /terms/:id/meta | meta_key, meta_value | Yes - mesma para atualização de termos. Se meta_key não existir cria, se meta_key existir atualiza o meta_value. 

```json
{
  "term": "term_name",
  "slug": "term_slug",
  "taxonomy_id": "taxonomia_id",
  "meta": [
    {
     "id": 1, // se esse campo não existir, esse metadado deve ser adicionado.
     "meta_key":  "meta key 1",
     "meta_value": "value",
    }
  ]
}
```

**Comment by nicholasio** [comment]
@alexandreadames da uma revisada aqui

**Comment by alexandreadames** [comment]
@nicholasio só uma dúvida, a rota PUT deve ter o mesmo comportamento do PUT de costs? Se tiver o id atualiza, se não tiver cria, se o id não estiver presente exclui?

**Comment by nicholasio** [comment]
@alexandreadames isso!

**Comment by nicholasio** [comment]
@alexandreadames talvez seja interessante ter rota específica para alterar ou criar um metadado em especifico. Porquê da forma como está agora estamos assumindo que o front sempre irá enviar todos os metadados do termo.

Vou atualizar o IB.
