### ISSUE TITLE
Enviar email de confirmação de conta antes de validar a conta do usuário.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#34]
### Resumo da implementação
Ao criar um usuário pela API, este usuário deverá estar como pendente até que ele confirme seu email. Ou seja, até que ele clique num link enviado para o email dele contendo um token único.

- A rota `auth/register` deverá enviar um email de confirmação para o email cadastrado. Essa rota aceitará ainda o seguinte parâmetro além dos que ela já recebe:
  - scope - **string** 'admin' ou 'web' basicamente altera a URL para o qual o link contendo o token para ativar a conta pertence.
- Quando um usuário é criado pela rota `auth/register`, esse usuário é criado como 'pendente' no banco, portanto precisamos de um novo campo `status` na tabela usuário. Os valores possíveis serão `pending` e `verified`.
- A rota `auth/login` somente deverá autenticar o usuário caso ele tenha o status `verified`. Caso ele tenha uma conta mas o status seja `pending` vamos retornar código 400 com um `error_code` específico que indique que o usuário ainda não foi validado.

- Uma nova rota deverá ser criada `auth/confirm-account` que recebe o token que foi enviado para o usuário e altera o status do usuário para "verificado"
- Uma nova rota deverá ser criada `auth/resend-confirmation-email` que recebe o email do usuário e **somente irá reenviar o email de confirmação caso o usuário ainda esteja pendente**

Note que  front end precisará  implementar a lógica que receberá o token do link enviado para o usuário e fará  a requisição para `auth/confirm-account` com o objetivo de confirmar a conta do usuário.

O token deverá ser criado utilizando o Model Token.js para mais detalhes e ajuda na implementação, ver #46 .

Essa tarefa engloba as alterações na API, e no site.

### Critérios de aceitação

- Um usuário não poderá logar na aplicação até que ele confirme seu email.
- A rota `auth/register` deverá enviar um link contendo um token único para o email do usuário que ao ser clicado irá confirmar o email do usuário.
- A rota `auth/confirm-account` deverá validar a conta do usuário se recebebr um token válido. Se o token for invalido ou tiver expirado, retornar mensagem de erro.

**Comment by nicholasio** [comment]
Se o usuário tentar logar antes de confirmar o email, o sistema deve informar que o usuário ainda não confirmou o e-mail.

**Comment by nicholasio** [comment]
@exlleysantos Designei essa issue pra você. Qualquer dúvida pode perguntar. Você pode se basear em como em #46

**Comment by nicholasio** [comment]
@exlleysantos Inicialmente faça a implementação somente da API, depois atualizamos juntos o front.

**Comment by exlleysantos** [comment]
"Quando um usuário é criado pela rota auth/register, esse usuário é criado como 'pendente' no banco, portanto precisamos de um novo campo `status `na tabela usuário. Os valores possíveis serão `pending `e `verified`."

Pra evitar usar as strings, seria interessante eu criar um campo `is_active `e setar ele como `true ` ou `false`?

**Comment by nicholasio** [comment]
@exlleysantos a vantagem do status é porquê se tivermos outro status no futuro, não precisamos de um novo campo. Além disso esse campo poderia ser criado como uma `enum` no mysql limitando os possíveis valores.

Mas também acho a ideia de um campo booleano também, nesse caso acho `is_verified` um nome melhor.

O que acham @lcnogueira @alexandreadames .

@nichollasrennah Você consegue imaginar algum outro titpo de status que um usuário possa ter? Depois de ter validado seu email? Por exemplo, um dono de uma tecnologia talvez tendo seu perfil manualmente verificado pelos curadores?

**Comment by alexandreadames** [comment]
Um novo campo com status é melhor, pois é mais escalável. Como @nicholasio mencionou pode exisitr algum outro fluxo que introduza algum outro tipo de status. Mas acho interessante colocar booleanos tipo `active` e `is_verified`.

**Comment by lcnogueira** [comment]
Como é algo que não gera complexidade na implementação, acho melhor usar logo o `status` mesmo. Daí, pode criar já uns métodos dentro do model de `User`, tipo, `isVerified` e `isPending`, pra ser utilizado nos controllers. Se algum dia tivermos outra situação, só adicionar na lista e criar um outro método. Se por outro lado mudarmos a estratégia, é só alterar a implementação desses métodos `isVerified` e `isPendind` sem mexer lá no controller.

**Comment by nicholasio** [comment]
@exlleysantos então vamos proceder com o campo `status` mesmo.

**Comment by exlleysantos** [comment]
@nicholasio,  @lcnogueira e @alexandreadames, fiz o commit de umas alterações iniciais da issue, vocês podem verificar se tô indo no caminho certo?

o que fiz foi:

1. Métodos `confirmAccount( )` e o envio de emails de confirmação no `register()`;
2. Método `generateConfirmationAccountToken( )` no Model de User;
3. Adicionei o campo `status` na migration User.

**Comment by alexandreadames** [comment]
Exlley eu fiz uns comentários lá no seu commit.

**Comment by nicholasio** [comment]
@exlleysantos Você pode criar uma `draft` Pull Request quando precisar de uma revisão inicial, fica melhor de revisar :)

**Comment by exlleysantos** [comment]
@nicholasio tô querendo saber se tô indo no caminho certo, minha implementação não tá completa. Já preciso preencher todos os campos na `draft pull request`?

**Comment by nicholasio** [comment]
@exlleysantos não, enquanto ela for draft a descrição pode estar incompleta

**Comment by exlleysantos** [comment]
Uma nova rota deverá ser criada `auth/resend-confirmation-email` que recebe o email do usuário e **somente irá reenviar o email de confirmação caso o usuário ainda esteja pendente**

Neste caso, ao reenviar o e-mail, é interessante revogar o `token `existente e enviar um novo, ou pode enviar o mesmo `token`?

**Comment by nicholasio** [comment]
@exlleysantos melhor revogar e enviar um novo!

**Comment by nicholasio** [comment]
@NaylsonFerreira repassando essa pra você depois que vc finalizar as suas atuais!
