### ISSUE TITLE
Notificação de sucesso no cadastro de usuário

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#343]
Ao realizar o cadastro de um novo usuário o sistema não informa que será necessário verificar o email e validar a conta criada.

A mensagem é de apenas "Conta cadastrada com sucesso" dentro do formulário em um espaço onde o usuário não percebe a mensagem, pois é apresentada entre os campos.

É preciso melhorar a forma de notificação aos usuários... uma notificação mais visível como um modal, por exemplo, com um botão OK para haver a interação do usuário. 

No email que confirma a ativação do cadastro o título do e-mail está em Inglês. Colocar em Português.

**Comment by nicholasio** [comment]
Podemos usar os tooltips que o @mateus4k introduziu.
