### ISSUE TITLE
Formatação do Campo Estágio de maturidade tecnológica

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#345]
1) Campo Estágio de maturidade colocar a lista em ordem alfabérica 

2) Nesse campo, ao escolher a opção de 1 a 6, apresentar a seguinte mensagem de advertência via modeal com um botão OK:
**ATENÇÃO: Só serão publicadas na Plataforma Sabiá as tecnologias do nível 7 a 9, pois tratam-se de projetos que já estão nas etapas de disponibilidade mercadológica.  Tecnologias em níveis inferiores de maturidade poderão ser cadastradas apenas para ter acesso ao banco de investidores e parceiros para o desenvolvimento do projeto.  Quando atingir a maturidade 7 ou superior serão analisadas pela curadoria para serem publicadas.**

**Comment by lcnogueira** [comment]
Não valeria a pena usar os tooltips também aqui @mateus4k, assim como sugerido em outra PR?
