### ISSUE TITLE
Processo de Mensagens

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#364]
## Feature Description

- A Plataforma Sabiá fará a comunicação dos seus usuários por meio de mensagens assíncronas. 
- Essas mensagens serão entregues por meio dos emails dos usuários.
- Será possível verificar a lista de mensagens trocadas no sistema na área do usuário.
- Essas mensagens são disparadas de acordo com as ações realizadas dentro da plataforma.
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nicholasio** [comment]
@nichollasrennah no caso isso aqui são basicamente os emaisl transacionais correto? Não seria o chat. No caso você quer que todas as mensagens sejam enviadas via email mas que seja possível verificar todas as mensagens enviadas em um `inbox` correto?

**Comment by nichollasrennah** [comment]
Vejo que podemos deixar essa funcionalidade como um chat mesmo.

**Comment by luizeboli** [comment]
@nichollasrennah  podemos fechar essa issue? Já temos mensagens tanto entre usuários quando plataforma > usuários.
