### ISSUE TITLE
Formulário de aquisição de tecnologia

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#365]
## Feature Description

- Quando o usuário quiser adquirir uma tecnologia, clicando no botão "QUERO ADQUIRIR ESSA TECNOLOGIA" na tela de detalhes da tecnologia irá aparecer uma nova tela com os seguintes campos em formato de formulário: 

![Quero adquirir essa tecnologia](https://user-images.githubusercontent.com/48101231/95073427-3b781380-06e3-11eb-889e-b0f46eb0b8ec.png)

- Os campos que irão ser necessários preencher pelo usuário:
   + Deseja adquirir quantas unidades dessa tecnologia? (campo inteiro)
   + A tecnologia será adquirida para uso: (Particular, Empresa, Governo Municipal, Governo Estadual, Governo Federal, Outro)
   + Deseja financiamento para essa aquisição? 
        * Sim, eu já tenho como financiar
        * Sim, mas não tenho como financiar ainda
        * Não desejo financiamento
   + Observação 

![form-aquisição](https://user-images.githubusercontent.com/48101231/95073451-43d04e80-06e3-11eb-97f1-86029bc35dc0.png)

---------------

## Acceptance criteria
- Somente usuários logados e com o cadastro de dados pessoais completos poderão adquirir a tecnologia
- O sistema precisa checar se o usuário completou os dados pessoais de cadastro, caso contrário, precisa desviar o fluxo para esse preenchimento.
- Uma notificação é feita ao pesquisador dono da tecnologia
- Uma negociação é registrada na área do usuário

* 

### Criação de novo esquema: `technology_orders`, com os campos:
| Campo          | Descrição | Tipo|
|-------------------|---------------|-------|
|user_id           |Usuário que adquiriu a tecnologia|Inteiro|
|technology_id |Tecnologia a ser adquirida  |Inteiro|
|quantity | Quantidade de unidades da tecnologia |Inteiro|
|use| Uso da tecnologia|Enum:['private','enterprise','local_government','provincial_government','federal_government','other']
|funding | Financiamento para aquisição|Enum:['has_funding','wants_funding', 'no_need_funding']
|comment| Comentário| String(Text)

### Rotas

| Método | Rota |Body | Auth|
|------------|--------|-------|-------|
|POST     |technologies/:id/orders|quantity (obrigatório), use(obrigatório),  funding(obrigatório), comment|Qualquer usuário logado com dados preenchidos|
|GET      |technologies/:id/orders|N/A|Permission: LIST_TECHNOLOGY_ORDERS or LIST_TECHNOLOGIES_ORDERS

### Detalhes técnicos

1. Criar novo middleware para checar se usuário tem todos os dados preenchidos. Ele pode ser utilizado para checar em determinadas rotas se é um requisito obrigatório para prosseguir com o fluxo.
2. No endpoint `POST technologies/:id/orders` enviar um email para o pesquisador dono da tecnologia após o pedido de compra.

**Comment by nicholasio** [comment]
@nichollasrennah adicionando a tag "needs-design", você pretende fazer o design ou vai aguardar o novo bolsista?

**Comment by nichollasrennah** [comment]
Preciso conversar com algum pesquisador para saber quais dados eles vão querer obter nessa etapa.

**Comment by nichollasrennah** [comment]
Pronto @JoaoPauloSMoura agora pegue essa issue aqui, que são juntas com as issues #436 e #437

**Comment by JoaoPauloSMoura** [comment]
Pode deixar

**Comment by JoaoPauloSMoura** [comment]
@nichollasrennah validou essa issue no figma?

**Comment by nichollasrennah** [comment]
Sim. Aprovada.

**Comment by JoaoPauloSMoura** [comment]
show, irei partir para as próximas!

**Comment by luizeboli** [comment]
Só um detalhe sobre o ponto:

`Criar novo middleware para checar se usuário tem todos os dados preenchidos. Ele pode ser utilizado para checar em determinadas rotas se é um requisito obrigatório para prosseguir com o fluxo.`

Precisei fazer a mesma coisa no model User por uma necessidade do processo de curadoria, os campos obrigatórios são esses:

```
/**
 * Required fields for checking if registration is completed
 */
const required_fields = [
	'full_name',
	'email',
	'company',
	'cpf',
	'birth_date',
	'phone_number',
	'lattes_id',
	'zipcode',
	'address',
	'district',
	'city',
	'state',
	'country',
];
```

**Comment by nichollasrennah** [comment]
Vou deixar isso aqui para @mateus4k
