### ISSUE TITLE
Refatorar TechnologyForm: mover `step` para ser parte da rota.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#369]
## Feature Description

Está ficando um pouco complicado de persistir o state do technology form (technology/new) agora que precisamos de vários endpoints distintos em telas diferentes. No momento precisamos "atualizar o state" tanto no getInitialProps como no `onSubmit`. A minha ideia é que o `step` faça parte da rota e que o "Salvar e Continuar", dê um `router.push` para direcionar para a próxima rota, de tal forma que o `getInitialProps` seja executado novamente.

Outra vantagem é que o `step` seria passado para o `getInitialProps` e com isso podemos decidir exatamente quais dados precisamos carregar baseado na tela do formulário.

---------------

## Acceptance criteria

* A navegação entre steps altera a rota.

## Implementation Brief

* A navegação entre o steps do FormWizard precisa ser alterado para que ele altere a rota (passando o próximo ?step) fazendo isso iremos chamar o getInitialProps que irá atualizar todas as props. Logo não precisamos da lógica de atualizar o state do formulário no `handleSubmit`.
* Dentro do getInitialProps, somente solicitar os dados necessários para o `step` em questão do formulário.

**Comment by nicholasio** [comment]
@davioliveiira Acho que essa aqui poderia ser uma boa issue inicial, não é tão trivial mas vai ajudar você a entender uma parte crucial da aplicação.

**Comment by davioliveiira** [comment]
@nicholasio acho que podemos também fazer uma validação nas rotas, por exemplo: Caso o usuário tente acessar uma rota do step diretamente e que necessite de alguns dados do passo anterior, podemos informar e redirecionar.

Exemplo:
O Usuário passa diretamente a rota `/step/2` e nesse caso ele deveria ter passado pelo `/step/1`...

**Comment by nicholasio** [comment]
@davioliveiira Faz sentido, só teria que ver como detectar isso. Creio que a única forma é verificar manualmente os campos `required` e ver se todos estão preenchidos.

Por exemplo, pra validar o step 2 verificar se todos os campos required existem no objeto de tecnologia retornado pela API.

**Comment by davioliveiira** [comment]
@nicholasio isso mesmo!
