### ISSUE TITLE
Auditar Designs/Front-End

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#374]
- Auditar o Design no Figma
- Auditar a implementação do Front.

Imagino que como resultado dessa auditoria teremos os seguintes resultados/consequências:

- Alterações no design para corrigir inconsistência
- Alterações no design para melhorar a UX
- Correções na implementação do Front-End

cc @nichollasrennah

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura Quanto tempo você precisa para completar essa issue?

**Comment by JoaoPauloSMoura** [comment]
@nichollasrennah eu acredito que entre o levantamento dos dados e documentação vai de  8 a 10h

**Comment by nicholasio** [comment]
@JoaoPauloSMoura Você pode postar o resultado da auditoria aqui? Você comentou que fez um style guide, tá no figma?

**Comment by JoaoPauloSMoura** [comment]
https://www.notion.so/joaopaulomoura/An-lise-geral-do-projeto-de-UI-f4d1ad803d3043d58253d95259ec5266
@nicholasio esse é o documento geral que estou anotando as modificações, porém com o passar do tempo vi que estava entrando em detalhes que precisaremos refazer algumas coisas, e como o objetivo é buscar alguma melhoria no geral pra que a gente consiga agilizar e fazer certo nas próximas etapas, foquei nas mehorias do estilos como um todo, padrão de fontes, cores, e componentes, a medida que eu for fazendo as issues vou fazendo uma página no Figma só com Ui componets já refatorados, fazer uma espécie de Design system.

Abaixo está o começo do nosso Style guide que eu citei, com o passar do tempo a ideia é ir aumentando o tamanho dele para que fique cada vez mais detalhado. Inclusive gostaria da logo em formato de vetor @nichollasrennah se vc tiver aí, porque aí crio uma seção só com a marca e todas as versões dela.
![Style Guide (1)](https://user-images.githubusercontent.com/46350848/92997961-707eb500-f4ed-11ea-8bb3-a538a83040d6.png)

**Comment by nichollasrennah** [comment]
Podemos considerar essa issue concluída, @JoaoPauloSMoura ?

**Comment by JoaoPauloSMoura** [comment]
Sim sim
