### ISSUE TITLE
Criar pacote `core`

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#375]
## Feature Description

Nós temos uma estrutura monorepo mas não estamos de fato usando a estrutura monorepo. Chegou a hora de começamos a quebrar nossa aplicação em pacotes menores para facilitar o reúso de código, principalmente agora que começaremos a trabalhar no aplicativo mobile.

Algumas coisas que podemos colocar nesse pacote `core`:

- Toda lógica de autenticação, os services, UserProvider, `useAuth` etc.
- Todos os services

A ideia do pacote `core` é que tenhamos código que possa ser reutilizado entre o app e o front-end web.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by luizeboli** [comment]
Por fim criou-se o pacote `app` em outro repositório. Caso algum dia voltemos a discutir sobre usar monorepo, abriremos uma nova issue.
