### ISSUE TITLE
Criar role "reviewer" (curador)

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#377]
## Feature Description

O curador terá algumas permissões especiais, tais como:

- Aprovar tecnologia
- Rejeitar tecnologia.

Ele só poderá fazer isso para as tecnologias associadas a ele.

Também precisaremos criar uma nova tabela de curadores pois eles tem informações específicas.

---------------

## Acceptance criteria

* É possivel criar um curador e associar diversas categorias pra ele.
* Somente o curador tem poder de aprovar ou rejeitar uma tecnologia.
* Aprovar e rejeitar uma tecnologia deve alterar seu status para públic.

## Implementation Brief

* Criar tabela `reviewers`
   - id, user_id (referência tabela usuário), status ('pending', 'approved')
   - Somente reviewers com status `approved` é que de fato foram aprovados para serem curadores. reviewers com status `pending` foram aqueles usuários que solicitaram para ser curadores mas não foram aprovados ainda.
* Criar tabela `reviewers_categories`
   - Contém o relacionamento entre reviewers e categories, ou seja, todas as categorias que o curador poderá revisar.
* Definir role `REVIEWER` em `api/app/Utils/roles_capabilities`
* Definir uma nova permissão UPDATE_TECHNOLOGY_STATUS em  `api/app/Utils/roles_capabilities`
* Atualizar as rotas de technologia para que o `status` não possa ser alterado.
* Criar nova rota `PUT /technologies/:id/update_status` cujo novos valores podem ser `pending`, `rejected` e `published`

**Comment by alexandreadames** [comment]
@nicholasio, dúvidas:

1. A associação direta do curador a tecnologia se dará através da tabela `technology_user` né? com o papel reviewer? Nesse caso no front vai usar a rota que já está definida em: `technologies/:id/users`;
2. Na tabela `reviewers_categories` o category será um `term_id` que ser refere a uma categoria na tabela de termos? 
3. O novo role `REVIEWER` terá apenas uma permissão? `UPDATE_TECHNOLOGY_STATUS` ou além dessa, herdará as permissões de um usuário comum?

**Comment by nichollasrennah** [comment]
Essa issue já pode ser fechada?
