### ISSUE TITLE
Rotas que retornam tecnologia só devem retornar tecnologias publicadas

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#378]
## Feature Description

Atualmente todas as tecnologia são retornadas no endpoint de tecnologia. Como resultado da issue #377 precisamos retornar somente tecnologias publicadas. Também precisamos atualizar a lógica que indexa tecnologias para o algolia para somente indexar tecnologiaspublicadas.

---------------

## Acceptance criteria

* Somente tecnologias publicadas devem ser públicas e retornadas no endpoint `GET /technologies`

## Implementation Brief

* Adiciar um `where({status: 'published'})` em `api/app/Controllers/TechnologyControllers.js:index`
* Somente admins, o curador (caso tenha um associado) e os responsáveis pela tecnologia podem acessar uma tecnologia que não é pública. Por tanto devemos atualizar os métodos do Controller Tecnologia para seguir essa regra.
* Sugiro criar um novo método no model Technology para abstrair a lógica de checagem se o usuário que esta fazendo a requisição tem permissaão para acessar aquela tecnologia.
* Atualizar o método `indextoAlgolia` para que ele só manda a tecnologia para o algolia se ela for `published`.
* Atualziar o comando que indexa as tecnologias para somente indexar as tecnologias `published`.

**Comment by nichollasrennah** [comment]
@alexandreadames essa issue passou a ser importante para o teste completo do processo de curadoria.

**Comment by nichollasrennah** [comment]
@alexandreadames já que você já enviou a PR da outra issue, veja se consegue resolver essa aqui pra essa semana.
