### ISSUE TITLE
Rota para solicitar papel de curador (reviewer) 

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#379]
## Feature Description

Ver #377 

Qualquer usuário pode solicitar se tornar um curador. Precisamos criar um novo endpoint que os usuários possam solicitar trabalhar como curadores.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
Essa issue já pode ser fechada?
