### ISSUE TITLE
Implementar busca da página principal

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#38]
### Implementation Brief
Deve-se criar um componente `Search` que irá englobar a funcionalidade de busca do nosso site. Esse componente utilizará a biblioteca [react-instant-search](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react/) (partindo da implementação já existente feita por @nicholasio) para realizar a busca no nosso índice do algolia e exibirá os resultados na página principal, mais especificamente no campo de busca existente.

Deve-se atentar para os seguintes detalhes da implementação:
- O campo de busca, o formulário, o input e o botão deverão ser os da própria lib `react-instant-search`, mais espeficamente através do componente `SearchBox` da biblioteca;
- À medida que o usuário digitar um termo de busca, os resultados devem ser exibidos em uma espécie de painel suspenso, com os termos encontrados sendo destacados. Como exemplo, ver a [busca na página principal da documentação do React](https://reactjs.org/docs/getting-started.html).
     - Ver https://www.algolia.com/doc/api-reference/widgets/autocomplete/react/
- Ao clicar em um termo encontrado (uma tecnologia), o usuário será levado para a página de detalhes daquela tecnologia. 
- Ao pressionar a tecla Enter ou clicar no botão de busca ao lado de botão de input, o usuário deve ser levado para a página de busca, já exibindo os resultados correspondentes.
_Obs.: a tela de busca será desenvolvida em outra issue. Só é necessário enviar a requisição com o termo correspondente para a tela de busca._ 

### Acceptance Criteria
- Ao deletar os termos do campo de busca, o painel suspenso deve desaparecer.
- O campo de busca deve retornar uma mensagem de "_Nenhum resultado foi encontrado para o termo <termo_buscado>_" dentro do painel de resultados  caso o usuário digite um termo inexistente.

**Comment by nicholasio** [comment]
IB :white_check_mark:

**Comment by nicholasio** [comment]
@lcnogueira pode confirmar se podemos fechar essa issue?

**Comment by lcnogueira** [comment]
Sim, fechando agora. É que a PR não tava com uma daquelas palavras (resolves, closes, etc.), aí não fechou automaticamente :+1: .
