### ISSUE TITLE
Processo de submissão de tecnologia e escolha de curador.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#380]
## Feature Description

Ao iniciar o cadastro de uma tecnologia, o status dela deve ser `draft`, quando o cadastro é finalizado, no entanto, o status precisa ser alterado para `pending` e um curador ( `reviewer`) precisa ser associado a tecnologia.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
Essa issue já pode ser fechada?
