### ISSUE TITLE
Criar área do usuário para curadores

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#381]
## Feature Description

Os usuários que também sejam curadores precisam ter uma área adicional na parte de "Minha conta" para que eles possa revisar as tecnologias que foram associadas a ele.

Na área do usuário precisa ter um menu chamado ÁREA DO CURADOR, no qual terá duas opções:
- Avaliar tecnologias
- Tecnologias avaliadas
- Botão: Seja um curador

![Área do usuário - Área do curador](https://user-images.githubusercontent.com/48101231/94135840-67211100-fe3a-11ea-88ee-97521a8cef01.png)

Ao clicar para AVALIAR TECNOLOGIAS aparecerá uma lista com as tecnologias com o status: [IN_REVIEW, REQUESTED_CHANGES, CHANGES_MADE]
- É para apresentar para avaliação somente tecnologias que foram cadastradas com TRL de 7 a 9.

As colunas da lista são:
- Título
- Instituição
- Status
- Última atualização
- Ações: Visualizar (executar a Issue #382 )

![Lista de tecnologias para avaliar](https://user-images.githubusercontent.com/48101231/94135683-2fb26480-fe3a-11ea-81ea-aac7c5aa7e91.png)

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by luizeboli** [comment]
Irei aguardar o PR da API ser aprovada pra seguir com a finalização dessa issue e poder testar a funcionalidade adequadamente
