### ISSUE TITLE
QA - Formulário de Cadastro

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#384]
Essa issue é para testar o formulário de cadastro, executar todos os passos, reportar qualquer problema aqui e abrir novas issues para corrigir os problemas encontrados (e corrigir).

**Comment by luizeboli** [comment]
Tava dando uma olhada por acaso, e percebi que o formulário no caso de uma edição, não verifica se a tal tecnologia pertence ao usuário autenticado. Ele carrega os dados do 1o step e retorna 403 caso tente salvar (o esperado).

Não achei outra issue sobre o tema (_não claramente_)

**Comment by calaca** [comment]
@nicholasio seguem os pontos que encontrei para melhoria e conserto:

### Cadastro de tecnologia
- Select deveria seguir as mesma linha visual dos inputs para manter consistência:
![image](https://user-images.githubusercontent.com/10481028/92017277-e9ca1b00-ed29-11ea-86c6-cb57eefa888f.png)
(inconsistência atual)
![image](https://user-images.githubusercontent.com/10481028/92017155-bab3a980-ed29-11ea-80aa-e9e23e906249.png)
(visual desejado)
- Posicionamento dos tooltips não está correto:
![broken_tooltip](https://user-images.githubusercontent.com/10481028/92020752-087ee080-ed2f-11ea-9fc1-065340d22064.jpg)
- Tooltip não funciona no mobile. Aqui seria interessante trocar o comportamento para o tooltip aparecer com um click ao invés do hover (que não funciona no mobile) ou esconder o tooltip no mobile.
- Layout de passos do cadastro quebra em certo ponto:
![image](https://user-images.githubusercontent.com/10481028/92021178-c3a77980-ed2f-11ea-8502-65aec2905d38.png)
- Tooltip vazio:
![broken_tooltip(1)](https://user-images.githubusercontent.com/10481028/92022514-bee3c500-ed31-11ea-8590-5effa5091432.jpg)
- Tooltip com typo:
![broken_tooltip(2)](https://user-images.githubusercontent.com/10481028/92022531-c6a36980-ed31-11ea-83fe-8e17ec4585d1.jpg)
- Switch e botão de ajuda desalinhados:
![image](https://user-images.githubusercontent.com/10481028/92022776-28fc6a00-ed32-11ea-92ac-bd25a02c70b7.png)
- Título e botão de ajuda desalinhados verticalmente:
![image](https://user-images.githubusercontent.com/10481028/92022807-36b1ef80-ed32-11ea-8e80-0dda04d29675.png)
- Falta máscara para inputs de custo:
![image](https://user-images.githubusercontent.com/10481028/92022928-64973400-ed32-11ea-82ba-32a62110763d.png)
- Valores decimais são ignorados quando utilizados com vírgula (padrão brasileiro):
![image](https://user-images.githubusercontent.com/10481028/92023064-94ded280-ed32-11ea-9c13-bb6ab5666558.png)
- Indicador de carregamento no select assíncrono está sem internacionalização:
![no_int](https://user-images.githubusercontent.com/10481028/92023429-251d1780-ed33-11ea-9e2d-f6500795200b.jpg)
- Resultados de localização estão em inglês:
![image](https://user-images.githubusercontent.com/10481028/92023580-585fa680-ed33-11ea-9505-153136c840f3.png)
- Alguns dados cadastrados não aparecem no resumo: objetivos, aplicação, contribuição, riscos, financiamento, custos da tecnologia e documentos.
- Ainda sobre o problema acima, seria interessante dar feedback para o usuário quando uma informação não estiver presente. Outra opção seria esconder seu título.
![image](https://user-images.githubusercontent.com/10481028/92024416-914c4b00-ed34-11ea-80ea-3d3d740d1ed3.png)
(Sem feedback)
![image](https://user-images.githubusercontent.com/10481028/92024457-9c9f7680-ed34-11ea-8925-e845d37d8d68.png)
(Com feedback)
- Ícone de check desalinhado:
![image](https://user-images.githubusercontent.com/10481028/92024366-80033e80-ed34-11ea-9a4d-ee7c03bed18f.png)
- Ao finalizar cadastro, os seguintes dados não foram persistidos:
  3. Custos e financiamento: custos de manutenção
  5. Mapas e anexos: região e documentos (PDF)

### Edição de tecnologia
- Ao preencher novamente os dados faltantes na edição de tecnologia, os dados do resumo são apresentados como esperado, com exceção dos documentos (PDF) e custos de manutenção.

### Edição de financiamento
1. Marcar "sim" para a necessidade de um financiamento
2. Preencher os dados
3. Salvar a tecnologia
4. Editar a tecnologia salva
5. Marcar "não" para a necessidade de um financiamento
6. Resumo ainda mostra dados do financiamento preenchido anteriormente:
![image](https://user-images.githubusercontent.com/10481028/92025599-2ef44a00-ed36-11ea-8ee4-87b8f51476b7.png)

@nicholasio como devo proceder agora?

**Comment by calaca** [comment]
@nicholasio fechando essa issue pois a etapa de investigação foi finalizada e novas issues foram criadas para resolver os problemas identificados.
