### ISSUE TITLE
Refatorar ordenação

### ISSUE THREAD

**Issue by mateus4k** [ufersa/plataforma-sabia#386]
## Feature Description

Precisamos aprimorar a feature de ordenação de nossa API.

Atualmente, só conseguimos utilizar os `query params` para ordenação (`/technologies?orderBy=created_at&order=DESC`, por exemplo) caso o nome da tabela seja o primeiro item da url, como `technologies` no caso acima.

Precisamos que seja possível ordenar uma entidade independentemente de sua posição na URL para que rotas relacionadas a entidade principal, como `/technologies/1/reviews` sejam também ordenáveis.

## Acceptance criteria

* Rotas como `/technologies/1/reviews?orderBy=created_at&order=DESC` precisam funcionar como esperado;
* Os campos possíveis de serem ordenados precisam estar prescritos no model da entidade;
* Campos não permitidos para ordernação não devem ser ordernados;

## Implementation Brief

> Esta é apenas uma sugestão de implementação. Sinta-se livre para ser criativo :slightly_smiling_face:

* Criar uma `trait` contendo um `globalScope` que a princípio fará apenas um `orderBy(field, order)`;
* O valor padrão do `field` deve ser a `primaryKey` do model. Creio que acessando o model base do Adonis conseguirá saber exatamente o nome do atributo; O padrão do `order` deverá ser `ASC`;
* Dentro do `globalScope`, checar se o campo recebido por parâmetro está contido no array `sortables`, que deverá ser inserido em cada model contendo os campos que podem ser ordernados;
* Implementar o middleware `handleOrder`, onde receberá o parâmetro `orderBy` e `order` da request, e, caso exista o primeiro, aplicará o `globalScope` a partir da trait. Creio que seja possível aplicá-lo ao model base para que seja aplicado independetemente do model em questão na requisição;
* Checar como podemos atualizar as ordenações na documentação.

**Comment by nicholasio** [comment]
@NaylsonFerreira nova issue pra vc aqui

**Comment by nicholasio** [comment]
IB ✅
