### ISSUE TITLE
Implementar página de busca do site

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#39]
### Implementation Brief
Deve-se implementar uma página de busca do site. Essa página deve utilizar o componente de busca [react-instant-search](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react/) do algolia para realizar a busca. Os resultados já devem ser filtrados à medida que o usuário digita no campo de busca. Além disso, deve haver um filtro lateral para permitir que os usuários possam filtrar os resultados.

Deve-se atentar para os seguintes detalhes da implementação:
- A filtragem só deve começar a ocorrer a partir de 3 letras digitadas.
- A filtragem deve considerar o campo de busca **E** os critérios de filtro.

### Acceptance Criteria
- A lista de resultados deve ser exibida por completo caso nenhum termo de busca esteja no input.

**Comment by nicholasio** [comment]
**IB ✅**
