### ISSUE TITLE
Dados não aparecem após cadastro de nova tecnologia e não são salvos

### ISSUE THREAD

**Issue by calaca** [ufersa/plataforma-sabia#390]
### Cadastro de Tecnologia
- Alguns dados cadastrados não aparecem no resumo: objetivos, aplicação, contribuição, riscos, financiamento, custos da tecnologia e documentos.
- Ainda sobre o problema acima, seria interessante dar feedback para o usuário quando uma informação não estiver presente. Outra opção seria esconder seu título.
![image](https://user-images.githubusercontent.com/10481028/92024416-914c4b00-ed34-11ea-80ea-3d3d740d1ed3.png)
(Sem feedback)
![image](https://user-images.githubusercontent.com/10481028/92024457-9c9f7680-ed34-11ea-8925-e845d37d8d68.png)
(Com feedback)
- Ao finalizar cadastro, os seguintes dados não foram persistidos:
  3. Custos e financiamento: custos de manutenção
  5. Mapas e anexos: região e documentos (PDF)

### Edição de Tecnologia
- Ao preencher novamente os dados faltantes na edição de tecnologia, os dados do resumo são apresentados como esperado, com exceção dos documentos (PDF) e custos de manutenção.
- Verificar se a tecnologia editada pertence ao usuário autenticado.

#### Edição de financiamento
1. Marcar "sim" para a necessidade de um financiamento
2. Preencher os dados
3. Salvar a tecnologia
4. Editar a tecnologia salva
5. Marcar "não" para a necessidade de um financiamento
6. Resumo ainda mostra dados do financiamento preenchido anteriormente:
![image](https://user-images.githubusercontent.com/10481028/92025599-2ef44a00-ed36-11ea-8ee4-87b8f51476b7.png)

**Comment by nicholasio** [comment]
@calaca Vamos deixar essa em hold por equanto. Tenho pra mim que iremos resolver isso em #369

**Comment by calaca** [comment]
Fechando a issue pois não será trabalhada no momento e provavelmente será resolvida pela #369.
