### ISSUE TITLE
Alterar comportamento e texto de tooltips

### ISSUE THREAD

**Issue by calaca** [ufersa/plataforma-sabia#391]
## Feature Description

- [x] Ajustar toggle do texto de tooltip por meio de click para ser possível acesssar essas informações pelo mobile.

- [x] Colocar textos do tooltip num modal para facilitar a leitura.

- [x] Remover tooltips desnecessários.

---------------

## Acceptance criteria

- Os textos dos tooltips devem ser acessíveis no mobile.
- Os textos dos tooltips devem possuir layout que facilite a leitura.

## Implementation Brief

- Adicionar um state para fazer o toggle do texto do tooltip.
- Verificar se é possível reutilizar/refatorar componentes de modal já existentes.

**Comment by calaca** [comment]
@nichollasrennah aqui vamos seguir com textos pequenos ou passar os textos dos tooltips para modais mesmo?

**Comment by nichollasrennah** [comment]
Vamos passar para o modal e deixar apenas aqueles campos que são mais difíceis de entender o seu conteúdo. Aqueles que são triviais podem sair.
