### ISSUE TITLE
Refatorar CurrencyInputField para funcionar com FormWizard

### ISSUE THREAD

**Issue by calaca** [ufersa/plataforma-sabia#395]
## Refactor Description

Ajustar o componente `CurrencyInputField` para que funcione com o componente `CurrencyInputField`.

---------------

## Acceptance criteria

- `CurrencyInputField` deve funcionar dentro do `Form`
- `CurrencyInputField` deve funcionar dentro do `FormWizard`

## Implementation Brief

- Passar a utilizar o componente `Controller` do `react-hook-form` em `CurrencyInputField`
OU
- Utilizar o ref do input:
```
const { register } = form:
return <NumberFormat inputRef={(el) => register(el)} />
```

**Comment by calaca** [comment]
Foi necessário refatorar o componente para passar a utilizar o `Controller` do `RHF` para que o `watch` também do `RHF` funcionasse corretamente.

**Comment by nichollasrennah** [comment]
@lcnogueira Você vai entrar aqui para ver junto com @calaca esse problema?

**Comment by lcnogueira** [comment]
Isso, @nichollasrennah . Só corrigir o bug nos testes e2e da tarefa #442. 

@calaca, vi que tava aguardando uma tarefa ontem. Quer dar uma olhada no porque do teste estar falhando na tarefa #442? Aí a gente ganha tempo e hoje à noite eu já olho essa tarefa aqui. Eu modifiquei o componente MaskedInputField, então, provavelmente, o cypress não tá conseguindo preencher o valor dentro do campo `cpf` que tem lá no perfil do usuário. Eu tentei algumas alternativas, mas não funcionou. Quando pesquisar na web por "input mask cypress" já vai encontrar alguns problemas relacionados a isso. 

Vlw, à noite tô por aqui :+1:
