### ISSUE TITLE
Incluir contribuintes na documentação

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#397]
## Feature Description

Usar o `all-contributors` bot para adicionar demais contribuintes.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by mateus4k** [comment]
Suggestion: https://intuit.github.io/auto/docs/generated/all-contributors

**Comment by lcnogueira** [comment]
@all-contributors please add @nicholasio for code,doc
@all-contributors please add @NaylsonFerreira for code,doc
@all-contributors please add @alexandreadames  for code,doc
@all-contributors please add @mateus4k  for code,doc
@all-contributors please add @marcusmota for code,doc
@all-contributors please add @exlleysantos for code
@all-contributors please add @ThaiMedeiros for code
@all-contributors please add @nichollasrennah for doc
@all-contributors please add @calaca for code,doc
@all-contributors please add @luizeboli for code,doc
@all-contributors please add @davioliveiira for code,doc

**Comment by lcnogueira** [comment]
@all-contributors please add @nicholasio for code, doc
@all-contributors please add @NaylsonFerreira for code, doc
@all-contributors please add @alexandreadames for code, doc
@all-contributors please add @mateus4k for code, doc
@all-contributors please add @marcusmota for code, doc
@all-contributors please add @exlleysantos for code
@all-contributors please add @ThaiMedeiros for code
@all-contributors please add @nichollasrennah for doc
@all-contributors please add @calaca for code, doc
@all-contributors please add @luizeboli for code, doc
@all-contributors please add @davioliveiira for code, doc

**Comment by lcnogueira** [comment]
@all-contributors please add @nicholasio for code and doc
@all-contributors please add @NaylsonFerreira for code and doc
@all-contributors please add @alexandreadames for code and doc
@all-contributors please add @mateus4k for code and doc
@all-contributors please add @marcusmota for code and doc
@all-contributors please add @exlleysantos for code
@all-contributors please add @ThaiMedeiros for code
@all-contributors please add @nichollasrennah for doc
@all-contributors please add @calaca for code and doc
@all-contributors please add @luizeboli for code and doc
@all-contributors please add @davioliveiira for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @nicholasio for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @nichollasrennah for doc

**Comment by lcnogueira** [comment]
@all-contributors please add @alexandreadames for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @NaylsonFerreira for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @mateus4k for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @marcusmota for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @calaca for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @luizeboli for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @davioliveiira for code and doc

**Comment by lcnogueira** [comment]
@all-contributors please add @exlleysantos for code

**Comment by lcnogueira** [comment]
@all-contributors please add @ThaiMedeiros for code

**Comment by lcnogueira** [comment]
@all-contributors please add @JoaoPauloSMoura for design

**Comment by lcnogueira** [comment]
@all-contributors please add @nicholasio for design and code

**Comment by lcnogueira** [comment]
@all-contributors please add @nichollasrennah for design and code
