### ISSUE TITLE
Tornar componentes da página de busca responsivos

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#40]
### Resumo da implementação
Deve-se estilizar a página de busca de maneira a manter o padrão visual do site e o padrão de estilização desenvolvido até agora.

- Os breakpoints devem ser criados dentro do  `styled-component` associado, para facilitar o entendimento posterior por outro desenvolvedor e manter o padrão do código.
- O site deve se manter responsivo entre todas as telas. Para isso, deve-se utilizar os breakpoints padrão disponibilizados através do [arquivo de tema](https://github.com/ufersa/plataforma-sabia/blob/master/packages/web/styles/theme.js) do projeto web.

### Critérios de aceitação
- O usuário deve ser capaz de utilizar a página de busca em qualquer dispositivo, independentemente do tamanho de tela que esteja usando.
- O código deve manter um padrão consistente, utilizando breakpoints e cores padrão através do arquivo de temas.

### Outras sugestões
- Se basear em [exemplo de e-commerce da própria documentação](https://www.algolia.com/doc/guides/building-search-ui/resources/demos/react/#e-commerce).

**Comment by nicholasio** [comment]
**IB** ✅

**Comment by lcnogueira** [comment]
Pretendo começar nessa aqui, @nicholasio . Enxerga alguma outra issue que seja mais prioritária?

**Comment by nicholasio** [comment]
@lcnogueira pode trabalhar nessa, tem umas do backend mas ainda precisa de alguns detalhes pra poder começar.
