### ISSUE TITLE
Detalhamento de Tecnologia - Compartilhar Tecnologia

### ISSUE THREAD

**Issue by mateus4k** [ufersa/plataforma-sabia#416]
## Feature Description

![image](https://user-images.githubusercontent.com/30202634/92822321-68fec500-f3a2-11ea-9f72-4f5da27c8d31.png)

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by mateus4k** [comment]
Pode descrever como será a funcionalidade, @nichollasrennah?

**Comment by nichollasrennah** [comment]
Funcionalidade semelhante ao magazine Luiza para compartilhar produtos https://www.magazineluiza.com.br/livro-geracao-de-valor/p/224952800/li/adml/
Compartilhar para WhatsApp Facebook twitter email e botão de copiar link
