### ISSUE TITLE
Custo de Implementação:  R$ NaN

### ISSUE THREAD

**Issue by marcusmota** [ufersa/plataforma-sabia#424]
O custo de implementação está como NaN quando a tecnologia não tem custos associados

![Screenshot 2020-09-16 at 10 20 45](https://user-images.githubusercontent.com/8526488/93318054-1ee46c00-f806-11ea-9acf-dc6ca8e635c1.png)

**Comment by nichollasrennah** [comment]
Coloque um espaço entre o : e o R$, pois está junto.
