### ISSUE TITLE
Correções no Formulário de Cadastro de Tecnologias 

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#426]
Esses foram os apontamentos feitos pelos pesquisadores que testaram o cadastro de tecnologias.

**CONTRIBUIÇÕES GERAIS:**
[ ]Incluir contador de caracteres para campos textarea (incluindo o número máximo de caracteres) Ex: 10/1000
[x] - Deixar mais claro quais campos são obrigatórios e quais são opcionais
[x] - Deixar mais claro quais campos podem adicionar mais de um item

**ABA: SOBRE A TECNOLOGIA**
[x] - Bioma da Tecnologia (Escolher mais de uma opção)
[x] - Dimensão da Tecnologia (Escolher mais de uma opção)
[x] - Atualizar nomenclatura das TRLs
[x] - Campo Proteção intelectual da tecnologia vem antes de "Tem patente". 
[x] - Campo "Tem patente" deve ficar oculto, aparecer somente se na questão "Proteção Intelectual da tecnologia" for marcada a opção "Propriedade Intelectual"

**ABA: CARACTERIZAÇÃO**
[ ] - Substituir "Objetivo secundário da tecnologia" por "Benefícios adicionais gerados pela adoção da tecnologia"
[x] - Retirar o campo "Problemas que a tecnologia acarreta", pois se confundi com o campo Riscos, que acaba sendo praticamente a mesma informação.
[ ] - Substituir "Contribuição da tecnologia" para "Resultados já obtidos com a tecnologia"

**ABA: CUSTOS E FINANCIAMENTO**
[x ] - Em cada linha inserir campos para Unidade de Medida (horas, m, dias, kg, meses, etc).
[x] - Todos os custos são opcionais

ABA: MAPAS E DOCUMENTOS
[x] - Incluir a opção de enviar vídeo

**ABA: RESUMO**
[x] - Ao final do cadastro ter campo de observação para o pesquisador descrever itens que ele não encontrou no formulário e acha interessante comunicar.

**Comment by luizeboli** [comment]
Podemos fechar essa issue já que está como `wontfix`
