### ISSUE TITLE
Construir página dos Termos de uso

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#435]
## Feature Description

- Contruir uma página simplificada com o conteúdo formatado dos Termos de Uso do serviço.

[TERMOS E CONDIÇÕES DE USO - PLATAFORMA SABIÁ.docx](https://github.com/ufersa/plataforma-sabia/files/5255523/TERMOS.E.CONDICOES.DE.USO.-.PLATAFORMA.SABIA.docx)

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by calaca** [comment]
@nichollasrennah temos layout dessa tela?

**Comment by nichollasrennah** [comment]
@calaca temos não, mas creio que seja apenas texto na página mesmo.
