### ISSUE TITLE
Lista de pedidos do Pesquisador

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#436]
## Feature Description

No momento que o usuário solicitar a aquisição de uma tecnologia, o pesquisador proprietário da tecnologia recebe uma notificação com o pedido. Esse pedido também ficará listado em Pedidos na área do pesquisador.

Os campos dessa lista de pedidos são:

- Título da tecnologia
- Nome do comprador
- Status do pedido
- Data do pedido
- Ações:
   - Fechar pedido
   - Cancelar pedido
   - Falar com o comprador

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura tela semelhante ao #437 com apenas alguns detalhes diferentes

**Comment by JoaoPauloSMoura** [comment]
![Pedidos (2)](https://user-images.githubusercontent.com/46350848/96122232-94a42c00-0ec7-11eb-895f-37efb02da548.png)

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura acabamos esquecendo alguns campos muito importantes nesse processo. São os campos que você criou na issue #365 . Quantidade, Uso e se tem financiamento. Qual seria a melhor forma de colocar isso? em forma de coluna na lista ou um ícone para um modal com os detalhes?

**Comment by JoaoPauloSMoura** [comment]
Poderia ser um campo com um "olho" sinalizando os detalhes do pedido, e abriria um modal mostrando as informações

**Comment by nichollasrennah** [comment]
Pode ser. Lembre de fazer isso na mesma tela dos meus pedidos da área do usuário.

**Comment by JoaoPauloSMoura** [comment]
![Captura de Tela 2020-11-01 às 00 55 30](https://user-images.githubusercontent.com/46350848/97794845-d29a9300-1bdd-11eb-9b0b-8b30c2407695.png)
Tela atualizada no Figma @nichollasrennah
