### ISSUE TITLE
Lista de Meus pedidos do usuário

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#437]
## Feature Description

No momento que o usuário solicitar a aquisição de uma tecnologia, o usuário receuma notificação com o pedido. Esse pedido também ficará listado em Meus Pedidos na área do usuário.

Os campos dessa lista de pedidos são:

Título da tecnologia
Nome do pesquisador que está vendendo
Status do pedido
Data do pedido
Ações:
 - Falar com o vendedor 
 - Cancelar o pedido

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura estava pensando em dar uma mãozinha aqui nessa issue e criar essa tela. Visto que o formato da lista são idênticas às que vc já criou. O que acha?

**Comment by JoaoPauloSMoura** [comment]
show de boa, pode deixar

**Comment by JoaoPauloSMoura** [comment]
![Pesquisador - Pedidos](https://user-images.githubusercontent.com/46350848/95678487-492a0f00-0ba3-11eb-97c6-6ffdd8c70e5a.png)

**Comment by JoaoPauloSMoura** [comment]
Finalizado

**Comment by nichollasrennah** [comment]
> ![Pesquisador - Pedidos](https://user-images.githubusercontent.com/46350848/95678487-492a0f00-0ba3-11eb-97c6-6ffdd8c70e5a.png)
> 

@JoaoPauloSMoura Troque o titulo para MEUS PEDIDOS. Ficou ótimo!

**Comment by JoaoPauloSMoura** [comment]
@nichollasrennah feito!

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura eu vi que você sugeriu a inativação do botão de mensagens quando o status do pedido estiver fechado ou cancelado. Mas essa funcionalidade precisa está ativa pelo menos para visualização. Dentro do modal das mensagens a gente trata essa questão do chamado ainda está ativo ou não, desabilitando a funcionalidade de enviar e receber mensagem.

**Comment by JoaoPauloSMoura** [comment]
Corrigido!
