### ISSUE TITLE
Registrar uma avaliação no relato de experiência

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#441]
## Feature Description

Usuários registrados poderão registrar uma avaliação de relato de experiência

![Relatos de Experiência](https://user-images.githubusercontent.com/48101231/95197735-7005d100-07b0-11eb-93ba-21c8fb9624d4.png)

- Na aba de relato de experiência colocar um botão AVALIE ESSA TECNOLOGIA (ver o melhor lugar na tela acima para inserir esse botão)
- Abrirá uma tela sobreposta com os seguintes campos:
- Você já têm essa tecnologia? "Ainda Não" e "Sim, já tenho"

![Já possui a tecnolgia_](https://user-images.githubusercontent.com/48101231/95197308-c9b9cb80-07af-11eb-8b24-b296475ad0da.png)

- Caso a resposta seja não, mostrar a seguinte mensagem: "Essa avaliação é apenas para pessoas que já adquiriram e estão utilizando essa tecnologia em seu dia a dia." E abortar o processo de cadastro.

![não possui tecnologia](https://user-images.githubusercontent.com/48101231/95197370-e3f3a980-07af-11eb-91c8-8f6cb72227cf.png)

- Caso a resposta seja sim, segue as seguintes perguntas:
  - Como foi sua experiência com essa tecnologia? (textarea)
  - Quais pontos positivos? (textarea)
  - Quais pontos negativos? (textarea)
  - Qual sua nota para essa tecnologia? (nota de 1 a 5 estrelas) 
- Incluir botão REGISTRAR AVALIAÇÃO
- Fechar tela sobreposta.

![form  de experiência](https://user-images.githubusercontent.com/48101231/95197416-f4a41f80-07af-11eb-813b-5b51edd948bd.png)

-------------

## Acceptance criteria

- Somente usuários cadastrados poderão registrar uma avaliação
- Somente usuários logados poderão registrar uma avaliação

## Implementation Brief

**Comment by nicholasio** [comment]
@nichollasrennah Não precisamos de trabalho na API aqui, isso já foi feito, confirma @alexandreadames ?

Aqui precisamos do design pra implementar o formulário de cadastro do relato no front.

**Comment by nichollasrennah** [comment]
@nicholasio tranquilo. Estou retirando a label API

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura adicionando você para construir essa tela também.

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura assim que estiver disponível, prepare esta tela.

**Comment by JoaoPauloSMoura** [comment]
Show @nichollasrennah, pode deixar

**Comment by JoaoPauloSMoura** [comment]
Telas finalizadas, assim que possível da uma olhada no Figma @nichollasrennah

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura muito bom! Minha sugestão é colocar campos textarea nos relatos.

**Comment by mateus4k** [comment]
@JoaoPauloSMoura pode mandar o link de onde está essa alteração no Figma? Olhei lá mas não consegui achar :confused:

**Comment by nichollasrennah** [comment]
@mateus4k já teve acesso ao Figma?
