### ISSUE TITLE
Correções de bug - Formulários de Tecnologias - Aba Responsáveis

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#442]
- Quando tenta editar o campo Telefone dos responsáveis a máscara não deixa colocar o último dígito e evita salvar
- O campo ID lattes fica em branco, mesmo quando esse número já está preenchido na área do usuário

**Comment by lcnogueira** [comment]
Bugs identificados:
- Campo telefone de um responsável já adicionado não aparece na próxima visita à página;
- Ao não preencher o telefone, uma msg é exibida e, em seguida, não é mais possível alterar o telefone;
