### ISSUE TITLE
Correções de bug - Formulários de Tecnologias - Aba Mapas e Anexos

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#443]
- Ao abrir para editar essa aba, os registros que estavam salvos somem do banco. 
- Campo Onde a tecnologia pode ser aplicada não está sendo salva. Sempre que vamos editar esse campo está em branco. É para deixar padrão o Semiárido, visto que só tem essa opção, por enquanto. 
- Não está upando os documentos
- "Onde a tecnologia é desenvolvida", no placeholder colocar "Procurar instituições e empresas"

**Comment by nicholasio** [comment]
Passando pra @mateus4k investigar.

**Comment by mateus4k** [comment]
A parte do upload provavelmente será resolvida no #432

**Comment by nichollasrennah** [comment]
@mateus4k pronto. A issue #432 foi finalizada. Acunha!

**Comment by nichollasrennah** [comment]
Essa issue vai ficar @mateus4k ou @marcusmota ?

**Comment by mateus4k** [comment]
Estou fazendo 👍

**Comment by nichollasrennah** [comment]
Eu alterei algumas coisas aí no corpo. São coisas simples.
