### ISSUE TITLE
Duração do processo de instalação da tecnologia permite número negativo

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#444]
Duração do processo de instalação da tecnologia – pode-se excluir a possibilidade de seleção de dias negativos; Permitir somente inteiros positivos.

**Comment by nicholasio** [comment]
@calaca Isso é uma alteração simples no front, você pode aproveitar e fazer uma alteração no back também? Basta mudar o validator da rota de tecnologia pra não aceitar números negativos (cc  @alexandreadames ).

**Comment by calaca** [comment]
> @calaca Isso é uma alteração simples no front, você pode aproveitar e fazer uma alteração no back também? Basta mudar o validator da rota de tecnologia pra não aceitar números negativos (cc @alexandreadames ).

@nicholasio claro!

**Comment by alexandreadames** [comment]
```javascript
class StoreTechnology extends BaseValidator {
	get rules() {
		return {
			title: 'required',
			description: 'required',
			// private: 'required',
			// thumbnail: 'required',
			// likes: 'required',
			patent: 'required',
			// primary_purpose: 'required',
			// application_mode: 'required',
			installation_time: 'number|above:0', <-- Essa alteração
			// solves_problem: 'required',
			// entailes_problem: 'required',
		};
	}
}
```
