### ISSUE TITLE
Correções de bug - Formulários de Tecnologias - Aba Sobre a tecnologia

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#457]
- Todos os campos dropbox colocar em ordem alfabética
- Campo Proteção intelectual da tecnologia vem antes de "Tem patente".
Campo "Tem patente" trocar por "Tem registro de patente?" e deve ficar oculto, aparecer somente se na questão "Proteção Intelectual da tecnologia" for marcada a opção "Propriedade Intelectual"
- Informar de alguma maneira quais campos são obrigatórios e quais são opcionais
- Informar de alguma maneira que os campos: PUBLICO-ALVO e PALAVRAS-CHAVE o usuário pode adicionar opções

**Comment by calaca** [comment]
@nichollasrennah fiz todos os itens menos um:
- Esconder o campo "Tem registro de patente?" por padrão e apresentá-lo apenas quando em "Proteção Intelectual da tecnologia" for marcada a opção "Propriedade Intelectual"

![image](https://user-images.githubusercontent.com/10481028/94993378-05158980-0567-11eb-8765-e5a3398be464.png)

Não fiz isso pois o campo "Proteção Intelectual da tecnologia" é obrigatório e o usuário teria que preenchê-lo de qualquer maneira. Na minha opinião, não faz muito sentido esconder o campo "Tem registro de patente?" por conta disso. O que acha?

**Comment by nichollasrennah** [comment]
> @nichollasrennah fiz todos os itens menos um:
> 
> * Esconder o campo "Tem registro de patente?" por padrão e apresentá-lo apenas quando em "Proteção Intelectual da tecnologia" for marcada a opção "Propriedade Intelectual"
> 
> ![image](https://user-images.githubusercontent.com/10481028/94993378-05158980-0567-11eb-8765-e5a3398be464.png)
> 
> Não fiz isso pois o campo "Proteção Intelectual da tecnologia" é obrigatório e o usuário teria que preenchê-lo de qualquer maneira. Na minha opinião, não faz muito sentido esconder o campo "Tem registro de patente?" por conta disso. O que acha?

@calaca na realidade essas opções aí desse campo estão desatualizadas. Precisa inclusive alterar o seed.
Esse campo Proteção Intelectual tem duas opções: Domínio Público e Proteção Intelectual.

Só é necessário saber se tem registro de patente se a tecnologia não esteja sob domínio público. Ou seja, se for marcado a opção de Proteção Intelectual aparece se tem registro de patente ou não.

**Comment by nichollasrennah** [comment]
Onde você colocou que pode adicionar novas opções nesse campo. Coloque que basta digitar e teclar enter. Para ficar mais instrutivo.

**Comment by nicholasio** [comment]
@nichollasrennah @calaca se só terá dois valores possivel não seria melhor esse campo ser um booleano? Semelhante ao "Tem Patente?" só que no caso perguntando se é de domínio público. Na minha opinião nem precisa ser uma taxonomia esse campo (cc @alexandreadames )

**Comment by alexandreadames** [comment]
Exato @nicholasio , basta colocar "Tem proteção intelectual", se sim ele pode marcar se tem patente ou não. Se não tem proteção intelectual é de domínio publico. Nesse caso a nível de banco de dados basta colocar mais um campo em `technologies`

**Comment by nichollasrennah** [comment]
Tem razão @alexandreadames e @nicholasio

**Comment by calaca** [comment]
@nichollasrennah @nicholasio nesse caso faço a troca para o switch ao invés de select agora e depois ajustamos a API?

**Comment by calaca** [comment]
@nichollasrennah alterei a dica de uso do select para:
![image](https://user-images.githubusercontent.com/10481028/95021433-52692800-0647-11eb-9412-7ef5bc7ea471.png)
