### ISSUE TITLE
Criar tela de perfil do curador

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#463]
## Feature Description

A partir do momento que o usuário tem o perfil de curador, aparecer no menu dentro da área do curador a opção PERFIL DO CURADOR.

Essa tela é para apresentar as opções de área e subárea que já foram escolhidas na solicitação para ser um curador. Essa opção é para possibilitar que o usuário altere essas opções.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by JoaoPauloSMoura** [comment]
![perfil](https://user-images.githubusercontent.com/46350848/95681446-4ab10280-0bb6-11eb-956a-0bf25ed04b1c.png)

**Comment by JoaoPauloSMoura** [comment]
@nichollasrennah oq vc acha?

**Comment by nichollasrennah** [comment]
É isso mesmo @JoaoPauloSMoura

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura onde você fez essa tela? criou outro Figma?

**Comment by JoaoPauloSMoura** [comment]
Está no figma novo @nichollasrennah, mandei uma msg no sábado lá no Slack, pedindo que me enviassem os emails para que eu mandasse o invite, responda lá com seu email que compartilho com vc

**Comment by JoaoPauloSMoura** [comment]
![Captura de Tela 2020-11-01 às 00 55 30](https://user-images.githubusercontent.com/46350848/97794856-fbbb2380-1bdd-11eb-9358-fabad1aee7d2.png)
Tela atualizada no figma @nichollasrennah
