### ISSUE TITLE
Correções de bug - Formulários de Tecnologias - Aba Resumo

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#465]
- Inserir um campo de comentário (textarea) ao final da página, antes dos aceites, para que o cadastrador possa enviar mensagem para o curador. Essa mensagem não precisa ficar registrada na tabela da revisão, visto que ela não será publicada. Será vista apenas pela curador no momento da avaliação.
- Adicionar esses checkbox para ser marcado no lugar da Política de Privacidade e Termos de Uso de Serviços:
   - Declaro ciência de que devo fornecer apenas informações verdadeiras no cadastro das tecnologias. Veja mais nos Termos e Condições de Uso. (OBRIGATÓRIO)
   - Estou ciente de que as informações cadastradas são de minha inteira responsabilidade, e a Plataforma Sabiá não responderá por quaisquer violações ao Direito de Propriedade Intelectual e Direito Autoral de terceiros. Veja mais nos Termos e Condições de Uso. (OBRIGATÓRIO)
   - Estou ciente de que poderei ser penalizado com advertência, suspensão e encerramento da minha conta por eventuais violações a direitos de terceiros no cadastro das tecnologias, como o Direito de Propriedade Intelectual e Direito Autoral. Veja mais nos Termos e Condições de Uso. (OBRIGATÓRIO)
   - Declaro ciência de que as transgressões a direitos de terceiros no cadastro das tecnologias podem implicar em responsabilização na esfera jurisdicional cível e criminal. Veja mais nos Termos e Condições de Uso. (OBRIGATÓRIO)

**Comment by nichollasrennah** [comment]
@alexandreadames Precisa ver esse campo de comentários aí que ficará na ultima tela do cadastro.

**Comment by nichollasrennah** [comment]
Você pode ver a issue #473 que Naylson pegou que trata essas questões dos disclaimers... talvez só precise ver essa questão do comentário mesmo.

**Comment by nichollasrennah** [comment]
@calaca creio que você pode ir fazendo o front dessa feature, enquanto o pessoal do back prepara na API.

**Comment by calaca** [comment]
@nicholasio o PR #506 resolve parcialmente essa issue. No caso fica faltando o textarea para enviar comentários.

**Comment by nichollasrennah** [comment]
@alexandreadames que ficará que incluir na API esse campo de observação para você poder integrar com o front. Alexandre, esse campo é aquele que falei que o usuário do cadastro vai conseguir informar detalhes ao curador. Esse campo é importante.

**Comment by nichollasrennah** [comment]
@alexandreadames acho que agora @calaca poderá inserir o campo de comentário no final do cadastro de tecnologias e integrar com a API, não é?

**Comment by alexandreadames** [comment]
> @alexandreadames acho que agora @calaca poderá inserir o campo de comentário no final do cadastro de tecnologias e integrar com a API, não é?

Falta apenas a aprovação da minha PR.

**Comment by nichollasrennah** [comment]
Pronto @calaca pode concluir esse aqui.
