### ISSUE TITLE
Permitir filtrar tecnologias pela API

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#469]
## Feature Description

Permitir filtrar através da API o GET das tecnologias, por STATUS X ou outra propriedade.

---------------

**Comment by luizeboli** [comment]
@alexandreadames o que comentamos na reunião, a necessidade de filtrar o GET de todas as tecnologias.

**Comment by nichollasrennah** [comment]
Essa issue já pode ser fechada?
