### ISSUE TITLE
Adicionar checks com os Disclaimers no cadastro de usuário

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#473]
## Feature Description

Adicionar os seguintes disclaimers no cadastro de usuário para serem marcados e registrados no banco de dados os itens obrigatórios e opcionais e data e hora do cadastro.

- Concordo com a Política de Privacidade e os Termos e Condições de Uso. (OBRIGATÓRIO)
- Concordo com o processamento dos meus dados pessoais para fins de fornecimento dos serviços da Plataforma Sabiá. Veja mais na Política de Privacidade. (OBRIGATÓRIO) 
- Concordo em respeitar a legislação brasileira vigente no conteúdo que eu venha a disponibilizar na Plataforma Sabiá, sendo de minha exclusiva responsabilidade. Veja mais nos Termos e Condições de Uso. (OBRIGATÓRIO)
- Estou ciente de que posso revogar o consentimento de uso dos meus dados pessoais a qualquer momento. Todavia, não poderei mais utilizar os serviços da plataforma que necessitam do uso e da coleta de dados pessoais. Veja mais na Política de Privacidade. (OBRIGATÓRIO) 
- Estou ciente quanto ao canal de suporte da Plataforma Sabiá, que estará à disposição para sanar eventual dúvida que possa surgir. (OBRIGATÓRIO)
- Estou ciente que em hipótese alguma será constituído vínculo cooperativo, associativo, societário ou empregatício entre a plataforma, os usuários cadastrados e os parceiros. Veja mais nos Termos e Condições de Uso. (OBRIGATÓRIO) 
- Concordo com o processamento dos meus dados pessoais com o objetivo de receber publicidade da Plataforma Sabiá e de terceiros parceiros. Veja mais nos Termos e Condições de Uso. (OPCIONAL)

O botão de cadastro só ficar ativo se todos os checkbox obrigatório for marcado.

---------------

## Acceptance criteria

* 

## Implementation Brief
Criar as seguintes tabelas no banco:

* disclaimers
  * id - integer
  * description - text
  * required - boolean
  * type - enum('privacypolicy', 'termsofuse')
  * version - varchar
**-**
* user_disclaimer
  * user_id - integer
  * disclaimer_id - integer
  * created_at - datetime
  * updated_at - datetime

Salvar no banco no momento do cadastro

**Comment by NaylsonFerreira** [comment]
@nichollasrennah  atualizei o IB. Se estiver ok posso começar

**Comment by nichollasrennah** [comment]
@NaylsonFerreira Era bom aproveitar e colocar os disclaimers da politica de privacidade e dos termos de uso serem registrados na mesma tabela né? cria um campo tipo para escolher privacypolicy ou termsofuse e outro campo com a versão da politica de privacidade ou do termo de uso.

**Comment by NaylsonFerreira** [comment]
Adicionado!
Tem mais alguma sugestão?

**Comment by nichollasrennah** [comment]
Pronto. Agora é mandar bala.
