### ISSUE TITLE
Layout e Texto dos emails transacionais.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#48]
## Feature Description

Em #33 foi introduzido o envio de emails no sistema. Por hora, os templates estão bem simples, precisamos de um layout/design melhor e também decidir o texto desses emails.

---------------

## Acceptance criteria

* N/A

## Implementation Brief

* Melhorar o design/texto dos emails em `packages/api/resources/view/emails`. Os emails são escritos usando a engine edge.

**Comment by nicholasio** [comment]
@nichollasrennah designicando essa pra você por enquanto pra ver a questão dos layouts dos email e do texto.

**Comment by nichollasrennah** [comment]
**E-MAIL DE ATIVAÇÃO DE CADASTRO**

To: {usermail}
Subject: PLATAFORMA SABIÁ: Ativação de Cadastro
Body:
Olá {name},

Agradecemos o seu cadastro na Plataforma Sabiá.

Agora só falta ativar o seu cadastro.

Para validar esse cadastro, clique no botão abaixo:
 
{ConfirmLink} --> Isso é um botão com o link de confirmação
 
Atenciosamente,

Equipe Plataforma Sabiá

------------------------------------------------------------------------

**E-MAIL DE CONFIRMAÇÃO DE CADASTRO**

To: {usermail}
Subject: PLATAFORMA SABIÁ: Confirmação de Cadastro
Body:
Olá {name},

Seu cadastro na Plataforma Saibá está ativo.

Utilize o usuário {username} e sua senha para acessar a plataforma www.plataformasabia.com.br
 
Atenciosamente,

Equipe Plataforma Sabiá

------------------------------------------------------------------------

**E-MAIL DE RECUPERAÇÃO DE SENHA**

To: {usermail}
Subject: PLATAFORMA SABIÁ: Recuperação de Senha
Body:
Olá {name},

Foi feita uma solicitação para renovação de senha na Plataforma Sabiá. 
Caso você não tenha feito essa solicitação, por favor ignore este e-mail.

Acesse o link abaixo para informar uma nova senha para sua conta na Plataforma Sabiá.

{recoverylink}
 
Atenciosamente,

Equipe Plataforma Sabiá

------------------------------------------------------------------------

**E-MAIL DE CONFIRMAÇÃO DE ALTERAÇÃO DE SENHA**

To: {usermail}
Subject: PLATAFORMA SABIÁ: Alteração de Senha
Body:
Olá {name},

A senha da sua conta na Plataforma Sabiá foi alterada com sucesso.
 
Atenciosamente,

Equipe Plataforma Sabiá

**Comment by nicholasio** [comment]
@ThaiMedeiros Também passei essa issue pra você, ela é bem simples, é basicamente atualizar o template dos emails na API para o texto que o @nichollasrennah definiu.
