### ISSUE TITLE
Cancelar pedido

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#483]
## Feature Description

- A funcionalidade de cancelar pedido pode ser realizada pelo vendedor (pesquisador) como pelo comprador (usuário)
- Ao solicitar o cancelamento, pode-se apresentar um campo de observações que pode ser preenchido para alguma mensagem, mas é opcional.
- Apresentar botão CANCELAR PEDIDO, que apenas atualizará o status do pedido e registra as observações na área de mensagens entre comprador e vendedor.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by JoaoPauloSMoura** [comment]
![image](https://user-images.githubusercontent.com/46350848/96127873-f4500680-0eca-11eb-8109-b6c3913cb692.png)

**Comment by alexandreadames** [comment]
@nichollasrennah um pedido pode ser cancelado caso ele tenha sido fechado?

**Comment by nichollasrennah** [comment]
Não. Depois de fechado não pode cancelar.

Em qua, 18 de nov de 2020 15:16, Alexandre Ádames <notifications@github.com>
escreveu:
