### ISSUE TITLE
Mensagens dos pedidos

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#484]
## Feature Description

- Na tela de Pedidos (Área do usuário) e Meus Pedidos (Área do Pesquisador) tem a opção do Comprador (usuário) e vendedor (pesquisador) conversarem entre sim por meio de mensagens (estilo chat da OLX).

![Usuário - Meus Pedidos](https://user-images.githubusercontent.com/48101231/95750583-be651500-0c73-11eb-9e51-c8eb2584f773.png)

- Ao clicar no ícone aparecer um modal com as mensagens trocadas e o campo para digitar a mensagem com o botão com ícone de envio.
- Botão na parte superior de fechar o modal
- No título do modal ter o nome do usuário que está conversando.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by JoaoPauloSMoura** [comment]
![image](https://user-images.githubusercontent.com/46350848/96712542-b09b4800-1375-11eb-98d3-8cb59e9fd0e0.png)

**Comment by JoaoPauloSMoura** [comment]
@nichollasrennah fiz dessa forma ao invés de um modal, oq vc acha?

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura eu gostei bastante... sugiro três pequenas coisas:
1 - Ter alguma forma de sinalizar em que tela ele está... pode-se pensar em colocar em negrito no menu ativo e título da tela
2 - Na lateral onde tem o responsável, colocar também a instituição dele (sigla da organização)
3 - No espaço onde tem a tecnologia adquirida, abaixo de data do pedido, colocar também a quantidade desejada.

**Comment by JoaoPauloSMoura** [comment]
Show, com realação a essa primeira sugestão, quando ele clicar em voltar ele vai voltar para a tela em que ele partiu, por exemplo, "mesagens" ou "minhas Tecnologias", vc sugere deixar elas em negrito para sinalizar de onde ele saiu?

**Comment by nichollasrennah** [comment]
Isso. Pode deixar em negrito a tela de pedidos (se essa tela for acessada pelo pesquisador vendedor) ou meus pedidos (usuário comprador)
