### ISSUE TITLE
Funcionalidade de Fale conosco

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#487]
## Feature Description

Deve ser implementado uma feature de Fale Conosco para permitir qualquer usuário entrar em contato com a administração da plataforma.

- Precisa encontrar o melhor local dentro do layout para inserir o link ou ícone do Fale Conosco
- Abrir modal com os campos:
   - Nome
   - Email
   - Telefone (opcional)
   - Assunto (lista suspensa com as opções: sugestão de melhoria, reportar erro, reportar abuso, crítica)
   - Mensagem
- Botão de enviar 

---------------

## Acceptance criteria

* 
- Qualquer usuário pode enviar uma mensagem ao Fale Conosco
- Não precisa ficar armazenada no banco essas mensagens. Toda a troca de conversa será por meio do email.
- Usuário e admin (plataformasabia@ufersa.edu.br) recebem email de confirmação
- Ao enviar apresentar mensagem de confirmação de envio

## Implementation Brief

*

**Comment by JoaoPauloSMoura** [comment]
![Captura de Tela 2020-10-24 às 20 45 16](https://user-images.githubusercontent.com/46350848/97095754-d789a080-1639-11eb-8d7a-ac4faf4d80fd.png)

**Comment by JoaoPauloSMoura** [comment]
@nichollasrennah percebi que não existia a página de contato, acredito que faz sentido o formulário ficar aqui

**Comment by nichollasrennah** [comment]
É isso mesmo. 
Precisa apenas dizer a mensagem de sucesso após clicar em enviar a mensagem.

**Comment by JoaoPauloSMoura** [comment]
show, vou fazer o modal
