### ISSUE TITLE
Atualizar filtros da busca

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#489]
## Feature Description

Na página de resultados da busca atualizar a lista de filtros incluindo os seguintes parâmetros:

- Classificação:
- Dimensão:
- Público-alvo
- Custo de implantação (min e max)

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
@luizeboli essa issue vai ser explicada por @lcnogueira

**Comment by luizeboli** [comment]
Done 👍
