### ISSUE TITLE
Fechar pedido

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#495]
## Feature Description

- O processo final positivo da negociação do vendedor (pesquisador) com o comprador (usuário) é o fechamento do pedido. É nessa fase que esse processo se conclui.
- Ao clicar no botão fechar pedido aparecerá um modal com os seguintes campos:
  - Quantidade adquirida:
  - Valor unitário negociado:
  - Precisa aparecer o Valor total (qtde x valor unitário)
- Um botão para concluir o processo.

---------------

## Acceptance criteria

* 
 - Somente pedidos com status ativos poderão fechar pedido.
 - Somente pesquisadores donos do cadastros poderão fechar o pedido.
 - O usuário comprador não pode fechar o pedido.

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
É isso mesmo.!

**Comment by alexandreadames** [comment]
@nichollasrennah com relação ao campo "Quantidade adquirida", seria necessário gravar no banco essa informação sendo diferente da quantidade informada na hora da solicitação da compra? Ou eu posso sobrescrever esse valor na hora do fechamento?

**Comment by nichollasrennah** [comment]
Pode sobrescrever Alexandre.

Em seg, 16 de nov de 2020 17:48, Alexandre Ádames <notifications@github.com>
escreveu:
