### ISSUE TITLE
Erro na listagem dos custos

### ISSUE THREAD

**Issue by alexandreadames** [ufersa/plataforma-sabia#499]
## Feature Description

Erro na listagem do custos da tecnologia e na aba de Mapas e Anexos - Onde a tecnologia é desenvolvida e onde já é utilizada.

---------------

## Acceptance criteria

Na hora de listar os custos da tecnologia no front mostrar os custos.

## Implementation Brief

Consertar a rota para listar os custos da tecnologia através do ID da tecnologia.
```javascript
        /**
	 * Show a technology costs.
	 * GET technologies/:id/costs
	 */
	async show({ request }) {
		return TechnologyCost.query()
			.with('costs')
			.withParams(request);
	}
```

- Onde a tecnologia é desenvolvida 
- Onde já é utilizada

**Comment by NaylsonFerreira** [comment]
É bom rever os testes dessa tela também, já que isso passou despercebido.
