### ISSUE TITLE
Implementar o fluxo de correção solicitadas pelo curador pelo pesquisador

### ISSUE THREAD

**Issue by alexandreadames** [ufersa/plataforma-sabia#500]
## Feature Description

Fluxo que permite ao pesquisador efetuar as mudanças solicitadas pelo curador e enviar novamente para revisão.

---------------

## Acceptance criteria

1. O pesquisador efetua as mudanças e envia novamente para o curador. Ele pode enviar uma comentário ao enviar.
2. O status da tecnologia muda para `changes_made`;

## Implementation Brief

Criar um novo esquema: `technology_comments`. Nesse esquema irá o `user_id`, `technology_id` e um `comment`.
**Na rota** 
`PUT /technologies/:id/finalize-registration` aceitar o campo `comment`. Criar um registro na tabela `technology_comments`.

**Novas rotas:**
`PUT /technologies/:id/revision`. Aceitar o campo `comment`. Criar um registro na tabela `technology_comments`.Além disso deve enviar a technologia novamente para revisão após o curador pedir `requested_changes`. Setar o status da technologia para `changes_made` e enviar email para curador.

`GET /technologies/:id/comments`. Essa rota irá mostrar os comentários feitos pelo pesquisador na hora que o curador for revisar a tecnologia.

**Comment by luizeboli** [comment]
@alexandreadames quando o pesquisador for efetuar as mudanças, vamos exibir um checkbox caso a tecnologia esteja no status `requested_changes`.

Esse checkbox vai habilitar um input de descrição pro pesquisador poder escrever qualquer comentário?

Se esse checkbox estiver habilitado, o botão **Concluir**, fará um request pra outro endpoint?

Essa observação que o pesquisador inserir precisa aparecer no modal de avaliação pro curador, certo?

**Comment by alexandreadames** [comment]
A ideia é basicamente isso, permitir que o pesquisador possa fazer as mudanças, e enviar novamente para revisão mandando opcionalmente um comentário. Eu vou criar um novo endpoint onde você possa enviar um comentário, nesse endpoint eu vou setar o status da tecnologia para `changes_made` e enviar um email para o revisor. Eu prentendo gravar esse registro na tabela de revisões, esse registro terá o id do pesquisador, o id da tecnologia e o comentário em description, ai eu deixo assessment em branco, já que não cabe. Quando o curador entrar na sua área que vê o status `changes_made` ele pode clicar em algum botão para ver o comentário caso exista.

**Comment by alexandreadames** [comment]
> A ideia é basicamente isso, permitir que o pesquisador possa fazer as mudanças, e enviar novamente para revisão mandando opcionalmente um comentário. Eu vou criar um novo endpoint onde você possa enviar um comentário, nesse endpoint eu vou setar o status da tecnologia para `changes_made` e enviar um email para o revisor. Eu prentendo gravar esse registro na tabela de revisões, esse registro terá o id do pesquisador, o id da tecnologia e o comentário em description, ai eu deixo assessment em branco, já que não cabe. Quando o curador entrar na sua área que vê o status `changes_made` ele pode clicar em algum botão para ver o comentário caso exista.

Devido a novas conversas eu tive que mudar o IB.
