### ISSUE TITLE
Não faz upload de documentos

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#502]
No cadastro de tecnologias na aba de Mapas e Anexos não realiza o upload de documentos.

**Comment by alexandreadames** [comment]
@marcusmota o erro que está ocorrendo é no servidor: 413 Request Entity Too Large, para consertar basta seguir esse tutorial:
https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by marcusmota** [comment]
Issue corrigida 👍

**Comment by marcusmota** [comment]
Issue corrigida 👍
