### ISSUE TITLE
Implementar CRUD de usuários.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#51]
## Feature Description

CRUD de usuários com as devidas permissões (i.e quem pode criar, remover e alterar).

Precisaremos criar um middleware `gate` para verificar as permissões

```javascript
Route.put('user/:id', 'UserController.update').middleware(['auth', 'gate:update-users']);
```

Dentro do middleware
```javascript
async handle (context, next, properties) {
  // a partir de context você tem acesso a request e os parãmetros
  // properties são as propriedades que você passa pro middleware (`updates-users`)
  // verificar como os parâmetros são enviados, não tenho certeza se properties é um array.
  return current_user_can(properties[0], context.request.id);
}
```

`current_user_can` seria uma função utilitária que pegar a permission e verificaria o seguinte:
1. Se o usuário possui a permissão individual  ou se a role que o usuário possui tem `update-users`
2. Realizar checagens adicionais dependendo da `permission` e.g: se o usuário tem poder pra editar o usuário passado.
---------------

## Acceptance criteria

* É possível criar usuários através dessa nova rota somente por alguém que tenha permissão. O mesmo para remover e alterar.
* Usuário agora possui first_name, last_name e avatar, com suporte a upload.
 

## Implementation Brief

* Criar rota `GET /users` - requer a permissão: `list-users`
* Criar rota `POST /users` - requer a permissão: `create-users`
   - Deverá ser possível associar uma `role` ou permissões individuais através dessa rota.
* Criar rota `PUT /users/:id` - requer a permissão: `update-users`, a permissão `update-users` também depende do id do usuário. E.g: alguém com a permissão update-users só pode editar usuários com `roles` hierarquicamente abaixo dele.
    - Deverá ser possível associar uma `role` ou permissões individuais através dessa rota.
* Criar rota `DELETE /users/:id` - requer a permissão: `delete-users`, depende do id do usuário também.

**Comment by nicholasio** [comment]
@NaylsonFerreira Já designei essa issue pra você, até amanhã vou detalhar bem ela, mas caso já queira ir começando fique a vontade.

**Comment by NaylsonFerreira** [comment]
@nicholasio  Estou vendo agora. Vou usar o CRUD das Tecnologias como exemplo

**Comment by nicholasio** [comment]
@NaylsonFerreira parece que o @exlleysantos já começou essa issue.

@exlleysantos Lembrar de movar para "In Progress" e preferencialmente comentar quando começar a trabalhar numa issua, principalmente uma como essa que ainda está incompleta

**Comment by NaylsonFerreira** [comment]
Tranquilo

**Comment by nicholasio** [comment]
@exlleysantos Adicionei os detalhes. Essa issue é um pouco mais avançada.

cc @alexandreadames coloquei uns detalhes de permissões aqui.

**Comment by nicholasio** [comment]
@exlleysantos Como está o progresso aqui? Se não tiver feito muito coisa avise que colocamos outra pessoa pra trabalhar nessa pois ela tá bloqueando algumas tarefas.

**Comment by nicholasio** [comment]
@alexandreadames passando essa pra você já que você já estava trabalhando com a parte de permissões.

**Comment by alexandreadames** [comment]
@nicholasio Eu pensei em fazer o seguinte: 
Criar os seguintes papeis, baseado no documento de requisitos:
```javascript
const roles = [
			{
				role: 'DEFAULT_USER',
				description: 'Usuário comum',
			},
			{
				role: 'RESEARCHER',
				description: 'Usuário Pesquisador',
			},
			{
				role: 'INVESTOR',
				description: 'Usuário Investidor',
			},
			{
				role: 'REVIEWER',
				description: 'Usuário Curador/Revisor',
			},
			{
				role: 'ADMIN',
				description: 'Usuário Administrador',
			},
		];
```
Dois middlewares `role:<role_list>, permission:<permission_list>`

1. Antes de executar qualquer código dentro dos middlewares, verificar se o papel do usuário logado é ADMIN, se for retorna logo true; 
2. No middleware `role` fazer um `checkRole`, ou seja, rotas protegidas por `role` seriam apenas para checar o papel, exemplo `POST /users` seria uma rota protegida por ADMIN, role:admin, só checaria o papel.
3. No middleware `permission`:
Se a permissão for do tipo create- ou list- ou details- checar apenas a permissão
Se a permissão for do tipo update- ou delete- verificar se o usuário que está tentando fazer a operação é o `owner` ou um papel relacionado,  ou seja, dentro do middleware `permission` teríamos um tratamento especial sempre que for `update-users`, `delete-users`, `update-technologies`, `delete-technologies`. A minha ídeia é criar dentro do model User ou Technology um método com a mesma assinatura, com implementação diferente:
Dentro do Model User:
Checar apenas se o usuário que está logado é o mesmo do recurso passado;
Dentro do Model Technology
Checar se o usuário que está logado faz parte do grupo de papéis que podem editar a technologia, ex.
Fulano criou a tecnologia 1, ou seja é OWNER
Sicrano está tentando editar a tecnologia 1, sendo REVIEWER
Resumindo: Nessa proposta que eu fiz, apenas usuários ADMIN podem editar ou deletar recursos de todos os usuários, se ele não for admin só pode editar o próprio recurso no caso de usuário, e pode editar o recurso de outro usuário caso façamos a lógica dentro do Model.

**Comment by alexandreadames** [comment]
Para atualizar o perfil do usuário poderia-se usar uma rota dedicada: 
`Route.put('/user/me', 'AuthController.updateMe').middleware(['auth']);`

**Comment by nicholasio** [comment]
@alexandreadames Muito bom, só algumas considerações:

- Acho que seria interessante uma permissão `update-users`, o usuário que tem ela, poderá atualizar qualquer usuário, da mesma forma com `delete-users`. A princípio somente admins terão essa permissão. Ficaria mais flexível assim por podemos fazer um usuário não admin ter permissões sobre todos os usuários por exemplo! Caso no futuro façamos uma outra role menos poderoso que admin, por exemplo: gerente ou editor.
- No caso dos usuários que só tiverem `update-user` ou `delete-user` aí sim faríamos a verificação invidual como você falou, entendeu? 

Vamos precisar criar uma tabela de cada `role` e suas respectivas `permissions` exemplo:

Eu acho que por hora podemos focar nas roles `default_user` e `admin` pois só iremos implementar funcionalidades referente a esses dois por enquanto, o que acha? A medida que formos implementando as funcionalidades das outras roles vamos atualizando.

| role | permissions
|---|---|
| DEFAULT_USER | edit-user, create-technologies etc...
| ADMIN | edit-users, delete-users, create-technologies, edit-techonologies etc...
| RESEARCHER | 
| INVESTOR | 
| REVIEWER

Perceba que o admin tem as permissions no plural então não precisa checar se ele tem permissão pra editar um usuário em específico ou uma tecnologia em específico.

**Comment by nicholasio** [comment]
FYI: essa issue depente de #73

**Comment by alexandreadames** [comment]
@nicholasio, só pra confirmar. Para o usuário atualizar o próprio perfil não seria uma rota dedicada, mas tipo, seria algo assim:
Route.put('/users/:id', 'UserController.update').middleware(['auth','permission:update-users, update-user']);
E dentro do middleware Permission se a permissão do usuário passada for 'update-user', fazer a checagem se o id da rota é igual ao id do user logado.

**Comment by alexandreadames** [comment]
Outra coisa, seria necessário incluir permissões para o tipo ADMIN? Acho que não seria necessário visto que esse role tem permissão pra tudo não acha? Inclusive existe implementações de um middleware chamado 'admin' igual ao 'guest':
```
const InvalidAccessException = use("App/Exceptions/InvalidAccessException");

class Admin {
  async handle({ request, auth }, next) {
    const user = await auth.getUser();

    if (!user.role_cd || user.role_cd != "admin")
      throw new InvalidAccessException();

    await next();
  }
}

module.exports = Admin;
```

**Comment by alexandreadames** [comment]
Outro ponto que lembrei agora, pelo que vi no documento de requisitos o DEFAULT_USER não pode criar tecnologias, ex.
| role | permissions
|---|---|
| DEFAULT_USER | update-user, details-technologies, create-technology-review
| ADMIN | update-users, delete-users, create-technologies, update-techonologies etc...
| RESEARCHER | update-user, create-technologies, details-technologies, update-technology, delete-technology, create-technology-review
| INVESTOR | 
| REVIEWER

**Comment by nicholasio** [comment]
> E dentro do middleware Permission se a permissão do usuário passada for 'update-user', fazer a checagem se o id da rota é igual ao id do user logado.

Exato! Assim fica bom, acho que rota específica é redundante.



> Outro ponto que lembrei agora, pelo que vi no documento de requisitos o DEFAULT_USER não pode criar tecnologias, ex.
> 
> role	permissions
> DEFAULT_USER	update-user, details-technologies, create-technology-review
> ADMIN	update-users, delete-users, create-technologies, update-techonologies etc...
> RESEARCHER	update-user, create-technologies, details-technologies, update-technology, delete-technology, create-technology-review
> INVESTOR	
> REVIEWER

Verdade, no caso ele pode criar mas não publicar né? Podemos criar uma permissão específica para publicar tecnologias! `create-tecnologies` seria pra criar tecnologias e deixar como `draft` ou `pending` e  `publish-tecnologies` seria revisores e admin! O que acha?

**Comment by alexandreadames** [comment]
Isso o create-technologies seria a permissão pra criar e deixar draft ou submited. Sendo que o submited seria quando terminasse ou cadastro. Pode ser pending também.
