### ISSUE TITLE
Definir imagem padrão do thumbnail

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#515]
## Feature Description

Atualmente, as imagens são enviadas para a tabela de uploads, mas nenhuma delas é definida como `thumbnail_id`na tabela de tecnologias. Com isso, a informação de thumbnail não é carregada (mesmo quando uma requisição é feita para o backend incluindo o `embed`), impossibilitando de ser exibida nos cards. Essa definição deve ser feita no momento dos uploads. 

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by lcnogueira** [comment]
@nichollasrennah @marcusmota , aqui podemos definir o thumnail_id como sendo a primeira imagem enviada ou permitindo ao usuário escolher. Eu acho que faz ou podemos incluir uma opção para que ele defina qual das imagens deve ser usada como thumbnail ou exibir uma mensagem informando que a primeira imagem será o thumbnail. Any thoughts?

**Comment by nichollasrennah** [comment]
@lcnogueira como não tem como alternar a ordem das imagens, então é melhor ter uma opção para escolher qual imagem é o thumbnail no formulário de cadastro.
