### ISSUE TITLE
Funcionalidade de Perguntas Frequentes da tecnologia

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#531]
## Feature Description

Será criada uma aba nova nos detalhes da tecnologia chamada PERGUNTAS FREQUENTES, no qual os usuários poderão fazer perguntas ao pesquisador responsável pela tecnologia. Terá as seguintes características:

VISÃO DO USUÁRIO
- Apresentar uma lista de perguntas e a resposta abaixo.
- Apresentar um botão FAZER UMA PERGUNTA
- Ao clicar no botão FAZER UMA PERGUNTA levará a um modal com um campo de pergunta (textarea) e o botão enviar
- Ao enviar, o pesquisador responsável recebe a notificação por email da pergunta

VISÃO DO PESQUISADOR
- Na área do pesquisador incluir mais um item de menu chamado PERGUNTAS (incluir um badget com a quantidade de perguntas SEM RESPOSTA)
- No Menu PERGUNTAS apresentar uma lista com a pergunta, a tecnologia vinculada, o usuário que fez a pergunta, o status (SEM RESPOSTA, RESPONDIDO, DESATIVADA), e ações (RESPONDER, DESATIVAR)
- Ao clicar em RESPONDER aparecer um modal com um campo textarea de resposta e o botão PUBLICAR RESPOSTA.
- Ao clicar em PUBLICAR RESPOSTA registrar a resposta e alterar o status para RESPONDIDO e apresentar a mensagem que a resposta que foi publicada com sucesso. 
- Ao clicar em DESATIVAR, alterar o status da pergunta para DESATIVADO e apresentar a mensagem que a pergunta não está mais publicada para os usuários visualizarem.

---------------

## Acceptance criteria

* 
- Qualquer usuário cadastrado e logado poderá fazer uma pergunta
- Qualquer usuário pesquisador responsável pela pergunta poderá registrar uma resposta

## Implementation Brief

*

**Comment by JoaoPauloSMoura** [comment]
![Uploading Captura de Tela 2020-11-01 às 20.07.09.png…]()

**Comment by JoaoPauloSMoura** [comment]
![Captura de Tela 2020-11-01 às 20 09 05](https://user-images.githubusercontent.com/46350848/97817924-1ba22400-1c7e-11eb-9efe-a562000b0630.png)

**Comment by JoaoPauloSMoura** [comment]
![Captura de Tela 2020-11-01 às 20 09 43](https://user-images.githubusercontent.com/46350848/97817943-31174e00-1c7e-11eb-912c-7e8a8c306728.png)

**Comment by nichollasrennah** [comment]
Desse jeito mesmo, @JoaoPauloSMoura !

**Comment by calaca** [comment]
@nichollasrennah @JoaoPauloSMoura o botão "var mais perguntas" na aba "perguntas e respostas" faz o quê?

**Comment by JoaoPauloSMoura** [comment]
A ideia é que não mostre todas as perguntas de uma vez @calaca , pq a gente não sabe o volume que vai ter, o idel seria mostrar as ultimas 5, ou ultimas 10. Então quando houver mais do que essa quantidade, coloca o botão "mostrar mais", e assim ele vai mostrando de 5 em 5 (ou de 10 em 10), entendeu?

**Comment by nichollasrennah** [comment]
@alexandreadames, a Lorena já fez o front, falta apenas o backend. Aí é contigo. Coloquei essa issue para ser a sua próxima.

**Comment by calaca** [comment]
@nichollasrennah reabrindo para finalizar a integração no front.

**Comment by calaca** [comment]
Ligação do front com API impedido por conta de novos ajustes necessários indicados em #693.
