### ISSUE TITLE
Cadastro de organizações

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#532]
## Feature Description

Será muito importante sabermos quais instituições/empresas estão dentro da Plataforma. Para isso precisamos definir melhor um cadastro de instituições/empresas para vincularmos os usuários e tecnologias cadastradas.

- No perfil do usuário tem um campo chamado INSTITUIÇÃO. Alterar esse campo para ORGANIZAÇÕES e com um dropbox com a lista de organizações cadastradas. Caso o usuário não a encontre ele poderá realizar o cadastro, por meio de um botão de CADASTRAR ORGANIZAÇÃO.
- Ao clicar no botão de CADASTRAR ORGANIZAÇÃO aparecer um modal com os seguintes campos:
BUSCAR INSTITUIÇÃO NO GOOGLE MAPS: Apresentar um campo no qual será feita uma busca no google com o registro da organização no google maps. É importante esse campo para encontrarmos o ponto geográfico da instituição.
- NOME:
- SIGLA:
- CNPJ: (chave primária)
- ENDEREÇO: (logradouro, numero)
- BAIRRO:
- CEP: 
- CIDADE
- UF
* todos esses campos são obrigatórios

Pode-se aproveitar a busca do google e já trazer boa parte desses dados para cadastro. Se a organização não for encontrada no Google, solicitar pelo menos o ponto geográfico da organização.

---------------

## Acceptance criteria

1. Criar o esquema `institutions`;
2. Alterar o esquema `users`;
3. Criar as rotas;
4. Criar o model, controller e relashionships;
5. Fazer os testes;
6. Fazer a documentação

Um usuario logado deve ser capaz de criar uma organização, e poderá alterá-la ou deletá-la caso a tenha criado. No cadastro e atualização do usuário deve ser possível associar uma organização.

### Criação de novo esquema (migration): `institutions`, com os campos:

| Campo          | Descrição | Tipo|
|-------------------|---------------|-------|
|name           |Nome da Instituição|String|
|initials |Sigla da instituição  |String|
|cnpj | CPNJ |String|
|address| Endereço|String(Text)
|district | Bairro|String
|zipcode | CEP|String
|city | Cidade|String
|state | UF|String
|lat|Latitude|String
|lng|Longitude|String

### Alterar o esquema (migration) `users`
Incluir no esquema de usuários o campo `institution_id` como chave estrangeira para a tabela `institution` (A priore o usuário só pode ter uma instituição).

### Rotas

| Método | Rota |Body | Auth|
|------------|--------|-------|-------|
|GET     |institutions|N/A|Qualquer usuário logado|
|GET     |institutions/:id|N/A|Qualquer usuário logado|
|POST   |institutions|N/A|Qualquer usuário logado|
|PUT     |institutions/:id|N/A|Permissions: UPDATE_INSTITUTION* ou UPDATE_INSTITUTIONS|
|DELETE     |institutions/:id|N/A|Permissions: DELETE_INSTITUTION* ou DELETE_INSTITUTIONS|

Alterar a rota de criação do usuário (store) e atualização (update) para receber um `institution_id` e associar ao usuário.

*Apenas o usuário que criou a instituição, checar permissão no model Permission.js

### Model e Controller

Criar o model `Institution` e o controller `InstitutionController`, no controller implementar os métodos index, show, store, update e destroy conforme as rotas.

### Relashionships

No model `User` criar o relashionship `institution()` do tipo `belongsTo`
No model `Institution` criar o relashionship `users()` do tipo `hasMany`

### Testes
Fazer os testes de CRUD obrigatórios
Fazer os testes de associação com usuários

### Documentação
Documentar a API conforme as regras do APIDoc.js

**Comment by alexandreadames** [comment]
@nichollasrennah um usuário pode ter várias organizações?
