### ISSUE TITLE
Funcionalidades Banco de Idéias

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#537]
## Feature Description

O banco de ideias é uma funcionalidade disponível para todos os usuários registrarem suas demandas de pesquisas e tecnologias. Vai ser a oportunidade para aqueles que não encontraram a tecnologia que buscam e sugerir que os pesquisadores desenvolvam de acordo com a demanda da sociedade.

O banco de ideias será composto por:

**1 - Lista corrida de oportunidades cadastradas pelos usuários**
- Uma pequena descrição abaixo do título da página:
_Não encontrou o que desejava?
Aqui você pode sugerir novas ideias de desenvolvimento de pesquisa e tecnologia de acordo com sua necessidade e para resolver problemas comuns do nosso povo. Veja abaixo as ideias já sugeridas pelos nossos usuários e registre a sua também._

- Lista simples composta pelo seguinte conteúdo
  - Título da ideia (texto)
  - Detalhe da ideia (textarea)
  - Palavras-chave
  - Usuário que sugeriu a ideia
  - Data do registro
- Incluir opções para filtrar a lista por texto do título e descrição e por palavra-chave
- Essa lista será acessar por meio do menu principal da Plataforma (estamos definindo esse menu ainda)

**2 - Cadastrar uma ideia**
- Somente usuários cadastrados podem registrar uma ideia
- Quando clicar em REGISTRAR UMA IDEIA aparecer uma tela com os seguintes campos:
- TÍTULO DA IDEIA
- DESCRIÇÃO DA IDEIA (textarea): 
- PALAVRAS-CHAVE (o mesmo do cadastro de tecnologias)
- botão ENVIAR IDEIA
 
**3 - Lista de Ideias para os usuários pesquisadores**
- Na área do pesquisador incluir um item no menu chamado BANCO DE IDEIAS
- Apresentar os seguintes campos na tabela:
  - Título
  - Usuário
  - Data
  - Palavras-chave
- Incluir opções para filtrar a lista por texto do título e descrição e por palavra-chave
- Incluir um ícone de detalhes que apresenta um modal com a descrição da ideia

---------------

## Acceptance criteria

* 
- Somente usuários logados e cadastrados poderão registrar novas ideias.

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
@JoaoPauloSMoura vamos correr com essa para podermos começar no projeto mobile

**Comment by JoaoPauloSMoura** [comment]
Preciso entender melhor Nichollas, um usuário comum pode cadastrar e visualizar a lista de ideias, mas o pesquisador também poderá acessar essa lista pelo dashboard?

**Comment by nichollasrennah** [comment]
Exato. Será uma funcionalidade que qualquer usuário pode cadastrar. Essa
lista de ideias será util para os pesquisadores. Por isso que iremos
disponibilizar a lista na área do pesquisador. Mas também a sociedade pode
ver quais as ideias já cadastradas tb. Nesse caso a listas dessas ideias tb
estarão públicas.

Em qua, 25 de nov de 2020 20:41, João Paulo Moura <notifications@github.com>
escreveu:

**Comment by JoaoPauloSMoura** [comment]
![image](https://user-images.githubusercontent.com/46350848/100563535-6030d780-329d-11eb-87fc-896cae6462a7.png)

**Comment by calaca** [comment]
Reabrindo pra seguir como issue base do front.

**Comment by calaca** [comment]
@nichollasrennah só deixando aqui que no momento estou aguardando o design responsivo da tela.

**Comment by JoaoPauloSMoura** [comment]
feito! @calaca

**Comment by calaca** [comment]
@nichollasrennah preciso que a issue de ajuste dos footer seja aprovada pra seguir com essa daqui, pois essa página usa os mesmos itens de footer e header (que tb ajustei). Além disso, vou precisar fazer ajustes em cima desses itens pra essa issue também.
