### ISSUE TITLE
CRUD Revisões de Tecnologia

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#54]
## Feature Description

CRUD de revisões de tecnologias.

---------------

## Acceptance criteria

* Usuários logados podem criar reviews de tecnologias.
* Somente admins podem remover reviews.
* Usuário que criou a review pode alterá-la.

## Implementation Brief

**Rotas**
|   método | rota  |  query/body params  |   auth |
|---|---|---|---|
|  POST | /techonology/:id/review    | user_id, content, rating(inteiro entre 0 e 5), *positive (deve ser armazenado como um json), *negative (deve ser armazenado como um json)  |   **Yes** - qualquer usuário
|  GET    |   /technology/:id/reviews  | NA  |   **No**
|  PUT    |   /techonology/:id/review/:reviewId | Mesmo que `POST /techonology/:id/review ` porém sem aceitar alterar o `user_id`  | **Yes** - Admin ou o próprio autor da review   
|  DELETE | /techonology/:id/review/:reviewId | NA |   **Yes** - admin

*postive/negative - lista de pontos positivo e negativos.

**Migrations/seeds**
- Criar a migration `technology_review` que deve estar associada a tecnologia.
- Criar seeds com fake data (só para testes).

**Testes**
- Implementar testes cobrindo todas as rotas.

**Outros**
- Incluir as revisões automaticamente ao listar tecnologias caso o `embed` esteja presente na URL (Atualizar o `withParams` query macro`)

**Comment by nicholasio** [comment]
@alexandreadames essa aqui está pronto alexandre. Caso queira fique a vontade para complementar o IB ou se tiver alguma outra sugestão.

**Comment by alexandreadames** [comment]
👍

**Comment by alexandreadames** [comment]
@nicholasio sugiro uma pequena alteração:
PUT /reviews/:id
DELETE /reviews/:id
No caso do PUT e DELETE não precisa do id da tecnologia, o id do review é único

**Comment by nicholasio** [comment]
@alexandreadames tem razão 👍
