### ISSUE TITLE
Implementar Sistema de Taxonomias de Tecnologia.

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#55]
## Feature Description

Implementar o sistema de taxonomias. 

**Implementções a serem feitas:**

- CRUD de Taxonomias
- CRUD de Termos com suas respectivas taxonomias
- Associar um Termo a uma Tecnologia
- Desassociar um Termo de uma Tecnologia
- Listar os Termos de uma dada Tecnologia por Taxonomia
- Criação das Migrations
- Criação dos Seeds

### Seed das Taxonomias:
Lista Numerada -> Taxonomia
Lista Secundária -> Termos padrão

#### Taxonomias da entidade Tecnologia

1. Keywords
2. Classification
   * Avanços tecnológicos
   * Tecnologias Sociais
   * Inovações sociais
3. Stage
   * Tecnologia em operação
   * Colocação da tecnologia em operação
   * Demonstração da tecnologia
4. Dimension
   * Ambiental
   * Social
   * Econômica
   * Cultural
   * Política
5. Category e SubCategory
    * Lista de Categorias e Subcategorias definidas no [Mapa Mental](https://www.mindmeister.com/1428163905)
6. TargetAudience
   * Agricultores
   * Empresários
   * Estudantes
   * Prefeituras
   * ...
7. FinancingTypes
   * Público
   * Privado
   * Crowdfunding

#### Taxonomias da entidade de custos

1. CostType
   * Serviço
   * Material
   * Equipamento
   * Pessoal
   * Insumos
2. CostDefinition
   * Desenvolvimento
   * Implantação
   * Manutenção

#### Taxonomias da entidade Georeferenciamento

1. GeoreferencingType
   * Desenvolvida
   * Aplicada
   * Implantada

#### Taxonomias da entidade Anexo

1. AttachmentType
   * Imagem
   * Vídeo
   * Diagrama
   * Documento

#### Taxonomias da entidade Contato

1. ContactType
   * Assistência técnica
   *  Instituição desenvolvedora
   * Desenvolvedor
2. Degree
   * Especialista em análise de solo
   * Técnico em perfuração de poços
   * ...

---------------

## Acceptance criteria

Passar em todos os testes:

1. Testes do CRUD de Taxonomia
2. Testes das rotas de Termos
3. Testes das rotas de Tecnologia

### Criação de Migrations segundo esse modelo:

![Taxonomy system model](https://user-images.githubusercontent.com/13112022/80811644-b3726880-8b9c-11ea-94e2-473274c6b523.png)

### Seeds

   1. TaxonomySeeder => Criar todas as taxonomias
   2. TermSeeder => Criar todos os termos e associar as taxonomias
   No caso da taxonomia `Category` criar as subcategorias especificando o `parent_id`

### Relacionamentos nos Models:

   ```javascript
   Taxonomy hasMany Terms
   Terms belongsTo Taxonomy
   Terms hasOne Terms
   Terms belongsTo Terms
   Technologies belongsToMany Terms
   Terms belongsToMany Technologies
   ```
#### Rotas de Terms:

```javascript
POST /terms
Body: term, taxonomy, parent_id (opcional)
```

Ao tentar criar um novo termo, checar se a taxonomia está cadastrada;
Se o parent_id for enviado, criar um novo termo com esse parent_id;

```javascript
GET /terms
Queryparam: ?taxonomy=<taxnomy>
```
O query param taxonomy irá limitar a listagem de termos por taxonomia

```javascript
GET /terms
Queryparam: ?taxonomy=<taxnomy>&parent_id=<parent_id>
```

O query param parent_id irá listar todos os terms que pertencem a esse parent

```javascript
PUT /terms/:id
Body: term, taxonomy (opcional)
 ```
Se for enviado a taxonomia, atualizar o termo para uma nova taxonomia

```javascript
DELETE /terms/:id
```
#### Rotas de Technologies:
   
 ```javascript
POST /technology_terms
Body: term_id, technology_id
 ```
Associa um termo a uma tecnologia
 
```javascript
GET /technology_terms/:technology_id
Queryparam: ?taxonomy=<taxnomy>
```
Lista todos os termos da tecnologia por taxonomia

**Comment by nicholasio** [comment]
@alexandreadames você pode descrever essa issua já que você já fez o modelo e tudo mais?

**Comment by alexandreadames** [comment]
Pode deixar, vou fazer.

**Comment by alexandreadames** [comment]
@nicholasio por favor dê uma olhada e veja se a descrição da issue está boa, eu coloquei tudo que julgo ser relevante.

**Comment by nicholasio** [comment]
@alexandreadames Muito bom, eu só acho que não precisamos da rota `technology_terms`, por simplicidate eu acho que a rota `PUT/POST /technologies` pode aceitar receber um term_id e taxonomy_id e fazer a associação.

Da mesma forma `GET /technologies` pode receber um `term_id` para que você liste todas as taxonomias que pertecem a um termo específico.

**Comment by nicholasio** [comment]
Também está faltando uma rota `/taxonomy`para que também seja possível criar taxonomias que não estejam pré-cadastradas no banco no futuro! Nessa rota podemos criar uma roda no seguinte padrão `/taxonomy/:id/terms` para retornar os termos da taxonomia!

**Comment by alexandreadames** [comment]
@nicholasio eu coloquei esse último comentário nesse ponto:
CRUD de Taxonomy => Crud Simples
Eu posso incluir nessa seção

**Comment by nicholasio** [comment]
@alexandreadames Ah sim entendi, seria bom colocar só para esclarecer.
👍

**Comment by alexandreadames** [comment]
Essa rota `/taxonomy/:id/terms`:  implementada por 

```javascript
GET /terms
Queryparam: ?taxonomy=<taxnomy>
```

**Comment by alexandreadames** [comment]
Tarefas efetuadas:

- [x] Criação de Migrations;
- [x] Criação de Models e Relashionships;
- [x] Seed de Taxonomy e Terms;
- [ ] Criação de Rotas;
- [ ] Testes;
