### ISSUE TITLE
Refatorar Seeds

### ISSUE THREAD

**Issue by NaylsonFerreira** [ufersa/plataforma-sabia#553]
## Feature Description

Deixar de usar tecnologias, palavras chave e usuários fakes em staging e produção.

## Acceptance criteria

* Os dados fakes não devem está presentes nos ambientes de staging e produção.
* Os dados fakes devem estar disponíveis em ambiente de desenvolvimento.

## Implementation Brief

*

**Comment by marcusmota** [comment]
Só para complementar, precisamos ter um seed em staging / produção com os dados mínimos para aplicação funcionar exemplo: taxonomias, já em dev pode ser tudo 👍

**Comment by alexandreadames** [comment]
@NaylsonFerreira e @marcusmota, já existe um comando chamado `seed:default` que popula o banco apenas com os dados mínimos que pode ser usado em staging e produção. Acredito que a única coisa que falta é criar um admin padrão.
