### ISSUE TITLE
Ajustar DELETE de um upload quando existir relacionamento na tabela technologies

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#557]
## Feature Description

Atualmente não consigo enviar um `DELETE` para um upload que tenha relacionamento na tabela de tecnologia, especificamente falando sobre o `thumbnail_id`

Quando tento excluir um upload que seja thumbnail ocorre o erro abaixo:

![image](https://user-images.githubusercontent.com/13091635/97220382-28200b80-17aa-11eb-9a9a-515a9c16f436.png)

---------------

## Acceptance criteria

*Conseguir excluir um upload que tenha relacionamento na tabela de tecnologias

**Comment by nichollasrennah** [comment]
Como está essa issue, @mateus4k ?

**Comment by mateus4k** [comment]
Parada devido outras prioridades. Voltarei com ela agora.
