### ISSUE TITLE
Move mail sending to background jobs

### ISSUE THREAD

**Issue by mateus4k** [ufersa/plataforma-sabia#560]
## Feature Description

In our API package, we have [some cases](https://github.com/ufersa/plataforma-sabia/search?q=Mail.send&type=code) where we send mails synchronously, blocking the endpoint while the mail is being sent and, consequently, slowing down our application.

The resolution is move these cases to a `background job`, as described in [that suggestion](https://github.com/ufersa/plataforma-sabia/pull/540#discussion_r511894214).

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
@mateus4k essa issue era pra ter sido fechada?

**Comment by mateus4k** [comment]
Não. Todos os emails ainda estão sendo enviados da maneira antiga exceto o de fale conosco.
