### ISSUE TITLE
Implementar rota para a funcionalidade Fale Conosco

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#568]
## Feature Description

Implementar a API para a funcionalidade Fale Conosco.

A parte relativa ao frontend está pronta na PR #567 

---------------

## Acceptance criteria

* Qualquer usuário pode enviar uma mensagem ao Fale Conosco
* Não precisa ficar armazenada no banco essas mensagens. Toda a troca de conversa será por meio do email.
* Usuário e admin (plataformasabia@ufersa.edu.br) recebem email de confirmação
* Ao enviar apresentar mensagem de confirmação de envio

**Comment by nichollasrennah** [comment]
Como esta essa implementação @mateus4k ?

**Comment by nichollasrennah** [comment]
Essa issue passou a ser urgente, pois precisamos dela funcionando para que os usuários consigam dar o feedback!

**Comment by mateus4k** [comment]
Ainda não comecei pois estou finalizando a #532. Deixo ela de lado um pouco pra trabalhar nessa?
