### ISSUE TITLE
Ajustes na API de tecnologias

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#581]
## Feature Description

- Incluir os seguintes campos relacionados aos custos da tecnologia:
  - Essa tecnologia é vendida por você? (Sim, Não) * obrigatório*
  - Qual o preço de venda dessa tecnologia? (Campo monetário) *obrigatório se o campo anterior for sim*

Esse campo vai ser muito importante para separarmos as tecnologias que estarão disponíveis na plataforma, tem custo de implantação, mas não está à venda. Está publicada apenas para ensinar como construir a tecnologia. É o caso de tecnologias sociais, como uma cacimba por exemplo. Elas existem e os usuários poderão fazer com meios próprios. Geralmente elas não são vendidas, mas não deixa de ter custo de implantação. Esse campo vai ser decisivo para habilitarmos ou não o botão de ADQUIRIR TECNOLOGIA.

- Inserir um campo a mais em cada registro dos custos de DESENVOLVIMENTO, IMPLANTAÇÃO e MANUTENÇÃO. O nome do campo será: Unidade de Medida. Esse campo pode ser uma taxonomia nova (Und, m, h, g, kg, km, cm, outro). Essas taxonomias serão cadastradas no admin.

Esse campo é importante para não ficar confuso no cadastro de itens, pois muitos são inseridos sem saber qual unidade de medida da quantidade informada.
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by alexandreadames** [comment]
> * Inserir um campo a mais em cada registro dos custos de DESENVOLVIMENTO, IMPLANTAÇÃO e MANUTENÇÃO. O nome do campo será: Unidade de Medida. Esse campo pode ser uma taxonomia nova (Und, m, h, g, kg, km, cm, outro). Essas taxonomias serão cadastradas no admin.
 
@nichollasrennah acredito que não seja interessante criar uma taxonomia para se referir a unidade de medida. Na minha opnião é melhor o pessoal do front criar uma lista transiente de unidades de medidas conhecidas e armazenar no banco como um campo string. Acredito que dificilmente irá surgir uma unidade de medida nova que precise de uma gerência de cadastro.

**Comment by nichollasrennah** [comment]
Verdade Alexandre. Mantenha então dessa forma que você sugeriu.

Em seg, 2 de nov de 2020 13:30, Alexandre Ádames <notifications@github.com>
escreveu:
