### ISSUE TITLE
Ajustes na tela de cadastro de tecnologias

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#582]
## Feature Description

**ALTERAÇÕES GERAIS**
1) Inserir um espaço abaixo do cabeçalho com a timeline do formulário, a descrição de cada etapa (aba) com os seguintes textos em cada aba:
SOBRE A TECNOLOGIA: O cadastro de tecnologias compreende 6 passos. Na primeira etapa você irá informar os metadados de categorização da tecnologia. A cada tela que você avança, automaticamente os dados serão salvos. 
Você poderá voltar a qualquer momento e continuar o cadastro da etapa onde parou. Poderá também clicar no botão voltar para ir para as etapas anteriores.
CARACTERIZAÇÃO: Essa etapa você irá informar dados textuais da plataforma. Procure dar clareza e objetividade no conteúdo para deixar a leitura mais agradável possível por parte dos usuários.
CUSTOS E FINANCIAMENTO: Essa etapa é opcional, mas muito importante para informar os custos relativos a tecnologia, desde o desenvolvimento (para as tecnologias que ainda estão sendo criadas) ao custo de implantação e manutenção. 
O financiamento é para os inventores que desejam recursos para desenvolver suas tecnologias e necessitam de financiamento. Parceiros poderão entrar em contato para oferecer as melhores opções de financiamento.
RESPONSÁVEIS: Informe todos responsáveis pela criação da tecnologia. São as pessoas que irão responder pelo cadastro. A primeira pessoa do cadastro é a que irá ser o contato principal na plataforma para esse cadastro.
MAPAS E ANEXOS: Etapa muito importante para conhecermos os locais que a tecnologia é desenvolvida, pode ser utilizada e onde ela já foi implantada. Essa busca é realizada no Google Maps, portanto, poderá procurar por empresas, instituições ou cidades. 
Em anexos você poderá informar fotos, links para vídeos no Youtube e documentos em PDF (cartilha, manual etc). Esses arquivos anexos não poderão ultrapassar 4MB de tamanho.
REVISÃO: Confira todos os dados cadastrados. Se necessitar alterar, basta voltar e alterar os dados. Se estiver tudo certo marque os termos da política de privacidade e clique no botão CONCLUIR.

2) Inserir um campo dos comentários do curador. Esse campo fica disponível apenas no processo de análise de revisão do curador e correção do cadastrador. 
3) Nos campos do tipo textarea, inserir um contador de caracteres com no máximo 1000 caracteres e informar ao usuário quantos restam. 
4) Colocar links para cada passo da timeline superior... para evitar ir para uma etapa específica e ter que ir voltando item a item.

**ALTERAÇÕES NA ABA CARACTERIZAÇÃO**
- No campo "Duração do processo de instalação da tecnologia" trocar a label por "Duração do processo de instalação da tecnologia (em dias)"

**ALTERAÇÕES NA ABA CUSTOS E FINANCIAMENTO**
- Inserir a seguinte estrutura de novos campos: 
  - Essa tecnologia é vendida por você? (Sim, Não)
  - Qual o preço de venda dessa tecnologia? Campo monetário
- Inserir um cabeçalho com os nomes dos campos dos custos. Só existe a descrição dos campos no placeholder do campo, impossibilitando saber a descrição do campo quando este estiver com dados preenchidos.
- Inserir um campo a mais em cada registro dos custos chamado: Unidade de Medida. Esse campo pode ser uma taxonomia nova (Und, m, h, g, kg, km, cm, outro). Essas taxonomias serão cadastradas no admin
Obs: Foi aberto uma nova issue #581  para tratar esses novos campos na API.

**ALTERAÇÕES NA ABA RESPONSÁVEIS**
- Inserir ao lado do campo ID Lattes um ícone para um infobox informando o seguinte:
- O ID Lattes poderá ser obtido na Plataforma Lates (informar o link abrindo em uma nova aba) nessa parte do currículo: 
![ID_lattes](https://user-images.githubusercontent.com/48101231/97723584-b6e2a000-1aaa-11eb-9a21-6dd410c21cac.jpg)

**ALTERAÇÕES NA ABA RESUMO**
- Refletir os itens alterados nas abas anteriores (novos campos dos custos).
- Abrir links da política de privacidade e termos e condições de uso em uma nova aba
- Inserir campo de comentário com a seguinte label: "Faça aqui os comentário para o Avaliador. Informe as dificuldades e antecipe as possíveis dúvidas sobre seu cadastro" 
- Ao clicar no botão CONCLUIR aparecer a seguinte mensagem: Sua tecnologia foi cadastrada com sucesso e enviada para análise da equipe de curadores. Você será redirecionado para as suas tecnologias para acompanhar o processo de revisão.
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by calaca** [comment]
@nichollasrennah pode falar mais sobre o item 2 das alterações gerais, por favor? Não entendi bem como é esse comentário.

**Comment by nichollasrennah** [comment]
@calaca na realidade não é um campo, mas um dado que vem do curador no processo de correções do cadastro. São as orientações do curador que precisam ser refeitas pelo cadastrador. O @JoaoPauloSMoura desenhou esse trecho hoje no final. João, você pode colocar a tela aqui?

**Comment by nichollasrennah** [comment]
![Cadastro Tecnologias - 1](https://user-images.githubusercontent.com/48101231/98474696-2f94db00-21d4-11eb-92a5-a940dfb06e60.png)

Será esse bloco que ficará aparecendo em todas as abas, localizado acima dos botões inferiores (Ele pode ficar em toda a largura da página, caso fique estranho somente em um lado da tela). Esse bloco só aparece no processo de edição da tecnologia quando o status for REQUEST CHANGES

**Comment by JoaoPauloSMoura** [comment]
Isso mesmo, @calaca qualquer dúvida pode me chamar no Slack

**Comment by nichollasrennah** [comment]
@calaca com relação a esse item: _"Inserir um campo a mais em cada registro dos custos chamado: Unidade de Medida. Esse campo pode ser uma taxonomia nova (Und, m, h, g, kg, km, cm, outro). Essas taxonomias serão cadastradas no admin"_
Alexandre falou que essa lista de possíveis unidades de medida poderão ser listadas somente no frontend, sem precisar cadastrá-lo como taxonomia no banco. Dessa forma, procurei uma lista melhor de unidades de medidas mais utilizadas. Aqui está:
- und - Unidade
- cx - Caixa
- pc - Pacote
- sc - Saco
- mil - Milheiro
- mm - Milímetro
- cm - Centímetro
- m - Metro
- km - Quilômetro
- pol - Polegada
- mg - Miligrama
- g - Grama
- kg - Quilograma
- ml - Mililitro
- l - Litro
- gl - Galão
- lt - Latão
- m² - Metro Quadrado
- m³ - Metro cúbico
- km² - Quilômetro quadrado
- km³ - Quilômetro cúbico
- ha - Hectare
- mes - Mês
- dia - dia
- h - hora
- min - Minuto
- outro - Outro

**Comment by nichollasrennah** [comment]
> ![Cadastro Tecnologias - 1](https://user-images.githubusercontent.com/48101231/98474696-2f94db00-21d4-11eb-92a5-a940dfb06e60.png)
> 
> Será esse bloco COMENTÁRIOS DO CURADOR que ficará aparecendo em todas as abas, localizado acima dos botões inferiores (Ele pode ficar em toda a largura da página, caso fique estranho somente em um lado da tela). Esse bloco só aparece no processo de edição da tecnologia quando o status for REQUEST CHANGES

@calaca Por favor, dispense esse item 2 do comentário do curador. Porque o Luiz Felicio já implementou na PR dele.
