### ISSUE TITLE
Desabilitar envio de emails quando o APP_ENV=testing

### ISSUE THREAD

**Issue by marcusmota** [ufersa/plataforma-sabia#586]
## Feature Description

Precisamos fazer um wrap do `use('Mail');` para não enviar email quando `APP_ENV=test` para evitar disparar errors ao rodar os testes na API

---------------

## Acceptance criteria

Rodar os testes e não vê errors do tipo 

![Screenshot 2020-10-31 at 18 16 13](https://user-images.githubusercontent.com/8526488/97786681-305eb900-1ba5-11eb-8915-93a91ea09396.png)

**Comment by mateus4k** [comment]
Basta seguir o que fiz aqui pro Bull: https://github.com/ufersa/plataforma-sabia/pull/601/files
