### ISSUE TITLE
Criar páginas informacionais da Plataforma

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#604]
## Feature Description

O Menu superior terá a seguinte estrutura:
PLATAFORMA
FUNCIONALIDADES
RECURSOS
CONTATO

Todo o conteúdo dessas páginas precisam ser modeladas para que fiquem visualmente bem apresentadas.
Os sites que queremos usar como referência são:

- [LINKAPI](https://www.linkapi.solutions/?gclid=CjwKCAjwlbr8BRA0EiwAnt4MTvQOUznXsEdS6j61tm8eh9z9MjMpD_G3Lblpz1f-aZuJlNbz4DirphoCOfIQAvD_BwE)
- [99](https://99app.com/)
- [LINX](https://www.linx.com.br/linx-commerce/?utm_source=google&utm_medium=cpc&utm_campaign=commerce_fundo&gclid=Cj0KCQjw59n8BRD2ARIsAAmgPmJ7y_kWDCUbbfF7_6FvWtxZ7cBCqjH5wR7Vbeuz97CDJAoDIfqHUj4aAvOiEALw_wcB)
- [DOITY](https://doity.com.br/?utm_source=google&utm_medium=cpc&utm_campaign=go-pesquisa_111&gclid=Cj0KCQjw59n8BRD2ARIsAAmgPmKXqY6qBCdf392sFxUYSxAs-80087vCNzY-No3lBwrMB7-uLydPMsMaAkQmEALw_wcB)

O conteúdo dessas páginas poderá ser acessado aqui: https://docs.google.com/presentation/d/1eU0bOH2HhYrD1qoiKyLJV76fXi0Llb_iEuZtyxv8bTk/edit?usp=sharing

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by calaca** [comment]
@JoaoPauloSMoura pode ir liberando aqui o que já estiver pronto, por favor? :grin:

**Comment by JoaoPauloSMoura** [comment]
Opa, @calaca o projeto está no figma, no painel esquerdo tu pode navegar até ele, está com o nome "landing page"

**Comment by nichollasrennah** [comment]
@calaca o material no Figma está pronto para ser usado. As logomarcas dos parceiros enviarei por email e alguns prints das funcionalidades seria interessante gerar pelo próprio figma @JoaoPauloSMoura .

**Comment by calaca** [comment]
@nichollasrennah não vai ter design do mobile?

**Comment by JoaoPauloSMoura** [comment]
Terá sim @calaca , a gente precisa só bater o martelo nas imagens mas eu já irei começar o design da versão mobile 😊

**Comment by calaca** [comment]
@nichollasrennah acho melhor eu esperar o design mobile então, pra evitar retrabalho.

**Comment by nichollasrennah** [comment]
No foot insira links para as seguintes redes sociais:
- Instagram: https://www.instagram.com/plataformasabia
- Facebook: https://www.facebook.com/plataformasabiaufersa
- Twitter: https://twitter.com/plataformasabia
- Linkedin: https://www.linkedin.com/in/plataformasabia
