### ISSUE TITLE
Curador não pode avaliar suas próprias tecnologias

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#606]
## Feature Description

Alterar regra de negócio para que na distribuição das tecnologias. O curador não pode avaliar cadastros de tecnologias sob sua responsabilidade.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by alexandreadames** [comment]
@nichollasrennah essa proibição é apenas para o dono da tecnologia? Ou qualquer usuário diretamente relacionado a ela?

**Comment by nichollasrennah** [comment]
Qualquer usuário relacionado a ela.

Em qui, 5 de nov de 2020 20:51, Alexandre Ádames <notifications@github.com>
escreveu:
