### ISSUE TITLE
Criar página de Estamos em manutenção

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#608]
## Feature Description

Criar página HTML coma mensagem que estamos em manutenção para evitar enviar para uma página 404.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by JoaoPauloSMoura** [comment]
![Captura de Tela 2020-11-10 às 20 29 46](https://user-images.githubusercontent.com/46350848/98746061-7bda4980-2393-11eb-98ef-89382620138d.png)

**Comment by JoaoPauloSMoura** [comment]
@nichollasrennah ficou legal?

**Comment by nichollasrennah** [comment]
Ficou ótimo.

Em ter, 10 de nov de 2020 20:30, João Paulo Moura <notifications@github.com>
escreveu:
