### ISSUE TITLE
Include comments field in technology register form: review step

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#613]
## Feature Description

Researchers will use this field to send comments to the reviewer. We also need to include a checkbox, so researcher can send technology to the reviewer or not, when updating it.

---------------

## Acceptance criteria

* Researcher is able to send a comment to the reviewer through last form step.
* Researcher is able to choose between sending technology to reviewer or not.

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
![modal-correção](https://user-images.githubusercontent.com/48101231/98478556-a9799400-21d5-11eb-9125-a52528e84e51.png)

![Cadastro Tecnologias - RESUMO](https://user-images.githubusercontent.com/48101231/98478615-ae3e4800-21d5-11eb-8bf8-806ddc04527e.png)
