### ISSUE TITLE
Permitir criar e alterar o parent_id de um termo

### ISSUE THREAD

**Issue by NaylsonFerreira** [ufersa/plataforma-sabia#614]
Permitir a inclusão de um parent_id no momento da criação de um termo e a alteração desse campo posteriormente.

---------------

## Acceptance criteria

* É possível alterar o parent_id de um termo no ADMIN
* É possível criar um termo com parent_id no ADMIN
* A documentação da API foi atualizada

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
@NaylsonFerreira esse item passou a se tornar urgente pois temos termos para cadastrar e não tenho como.

**Comment by NaylsonFerreira** [comment]
Vou tentar fazer agora!
