### ISSUE TITLE
Situações de edição de cadastro de tecnologias

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#623]
## Feature Description

- As tecnologias só podem ser editadas quando estiverem com os seguintes status: DRAFT, REQUEST CHANGES ou PUBLISHED
- Quando tentar editar em outros status aparecer a seguinte mensagem: "Esse cadastro está em processo de avaliação. Aguarde o parecer do curador para realizar as alterações desejadas."

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by luizeboli** [comment]
@nichollasrennah quando o curador aprova a tecnologia, esta vai pro status `APPROVED`.

Nessa etapa o curador já avaliou, mas o admin ainda não publicou a tecnologia. Faz sentido exibir a mensagem de que está pendente de avaliação pelo curador?

**Comment by nichollasrennah** [comment]
Sim. Mantém a mensagem pq de certa forma o administrador vai homologar ou
não o trabalho do curador. Pra saber se foi tudo certo.


Em qua, 11 de nov de 2020 09:09, Luiz Felicio <notifications@github.com>
escreveu:
