### ISSUE TITLE
Minhas tecnologias em área do usuário não traz nenhuma tecnologia cadastrada

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#665]
Esse problema ocorreu depois da mudança da API para trazer para a área de busca somente tecnologias publicadas. Acontece que precisa continuar trazendo para a área do usuário suas tecnologias cadastradas independente do status. 

![image](https://user-images.githubusercontent.com/48101231/99885995-e3a45600-2c17-11eb-8fb0-f375c4d2b1ea.png)

**Comment by alexandreadames** [comment]
@nichollasrennah esse problema ainda está ocorrendo? Trabalhamos em uma solução para um problema relacionado.

**Comment by nichollasrennah** [comment]
Não. Ja foi corrigida. Pode excluir essa issue.

Em qua, 25 de nov de 2020 20:09, Alexandre Ádames <notifications@github.com>
escreveu:
