### ISSUE TITLE
Permitir atribuir manualmente um curador para uma tecnologia

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#672]
## Feature Description

Hoje a distribuição dos curadores dos cadastros de tecnologias ocorre de forma automatizada. Para que não ocorra gargalos no processo é preciso permitir que o ADMIN possa fazer a designação do curador de forma manual também.
- Essa funcionalidade pode ficar no item TECNOLOGIAS no ambiente ADMIN.
- Pode designar qualquer usuário com o papel de REVIEWER
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by alexandreadames** [comment]
@nichollasrennah algumas observações sobre esse processo:
1. Mesmo sendo uma atribuição manual é necessário que o usuário solicite a curadoria;
2. Na hora de atribuir manualmente o curador é recomendado que o ADMIN só atribua uma tecnologia a um curador que tenha sua área de atuação (na hora de atribuir o sistema deve não permitir caso o ADMIN tente atribuir o curador a uma tecnologia fora de sua área)
