### ISSUE TITLE
Sessão repetida no footer

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#674]
## Feature Description

A sessão `Localizações` está duplicada no footer

![image](https://user-images.githubusercontent.com/13091635/100387454-e7b0e900-3006-11eb-8cdf-8634946d28ae.png)

---------------

**Comment by nichollasrennah** [comment]
@luizeboli , essa parte do footer está sendo redesenhado. Os itens serão outros.
Iremos atualizar depois que @calaca terminar a parte informacional, pois alguns links apontarão para lá.

Ficará dessa forma:
![image](https://user-images.githubusercontent.com/48101231/100387715-83daf000-3007-11eb-9820-5e249fc8e465.png)

**Comment by luizeboli** [comment]
Tranquilo @nichollasrennah, obrigado!

Vou encerrar essa issue então e podemos corrigir posteriormente 🎉
