### ISSUE TITLE
Funcionalidade de Banco de Editais

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#687]
## Feature Description

Do mesmo molde do Banco de Ideias o banco de editais será possível visualizar os variados editais que são publicados por meio de outras instituições. Queremos dar a oportunidade para os nossos usuários fiquem sabendo quais editais vigentes eles podem consultar e participar.

Essa funcionalidade terá:

**1 - LISTA DE EDITAIS**
- Listar todos os editais cadastrados em formato de card (similar ao banco de ideias)
- O conteúdo dessa lista será:
   - Organização: 
   - Número do Edital: 
   - Título: 
   - Descritivo: 
   - Público-Alvo: 
   - Palavras-chave:
   - Recursos financeiros: 
   - Período de inscrição:
   - Observação:
   - Link para a Página do edital: (abrir em uma nova janela)

- Somente serão publicos os registros com status PUBLISHED
- Mesmo o edital com data expirada continua visível nessa lista 

**2 - REGISTRAR UM EDITAL**
- Qualquer usuário cadastrado poderá registrar um edital.
- Os campos serão:
   - Organização (Dropdown): 
   - Número do Edital: (campo texto)
   - Título: (campo texto)
   - Descritivo: (textarea)
   - Público-Alvo: (Lista de publico-alvo das taxonomias existentes)
   - Palavras-chave: (Lista de palavras-chave das taxonomias existentes)
   - Recursos financeiros: (Opcional) - campo de valor monetário
   - Período de inscrição: (data de inicio e data de fim)
   - Observação: (textarea)
   - Link para a Página do edital: (URL)

- Ao cadastrar o registro terá um status de pendente 
- Somente o ADMIN muda o status para PUBLISHED
- O ADMIN poderá cancelar o registro.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by alexandreadames** [comment]
@nichollasrennah a organização do cadastro é a mesma que foi criada aqui: https://github.com/ufersa/plataforma-sabia/issues/532

**Comment by nichollasrennah** [comment]
É sim.

Em ter, 1 de dez de 2020 19:50, Alexandre Ádames <notifications@github.com>
escreveu:
