### ISSUE TITLE
Validators e testes no CRUD Papel e Permissão

### ISSUE THREAD

**Issue by alexandreadames** [ufersa/plataforma-sabia#69]
## Feature Description

1. Implementar os validators para os CRUDs de Papel e Permissão;
2. Implementar os demais testes para esses CRUDS;

---------------

## Acceptance criteria

1. Ao tentar realizar o cadastro de uma Permissão, verificar se os campos obrigatórios estão preenchidos;
Campos obrigatórios: `permission` e `description`
Campo unique: `permission`
2. Ao tentar realizar a atualização validar o campo `permission` se é unique
3. Ao tentar realizar o cadastro de um Papel, verificar se os campos obrigatórios estão preenchidos;
Campos obrigatórios: `role` e `description`
Campo unique: `role`
4. Ao tentar realizar a atualização validar o campo `role` se é unique

## Implementation Brief

1. Criar o validator `StorePermission`, que irá validar se o campos obrigatórios foram preenchidos para a rota: POST /permissions
2. Criar o validator `UpdatePermission` que irá validar se o campo `permission` é unique para a rota PUT /permission/:id
3. Criar o validator `StoreRole`, que irá validar se o campos obrigatórios foram preenchidos para a rota: POST /roles
4. Criar o validator `UpdateRole` que irá validar se o campo `role` é unique  para a rota PUT /role/:id
5. Criar novos testes em `permission.spec.js` e `role.spec.js`

**Comment by nicholasio** [comment]
@alexandreadames Seria interessante especificar aqui quais os campos de `Permission` e `Roles`.

**Comment by alexandreadames** [comment]
Blza @nicholasio, atualizei a descrição, veja se ficou bom.

**Comment by nicholasio** [comment]
IB ✅
