### ISSUE TITLE
Comportamento inesperado ao associar os termos a uma tecnologia

### ISSUE THREAD

**Issue by NaylsonFerreira** [ufersa/plataforma-sabia#698]
## Feature Description

Reproduzir o error...

1 - Resetar banco

2 - Listar termos associados a tecnologia GET /technologies/1/terms
3 - Associar termos PUT /technologies/1 body { "terms": [8,9,10] }
4 - Listar termos associados a tecnologia GET /technologies/1/terms

* Funciona como esperado

5 - Associar termos PUT /technologies/1 body { "terms": [1,2,3] }
6 - Listar termos associados a tecnologia GET /technologies/1/terms
 
* Os termos anteriores não são removidos

7 - Associar termos PUT /technologies/1 body { "terms": [1] }
8 - Listar termos associados a tecnologia GET /technologies/1/terms

* Agora alguns são removidos outros não

9 - Associar termos PUT /technologies/1 body { "terms": [20] }
10 - Listar termos associados a tecnologia GET /technologies/1/terms

Agora nenhum é removido

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by alexandreadames** [comment]
@NaylsonFerreira após uma série de problemas no cadastro de tecnologias, o comportamento de associação de termos foi mudado. Agora se você tentar associar um termo ele verifica se já existe termos anteriores, porém por taxonomia, exemplo:

1 - Resetar banco
2 - Listar termos associados a tecnologia GET /technologies/1/terms
3 - Associar termos PUT /technologies/1 body { "terms": [8,9,10] }
4 - Listar termos associados a tecnologia GET /technologies/1/terms

Nesse caso ele associa os termos sem problemas. Já no segundo caso:

5 - Associar termos PUT /technologies/1 body { "terms": [1,2,3] }
6 - Listar termos associados a tecnologia GET /technologies/1/terms

Ele não desassocia os termos 8,9,10 porque eles não pertencem a taxonomia dos termos 1,2,3
Os termos 1,2,3 pertencem a taxonomia: CLASSIFICATION
Os termos 8,9,10 pertencem a taxonomia: STAGE

Para simular um comportamento esperado você precisa associar o termo 8-Nível 5 - Verificação da função crítica do componente e/ou subsistema em ambiente relevante. E depois associar o termo 9 Nível 6 - Demonstração do modelo de protótipo de sistema/subsistema em ambiente relevante. O sistema entende que você quer mudar o STAGE da tecnologia. Se você tentar associar o termo 1 ele não vai desassociar o 8 porque o 1 é uma  CLASSIFICATION. Resumindo, ele desassocia e associa por taxonmia.
