### ISSUE TITLE
Atualizar base de dados de Organizações

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#701]
## Feature Description

Na tabela de organizações, inserir os seguintes campos:

  * E-mail (OPCIONAL)
  * Telefone (OPCIONAL)
  * Site (OPCIONAL)
  * Logomarca (OPCIONAL)
  * Tipo: Pública, Privada ou Mista (OBRIGATÓRIO)
  * Categoria: Universidade, Instituto, Associação, Fundação, Cooperativa, Empresa, Outro (OBRIGATÓRIO)

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by alexandreadames** [comment]
@nichollasrennah só umas dúvidas:

1. O campo logomarca seria como o thumbnail da tecnologia né?
2. Quais seriam os valores default para tipo e categoria? Quando a gente atualiza a base de dados, e o campo é o obrigatório é necessário.

**Comment by nichollasrennah** [comment]
A logomarca será utilizada lá na frente em outra funcionalidade chamada
Vitrine Tecnológica de cada instituição.

O valor default é Outro

Em seg, 14 de dez de 2020 11:42, Alexandre Ádames <notifications@github.com>
escreveu:
