### ISSUE TITLE
Integrar funcionalidade de Aquisição de tecnologia com a API

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#713]
## Feature Description

Integrar funcionalidade de Aquisição de tecnologia com a API

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by luizeboli** [comment]
Fechando a issue pois o botão 'Adquirir tecnologia' já envia uma ordem de compra para a API

**Comment by luizeboli** [comment]
Reabrindo issue pois a página 'Meus pedidos' ainda está com dados mockados
