### ISSUE TITLE
Implementar sistema de PAPEL PERMISSÂO

### ISSUE THREAD

**Issue by alexandreadames** [ufersa/plataforma-sabia#73]
## Feature Description

1. Criar seed de todas as permissões do sistema
2. Criar seed de todos os papéis do sistema e atribuir as permissões em cada papel
3. Criar middleware de permissão para checar se a rota em questão precisa de uma permissão específica.
4. Criar middleware de papel para checar se a rota em questão precisa de um papel específico.

Criar rotas ou funcionalidades para:

1. Associar role a usuário
2. Associar permissões individuais a usuários
3. Verificar se um usuário tem uma certa permissão
4. Verificar se um usuário tem um certo papel
5. Associar uma permissão a um papel

---------------

## Acceptance criteria

Passar nos seguintes testes:
Rotas protegidas por uma permissão só devem ser acessadas pelo usuário com a permissão ou papel que contenha a permissão
Rotas protegidas por um papel só devem ser acessadas pelo usuário com o papel em quesstão
Ao associar um papel a um usuário ele ter acesso a rota protegida pelo papel
Ao associar uma permissão individual ao usuário ele ter acesso a rota protegida pela permissão
Ao associar uma permissão a um papel que o usuário com o papel possa acessar a rota protegida pela permissão

## Implementation Brief

Para criar os seeds usar os papeis e permissões definidas no  documento de **Requisitos Funcionais** - E-3 Usuários.
Ao proteger uma rota por permissão:
`.middleware(["auth", "permission:<permission>"]);`
A rota deve checar se o usuário está autenticado e caso esteja verificar se possui a permissão:
`const user = await auth.getUser();`
Usar o método para checar se a permissão existe:
`Permission.checkPermission(user, properties.permission);`
O método `checkPermission` verifica se o user tem uma permissão por meio do papel ou uma permissão direta.

Ao proteger uma rota por papel:
`.middleware(["auth", "role:<role>"]);`
A rota deve checar se o usuário está autenticado e caso esteja verificar se possui o papel:
`const user = await auth.getUser();`
Usar o método para checar se a permissão existe:
`Role.checkRole(user, properties.role);`

Para associar um papel a um usuário basta:
Consultar o papel
Realizar a associação ao usuário
`await user.role().associate(role);`

Para associar uma permissão a  um usuário basta:
Consultar a permissão
Verificar se o usuário não possui a permissão pelo papel
Verificar se o usuário não possui a permissão de forma direta
Realizar a associação ao usuário
`await user.permissions().save(permission);`

Para Verificar se um usuário tem uma certa permissão
Consultar todas as permissões associadas ao papel do usuário e verificar se possui a permissão
Se a primeira consulta falhar:
Consultar a se existe uma permissão direta com o usuário

Para Verificar se um usuário tem um certo papel
Realizar uma consulta direta pelo papel do usuário
`await user.load('role');`

Para Associar uma permissão a um papel
`await role.permissions().save(permission);`

**Comment by nicholasio** [comment]
IB ✅
