### ISSUE TITLE
Atualizar perfil do usuário

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#731]
## Feature Description

- Atualizar campos do cadastro de organizações no modal de criação de organizações de acordo com as inclusões dos novos campos: 
  * E-mail
  * Telefone
  * Site
  * Logomarca
  * Tipo: Pública, Privada ou Mista
  * Categoria: Universidade, Instituto, Associação, Fundação, Cooperativa, Empresa, Outro 

- Alterar o label do campo Instituição para Instituição/Empresa e o Local place para "Nome da sua instituição ou empresa"
- Checar verificação no campo Telefone, que aceita apenas formato de telefone celular. Ou seja, telefones fixos com DDD + 8 digitos não é aceito.
-  Campos CPF, CEP e Telefone aparecem erro de invalidPattern quando editamos qualquer outro campo.
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by calaca** [comment]
@nichollasrennah atualização parcial do cadastro de organizações concluído me #758. Ficaram dois ajustes para serem aplicados quando retornarmos nessa issue para adicionar os campos restantes.

**Comment by nichollasrennah** [comment]
Acho que @alexandreadames já concluiu os campos que restavam em #737

**Comment by calaca** [comment]
@nichollasrennah beleza! Vou finalizar o banco de ideias e volto pra essa issue.

**Comment by nichollasrennah** [comment]
@mateus4k era Lorena que estava nessa issue e ela precisar ser concluída. Faltam as seguintes alterações:

- Incluir campos (no mesmo molde do perfil do curador) para escolher Grande Área, Área, Subárea e especialidade de acordo com as mudanças feitas na PR #703. O usuário poder escolher até 4 especialidades.
- Inserir um checkbox perguntando se o pesquisador deseja que o nome dele seja publicado no banco de pesquisadores nas áreas escolhidas. (Essa opção está sendo feita por @alexandreadames)
- Alterar o label do campo Instituição para Instituição/Empresa e o Local place para "Nome da sua instituição ou empresa"
- Checar verificação no campo Telefone, que aceita apenas formato de telefone celular. Ou seja, telefones fixos com DDD + 8 digitos não é aceito.
- Campos CPF, CEP e Telefone aparecem erro de invalidPattern quando editamos qualquer outro campo.

**Comment by nichollasrennah** [comment]
Na PR #792 @luizeboli já resolveu a questão das máscaras. Fazer o teste para ver se está funcionando na tela de usuários.
