### ISSUE TITLE
Criar stories dos componentes do algolia

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#74]
## Feature Description
Criar stories dos componentes do algolia para que possam ser facilmente reutilizados. Fazer ajustes (caso necessário) para deixá-los o mais genéricos possíveis.

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nicholasio** [comment]
@lcnogueira passando essa pra @calaca, pode descrever mais essa issue? seria só para fazer os stories dos componentes do algolia?

**Comment by lcnogueira** [comment]
@nicholasio, isso mesmo: quando criei a ideia era criar stories dos componentes do algolia (`components/Algolia/`) para que ficasse mais simples reutilizá-los. Porém, percebi que esses componentes não serão tão utilizados. De qualquer modo, acho que vale a pena criar para eles e também para outros componentes que utilizamos e que não temos stories deles hoje.

**Comment by luizeboli** [comment]
Pessoal, lembrando que temos o PR #372 que corrige o build do Storybook e atualiza para a versão mais recente. Talvez seja interessante esperar o merge e iniciar o desenvolvimento dessa issue baseado nessa correção.

**Comment by lcnogueira** [comment]
Ah, bem lembrado pelo @luizeboli . Interessante fazermos logo o merge daquele PR, @nicholasio
