### ISSUE TITLE
Refatorar estrutura das pastas dos componentes

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#77]
## Feature Description

No lugar de ter o padrão:
```
Folder/
  --- index.js <-- componente "principal" 
```

É preferível ter o seguinte:

```
Folder/
  --- index.js <-- exports all componentes in this folder
  --- Component1.js
  --- Component2.js
  --- styles.js
```

Dessa forma se eu quero importar qualquer componente de  `Folder` eu posso simplesmente fazer assim:

```javascript
import { Component1, Component2 }  from '../Folder';
```

No lugar de 
```javascript
import Component1 from '../Folder/Component1.js';
import Component2 from '../Folder/Component2.js';
```

Não é preciso exportar os styles.js já que eles são limitados aos componentes da pasta em questão.

Um exemplo desse padrão pode ser visto aqui: 
```javascript
export { default as InputField } from './InputField';
export { default as Form } from './Form';
export { Actions } from './styles';
```
https://github.com/ufersa/plataforma-sabia/tree/master/packages/web/components/Form

e

https://github.com/ufersa/plataforma-sabia/tree/master/packages/web/components/User

---------------

## Acceptance criteria

* Tudo funciona como antes e nada foi quebrado :)

## Implementation Brief

* Atualizar todas as pastas em `web/componentes` para seguir o padrão descrito
* Atualizar todos os imports na aplicação web para utilizar o novo padrão de importação: `import { Component1.js, Component2.js }  from '../Folder';`onde for aplicável
* Não há dependecy cycles (https://spin.atomicobject.com/2018/06/25/circular-dependencies-javascript/), o próprio eslint já detect isso.

**Comment by nicholasio** [comment]
cc @lcnogueira

**Comment by nicholasio** [comment]
@ThaiMedeiros passando essa issue pra você, ela é bem simples, é uma pequeno refactoring.

**Comment by lcnogueira** [comment]
@nicholasio , a ideia aqui é refatorar especificamente o diretório dos componentes, certo? Então, pegando um exemplo, no `Footer`, ao invés de ter:
- `index.js`: componente principal
- `styles.js`: estilos.
seria
- `Footer.js`: componente principal
- `styles.js`: estilos
- `index.js`: exporta o `Footer` (e outros componentes "internos" a esse diretório).

Seria isso?

**Comment by nicholasio** [comment]
@lcnogueira Isso!
