### ISSUE TITLE
A busca indexa todos as tecnologias sem status de publicada 

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#790]
Quando clicamos no link BUSCA do menu aparecem todas as tecnologias sem o status de published.

![image](https://user-images.githubusercontent.com/48101231/106358232-9c0e0a80-62e9-11eb-9e72-899c7b7742c0.png)

**Comment by luizeboli** [comment]
@nichollasrennah houve uma issue específica pra API que resolve esse problema,  e indexa apenas tecnologias publicadas. Porém como não sei qual versão está em produção não dá pra saber se é de fato um outro problema ou apenas não subiu...

**Comment by nichollasrennah** [comment]
Vamos aguardar então!
