### ISSUE TITLE
Solicitação de assistência técnica (serviços)

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#795]
## Feature Description

- Qualquer usuário pode solicitar serviços na plataforma
- Podem adicionar quantos serviços desejar no carrinho de compras
- Ao concluir o pedido, poderá informar dados em um campo de observação 
- Os prestadores de serviço recebem as solicitações via plataforma e realiza o atendimento, nos mesmos moldes do atendimento de pedidos de tecnologias.

Já existem as telas no Figma
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
Esse chamado não fechou automaticamente com o encerramento das PR!

**Comment by luizeboli** [comment]
@nichollasrennah o pr principal não foi mergeado ainda, quando acontecer a issue será fechada

**Comment by luizeboli** [comment]
Closed by #889
