### ISSUE TITLE
Alterações na tela de login

### ISSUE THREAD

**Issue by Pedro-Alcantara-M** [ufersa/plataforma-sabia#797]
## Feature Description

O modal do "esqueci minha senha" não está ajustando para telas menores que 768px de largura.

<img width="354" alt="screenshot_2021-02-02_at_12 17 26" src="https://user-images.githubusercontent.com/77678283/106604060-dec82080-653d-11eb-92a0-7d02397441ff.png">

E diminuir a fonte dos disclaimers, pois está grande demais que precisa rolar a tela para ter acesso aos botões:
![image](https://user-images.githubusercontent.com/48101231/109644906-de1eac00-7b34-11eb-85e1-d574dbfc16d0.png)

---------------

## Acceptance criteria

Deixar o modal responsivo para que não quebre em telas menores que 768px

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
Como está essa issue? quem está fazendo ela?
