### ISSUE TITLE
No ADMIN não se consegue apagar um usuário

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#824]
## Feature Description

No ADMIN não consegue excluir um usuário pois sempre existe um relacionamento com a tabela token. Precisa permitir que se exclua um usuário e o relacionamento nesta tabela.
---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by NaylsonFerreira** [comment]
<img width="1757" alt="Captura de Tela 2021-02-11 às 16 05 23" src="https://user-images.githubusercontent.com/25301330/107686572-29efdb00-6c84-11eb-9dff-f38355c7509e.png">

**Comment by NaylsonFerreira** [comment]
Um migration pode resolver @alexandreadames
