### ISSUE TITLE
Ao editar a tecnologia o sistema não traz preenchido alguns campos

### ISSUE THREAD

**Issue by alexandreadames** [ufersa/plataforma-sabia#846]
## Feature Description

Quando pesquisador vai editar a tecnologia após o curador pedir mudanças tem uns pequenos bugs na hora de capturar os dados já preenchidos, são eles:
- Áreas (o sistema pede novamente para selecionar as áreas, mesmo elas já tendo sido selecionadas antes)

**Comment by mateus4k** [comment]
Feature da thumbnail movida para #884
