### ISSUE TITLE
Funcionalidade de Vitrine Tecnológica

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#852]
## Feature Description

A Vitrine Tecnológica será o espaço no qual serão apresentados as tecnologias e serviços de cada instituição.
- A solução será considerada da instituição quando for cadastrado por usuários que tenham a instituição definida no campo Organização.
- No cabeçalho da página colocar a logomarca da organização e todos os seus dados
- Logo abaixo inserir o título VITRINE TECNOLÓGICA DA %SIGLA%
- Inserir abaixo os cards das tecnologias (8 cards)
- Logo depois colocar os serviços (8 cards)
- Inserir paginação das tecnologias e dos serviços
- Ambas podem ser filtradas por campos determinados e ordenadas pelo usuário
- Essa página da vitrine pode ser acessada via link para que as instituições possam inserir em seus próprios portais. Uma sugestão de endereço seria: https://plataformasabia.com/vitrine/ufersa

- Precisa criar também uma página com a lista de todas as instituições que tenham soluções cadastradas em seu nome. Ao clicar na instituição a página é direcionada para a vitrine tecnológica dessa instituição. O Endereço para essa lista seria:  https://plataformasabia.com/vitrines

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
![Vitrine Tecnológica](https://user-images.githubusercontent.com/48101231/110123250-6ef8c000-7d9f-11eb-8359-378a3c968563.png)

**Comment by nichollasrennah** [comment]
@alexandreadames você começou a fazer essa issue?

**Comment by alexandreadames** [comment]
> @alexandreadames você começou a fazer essa issue?

Ainda não
