### ISSUE TITLE
Tecnologias relacionadas

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#863]
Relacionar as **tecnologias e serviços** pelas pelas palavras-chave com a tecnologia que está consultando. Trazer somente tecnologias com o status de published.

![image](https://user-images.githubusercontent.com/48101231/110040120-0539d100-7d21-11eb-85a3-e79f4e5a30e4.png)

**Comment by nichollasrennah** [comment]
Essa issue já foi concluída né?

**Comment by luizeboli** [comment]
Ainda não, está em progresso por @mateus4k
