### ISSUE TITLE
Alterações na tela inicial

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#869]
## Feature Description

- [x] No menu, retirar as opções de Forum, Ajuda, e banco de pesquisadores por enquanto.
- [x] No menu, consertar o link para cursos: cursos.plataformasabia.com
- [x] No rodapé, consertar os mesmos links e alterar Contacte-nos por **Contato**
- [x] O link dos botões para os 3 bancos não precisa abrir em uma nova janela. Pode abrir na mesma janela. O link para o Banco de editais é para o link http://plataformasabia.com/announcements e está apontando para outro.
- [x] Inativar o botão Banco de Pesquisadores
- [x] As imagens dos cards estão apertadas na largura. Pode-se utilizar para realizar o corte nas laterais.
- [x] Para tecnologias que não estão a venda não mostrar o valor nos cards.  Deixar o preço em branco. 
- [x] Nos cards inserir a sigla da instituição abaixo do título
![image](https://user-images.githubusercontent.com/48101231/110552736-9db3c500-8116-11eb-9a27-55ac87e1e142.png)

- [x] Os cards do serviço colocar a SIGLA da instituição e não o nome completo:
![image](https://user-images.githubusercontent.com/48101231/110843502-22255580-8287-11eb-8db3-d977e49d974f.png)

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
Você já começou essa issue @mateus4k? Se não tiver ainda iniciado eu passo para @luizeboli, que é a praia dele.

**Comment by mateus4k** [comment]
Ainda não comecei. Pode repassar :+1:
