### ISSUE TITLE
Ajustes no banco de ideias

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#876]
- Apaguei uma ideia via ADMIN, mas na página do banco de ideia ela ainda está aparecendo.
- Quando não tem ideia cadastrada aparece as tecnologias, que não precisa. deixar em branco mesmo.
- E também informar o nome da pessoa que cadastrou a ideia, a data e as Palavras-chave, da forma que está no design do figma.

**Comment by mateus4k** [comment]
O segundo problema será resolvido em #903

**Comment by mateus4k** [comment]
- O problema ao apagar itens será resolvido em #994
- O problema de aparecer tecnologias em outras páginas foi corrigido em #903
- A melhoria em relação ao visual da página foi movida para #996
