### ISSUE TITLE
Ao pesquisar serviços na home e clicar em "pesquisar" deve direcionar para a tab de serviços

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#877]
## Feature Description

Atualmente ao efetuar uma pesquisa com a tab 'Serviços' ativa na home, ao clicar no botão pesquisar, o usuário é redirecionado para a página de busca porém com a tab 'Tecnologias' ativa.

O comportamento esperado é que a tab escolhida permaneça ativa na página de busca após o redirecionamento.

---------------

## Acceptance criteria

* Ao pesquisar por serviços na home, direcionar o usuário para a página de busca com a tab 'Serviços' ativa. A mesma coisa para 'Tecnologias'

## Implementation Brief

* Já temos um comportamento similar no botão 'Escolher mais serviços', implementado na página do carrinho.

**Comment by mateus4k** [comment]
Already fixed in #895

**Comment by mateus4k** [comment]
Already fixed in #895
