### ISSUE TITLE
Imagem Hero é muito grande (600kb)

### ISSUE THREAD

**Issue by nicholasio** [ufersa/plataforma-sabia#88]
## Feature Description

Precisamos diminuir o tamanho da hero, diminuindo a resolução e comprimindo (usando algo como JPEGMini). Talvez seja interessante investigr o formato webp (e seu suporte nos browsers).

---------------

## Acceptance criteria

* Tamanho do hero diminui consideralvemente (idealmente não deve ser maior que 150kb)

## Implementation Brief

N/A

**Comment by lcnogueira** [comment]
Vi aqui que o `WebP` não é suportado no safari: https://caniuse.com/#feat=webp. Vale a pena utilizarmos assim mesmo?
