### ISSUE TITLE
Campos não preenchidos na aquisição de tecnologia

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#881]
O sistema apresenta a mensagem de campo não preenchido no momento da aquisição de tecnologias. No entanto, mesmo depois de preencher todos os campos a mensagem ainda aparece, não sendo possível seguir com o procedimento de aquisição.

**Comment by nichollasrennah** [comment]
@mateus4k o problema de não puxar a áre ainda persiste em produção.

**Comment by mateus4k** [comment]
@luizeboli vai dar uma olhada, @nichollasrennah 👍

**Comment by luizeboli** [comment]
Essa issue era referente a aquisição de tecnologia e não criação, vou abrir outra 👍🏻
