### ISSUE TITLE
Ícones para os tipos de serviços

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#882]
Hoje para cadastrar um serviço não é obrigatório inserir uma imagem que sirva de thumbnail. Para evitar que as pessoas não informem a imagem, nem se utilize uma única imagem para todos os serviços, será preciso definir um ícone para cada tipo de serviço. Assim os serviços serão diferenciados na imagem do tipo.

Criar os seguintes ícones em SVG:

- Serviço
- Análise
- Consultoria
- Exame
- Mão de Obra
- Perícia
- Trabalho Técnico especializado

Após a criação, a equipe de frontend precisa incluir isso na aplicação.

**Comment by JoaoPauloSMoura** [comment]
![Captura de Tela 2021-03-12 às 19 29 47](https://user-images.githubusercontent.com/46350848/111005296-5113f800-8369-11eb-86f8-6aa41f298b7e.png)
@nichollasrennah oq vc acha?

**Comment by JoaoPauloSMoura** [comment]
![image](https://user-images.githubusercontent.com/46350848/111240547-3ac0a300-85da-11eb-8b93-ffa78894e0b8.png)
[Link ](https://www.figma.com/file/EN9rw1NbspVx3IRgT3SiJL/App-Plataforma-Sabi%C3%A1?node-id=695%3A442)para figma.

**Comment by nichollasrennah** [comment]
Isso serve para @davioliveiira incluir no APP quando não tiver fotos nos serviços.

**Comment by luizeboli** [comment]
@nichollasrennah não entendi, usaremos quais das duas versões de imagens no web?

**Comment by nichollasrennah** [comment]
Usaremos essa última que o João Paulo enviou. Não mais aqueles ícones que
ele enviou no início.

Em ter., 16 de mar. de 2021 13:48, Luiz Felicio ***@***.***>
escreveu:
