### ISSUE TITLE
Criação da tela de Meus serviços

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#883]
## Feature Description

Criação de uma tela de meus serviços na área do pesquisador.

![image](https://user-images.githubusercontent.com/48101231/110843874-906a1800-8287-11eb-8424-55f6e3c527a3.png)

Os serviços terão os seguintes colunas:
- Id
- Nome do serviço
- Tipo
- Botão para Ativar/desativar (para evitar colocar um botão excluir)
- Botão de Editar

---------------

## Acceptance criteria

* 

## Implementation Brief

*

**Comment by JoaoPauloSMoura** [comment]
![Meus-serviços](https://user-images.githubusercontent.com/46350848/111238192-5aa19800-85d5-11eb-9190-9ceafe05145f.png)
@luizeboli segue imagem da tela de meus serviços, e aqui o [link ](https://www.figma.com/file/8mZn2wEyabfktc4C58Rf4s/Plataforma-Sabi%C3%A1?node-id=3652%3A0)para a tela no figma.
