### ISSUE TITLE
Algolia sempre inicializa com o índice de tecnologias

### ISSUE THREAD

**Issue by luizeboli** [ufersa/plataforma-sabia#903]
## Feature Description

Atualmente percebemos que o Algolia sempre inicializa com o índice de tecnologias e depois troca para o desejado. Isso gera um comportamento inesperado que pode ser uma rápida apresentação de dados incorretos nos cards. Por exemplo, ao carregar a página de Editais, o primeiro request feito é para o índice de tecnologias.

---------------

## Acceptance criteria

* Carregar as páginas que busquem dados do Algolia e usem outro índice além do de tecnologias, e não inicializar com o índice de tecnologias

## Implementation Brief

* Acredito que em algum lugar que esteja mais acima na árvore de componentes, está chamando o Provider do Algolia, sem passar índice (isso faz chamar o de tecnologias), ou o próprio de tecnologias

**Comment by luizeboli** [comment]
Já fiz um `console.log` do `indexName` no Provider e por algum motivo ele inicializa como `technologies`.

Não tive tempo para investigar

**Comment by mateus4k** [comment]
Update: problema referente ao componente `MainSearch` sendo chamado durante o SSR 👍
