### ISSUE TITLE
Alterar algumas URLs de ingles para portugues

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#919]
**Alterar as seguintes URLs públicas que apontam para nomes em ingles para portugues:**
- http://plataformasabia.com/ideas-bank -> http://plataformasabia.com/ideias
- http://plataformasabia.com/announcements -> http://plataformasabia.com/editais
- http://plataformasabia.com/researchers-bank -> http://plataformasabia.com/pesquisadores

O restante pode manter como está.

**Comment by luizeboli** [comment]
There's a good discussion about that [here](https://github.com/vercel/next.js/issues/8241)

**Comment by luizeboli** [comment]
There's also a [RFC ](https://github.com/vercel/next.js/discussions/9081)
