### ISSUE TITLE
Sincronizar URL com página de busca

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#94]
## Feature Description

Sincronizar a URL da página de busca com o campo os elementos (campo de busca, filtros, elementos de ordenação, páginação etc.). O objetivo é permitir que um usuário que navegue a partir de outra página para a página de busca, ao chegar na página, já veja os resultados filtrados. Isso será útil, dentre outros casos, quando:
- O usuário utilizar a busca da página inicial;
- O usuário navegar a partir de uma página de detalhes da tecnologia. 

## Acceptance criteria
- Os resultados devem ser filtrados quando o usuário navegar a partir da busca na página inicial.

## Implementation Brief
Utilizar como ponto de partida:
- Guia da própria documentação da `react-instatnsearch`: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/#overview;
- Exemplo de uso da lib do próprio github da `react-instantsearch`: https://github.com/algolia/react-instantsearch/tree/master/examples/next
- Exemplo de uso da lib do github do `nextjs`: https://github.com/zeit/next.js/tree/canary/examples/with-algolia-react-instantsearch

## Additional information
- Verificar se estamos realizando o trabalho correto do ponto de vista de SSR: https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react/

**Comment by nicholasio** [comment]
Boa, tinha me esquecido disso. Muito importante isso.
