### ISSUE TITLE
[Search] Scroll to the top when pagination changes

### ISSUE THREAD

**Issue by mateus4k** [ufersa/plataforma-sabia#956]
The page does not scroll when the pagination changes, so the user has a bad usability experience.

![Screen Recording 2021-03-23 at 3 57 50 PM](https://user-images.githubusercontent.com/30202634/112203142-f98b4d00-8bf0-11eb-8280-ffaf590eb57b.gif)

**Comment by luizeboli** [comment]
Take a look [here](https://www.algolia.com/doc/api-reference/widgets/scroll-to/react/)
