### ISSUE TITLE
[Cadastro de tecnologia] Imagens não estão sendo enviados corretamente

### ISSUE THREAD

**Issue by mateus4k** [ufersa/plataforma-sabia#957]
## Feature Description

Percebi duas situações onde as imagens não estão sendo salvas corretamente.
1. Quando o usuário adiciona somente uma imagem nada é enviado como `thumbnail_id` para o endpoint de atualização da tecnologia. Quando o usuário adiciona mais de uma imagem, funciona normalmente pelo o que testei.
2. Quando o usuário passa pela tela de edição de attachments sem trocar as imagens, o `thumbnail_id` novamente é enviado como `null`.

## Acceptance criteria

* O usuário deve poder ter somente uma única imagem na sua tecnologia;
* O usuário deve poder salvar sem modificações a página de `edit/map-and-attachments` sem ficar com o `technology.thumbnail_id` igual a `null` após isso

## Implementation Brief

*

**Comment by nichollasrennah** [comment]
@luizeboli veja esse pro também.
