### ISSUE TITLE
Criar página de vitrine tecnologia de uma organização

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia#980]
A Vitrine Tecnológica será o espaço no qual serão apresentados as tecnologias e serviços de cada instituição.

A solução será considerada da instituição quando for cadastrado por usuários que tenham a instituição definida no campo Organização.

No cabeçalho da página colocar a logomarca da organização e todos os seus dados

Logo abaixo inserir o título VITRINE TECNOLÓGICA DA %SIGLA%

Inserir abaixo os cards das tecnologias (8 cards)

Logo depois colocar os serviços (8 cards)

Inserir paginação das tecnologias e dos serviços

Ambas podem ser filtradas por campos determinados e ordenadas pelo usuário

Essa página da vitrine pode ser acessada via link para que as organizações possam inserir em seus próprios portais. Uma sugestão de endereço seria: https://plataformasabia.com/vitrine/ufersa

![Vitrine Tecnológica](https://user-images.githubusercontent.com/48101231/113766489-da61e480-96f3-11eb-973f-dc9536deb225.png)

**Comment by mateus4k** [comment]
SEO data:
```json
{
  "description": "Conheça as tecnologias e serviços desenvolvidos na {{name}} - {{initials}}",
  "keywords": [
    "vitrine tecnológica",
    "tecnologias",
    "serviços",
    "prestação de serviços",
    "plataforma sabiá",
    "semiárido",
    "universidade",
    "instituições",
    "instituto",
    "inovação",
    "invenção",
    "nit",
    "núcleo de inovação tecnológica",
    "agência de inovação"
  ],
  "title": "Vitrine tecnológica da {{initials}} na Plataforma Sabiá"
}
```
