### ISSUE TITLE
Improve i18n setup

### ISSUE THREAD

**Issue by mateus4k** [ufersa/plataforma-sabia#992]
## Feature Description

Prevent this warning:
![image](https://user-images.githubusercontent.com/30202634/114254716-6475ab80-9987-11eb-8b55-be47232ca58d.png)

https://github.com/freeCodeCamp/freeCodeCamp/issues/41211#issuecomment-783702803

https://react.i18next.com/latest/i18next-instance

**Comment by luizeboli** [comment]
We don't use this library anymore.
